### ISSUE TITLE
Add Ruby and Ruby DevKit

### ISSUE THREAD

**Issue by KINGSABRI** [fireeye/commando-vm#1]
Hello guys 
Thank you for the awesome efforts. 

Please add the latest version of Ruby 2.6 and its DevKit.

![image](https://user-images.githubusercontent.com/1071827/55202679-78537800-51d9-11e9-8cc9-533b7f8e7e16.png)

![image](https://user-images.githubusercontent.com/1071827/55202677-6f62a680-51d9-11e9-8315-4b97283f8f1d.png)

![image](https://user-images.githubusercontent.com/1071827/55202685-7f7a8600-51d9-11e9-871c-34c26f29ef8e.png)

![image](https://user-images.githubusercontent.com/1071827/55202705-8ef9cf00-51d9-11e9-877d-865cecf5c813.png)

Chose #3 

Thanks!

**Comment by day1player** [comment]
Added to roadmap

**Comment by day1player** [comment]
Added with version 1.1
