### ISSUE TITLE
BUG: PwndPasswordsNTLM / PwnedPasswordsNTLM typo

### ISSUE THREAD

**Issue by b3n-j4m1n** [fireeye/commando-vm#101]
There's a typo in the packages.json files and/or package source for PwnedPasswordsNTLM that causes the install to fail.

"Pwnd" vs "Pwned"

![image](https://user-images.githubusercontent.com/19149345/66265558-6e838f00-e864-11e9-96da-ba881231f86c.png)

**Comment by day1player** [comment]
Resolved.
