### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by ammislam** [fireeye/commando-vm#103]
I ran `cup all` command from command prompt, and got the following two issue. Let me know if they are of any major issue to use the VM or not. 

![commando-vm-error1](https://user-images.githubusercontent.com/16259882/67661830-5c40d080-f98c-11e9-9bd3-4f0efd59309d.JPG)
![commando-vm-error2](https://user-images.githubusercontent.com/16259882/67661836-61058480-f98c-11e9-8e3d-f20cd7f06478.JPG)

**Comment by day1player** [comment]
@ammislam there is a small bug with the config package. You may have to delete the README off of the desktop and try running the config install again. If you are just *upgrading* your install as you said then you should be fine, if this is a new install you will want to make sure that config install completes.

metasploit and proxycap you can probably live without; if not, you can manually install them if you need it. We are aware of both of those packages as well.
