### ISSUE TITLE
BUG : Incomplete TamperProtection settings detection on install

### ISSUE THREAD

**Issue by juuouki** [fireeye/commando-vm#104]
On some Windows 10 Editions, the value for a disabled instance of TamperProtection in the registry is not '0'. When I disable TamperProtection my registry value sets to '4'. 

I'm using Windows 10 Enterprise with latest updates and Australian localisation. For Home and Pro installs the setting is 0. According to documentation it's "supposed" to be 2 for Enterprise when disabled; however, there are clearly times when it's also 4 but what conditions they are I'm not sure. I will continue to look around, but in the meantime to get the install running I updated the install.ps1 script, line 255 with the below:

```
$tmperProtectSetting = $(Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows Defender\Features" -Name "TamperProtection").TamperProtection
    if ($tmperProtectSetting -eq 1 -OR $tmperProtectSetting -eq 3 -OR $tmperProtect -eq 5){
```

**Comment by day1player** [comment]
We did anticipate this, which is why we included an option to continue installation in the event TamperProtection is not set to 0

You should be prompted to continue installation even if the script doesnt think TamperProtection is disabled.
