### ISSUE TITLE
BUG spiderfoot.docker.fireeye v0.0.0.7 won't install

### ISSUE THREAD

**Issue by Shkk1337** [fireeye/commando-vm#105]
I have noticed that several packages threw errors during the install.
I tried to install it manually after the install script.
One important (for me) package has a special error:

C:\Users\Administrator\Desktop+>cinst -y spiderfoot.docker.fireeye --force
Chocolatey v0.10.15
Installing the following packages:
spiderfoot.docker.fireeye
By installing you accept licenses for the packages.
Progress: Downloading spiderfoot.docker.fireeye 0.0.0.7... 100%

spiderfoot.docker.fireeye v0.0.0.7 (forced)
spiderfoot.docker.fireeye package files install completed. Performing other installation steps.
Sending build context to Docker daemon  19.53MB

Step 1/8 : FROM alpine:latest
 ---> 965ea09ff2eb
Step 2/8 : COPY requirements.txt .
 ---> Using cache
 ---> 41d0a469d736
Step 3/8 : RUN apk --update add --no-cache --virtual build-dependencies gcc git curl py2-pip swig         tinyxml-dev python2-dev musl-dev openssl-dev libffi-dev libxslt-dev     && apk --update --no-cache add python2 musl openssl libxslt tinyxml     && pip --no-cache-dir install wheel     && pip --no-cache-dir install -r requirements.txt     && addgroup spiderfoot     && adduser -G spiderfoot -h /home/spiderfoot -s /sbin/nologin                -g "SpiderFoot User" -D spiderfoot     && rmdir /home/spiderfoot     && cd /home     && curl -sSL https://github.com/smicallef/spiderfoot/archive/master.tar.gz        | tar -v -C /home -xz     && mv /home/spiderfoot-master /home/spiderfoot     && chown -R spiderfoot:spiderfoot /home/spiderfoot     && apk del --purge build-dependencies     && rm -rf /var/cache/apk/*     && rm -rf /root/.cache
 ---> Running in 23afa7874885
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
(1/51) Installing binutils (2.32-r0)
(2/51) Installing gmp (6.1.2-r1)
(3/51) Installing isl (0.18-r0)
(4/51) Installing libgomp (8.3.0-r0)
(5/51) Installing libatomic (8.3.0-r0)
(6/51) Installing libgcc (8.3.0-r0)
(7/51) Installing mpfr3 (3.1.5-r1)
(8/51) Installing mpc1 (1.1.0-r0)
(9/51) Installing libstdc++ (8.3.0-r0)
(10/51) Installing gcc (8.3.0-r0)
(11/51) Installing ca-certificates (20190108-r0)
(12/51) Installing nghttp2-libs (1.39.2-r0)
(13/51) Installing libcurl (7.66.0-r0)
(14/51) Installing expat (2.2.8-r0)
(15/51) Installing pcre2 (10.33-r0)
(16/51) Installing git (2.22.0-r0)
(17/51) Installing curl (7.66.0-r0)
(18/51) Installing libbz2 (1.0.6-r7)
(19/51) Installing libffi (3.2.1-r6)
(20/51) Installing gdbm (1.13-r1)
(21/51) Installing ncurses-terminfo-base (6.1_p20190518-r0)
(22/51) Installing ncurses-terminfo (6.1_p20190518-r0)
(23/51) Installing ncurses-libs (6.1_p20190518-r0)
(24/51) Installing readline (8.0.0-r0)
(25/51) Installing sqlite-libs (3.28.0-r1)
(26/51) Installing python2 (2.7.16-r1)
(27/51) Installing py-setuptools (40.8.0-r1)
(28/51) Installing py2-pip (18.1-r0)
(29/51) Installing gc (8.0.4-r0)
(30/51) Installing libltdl (2.4.6-r6)
(31/51) Installing libunistring (0.9.10-r0)
(32/51) Installing guile-libs (2.0.14-r0)
(33/51) Installing guile (2.0.14-r0)
(34/51) Installing pcre (8.43-r0)
(35/51) Installing swig (3.0.12-r4)
(36/51) Installing tinyxml (2.6.2-r1)
(37/51) Installing tinyxml-dev (2.6.2-r1)
(38/51) Installing pkgconf (1.6.1-r1)
(39/51) Installing python2-dev (2.7.16-r1)
(40/51) Installing musl-dev (1.1.22-r3)
(41/51) Installing openssl-dev (1.1.1d-r0)
(42/51) Installing linux-headers (4.19.36-r0)
(43/51) Installing libffi-dev (3.2.1-r6)
(44/51) Installing libgpg-error (1.36-r2)
(45/51) Installing libgcrypt (1.8.5-r0)
(46/51) Installing libxml2 (2.9.9-r2)
(47/51) Installing libxslt (1.1.33-r2)
(48/51) Installing zlib-dev (1.2.11-r1)
(49/51) Installing libxml2-dev (2.9.9-r2)
(50/51) Installing libxslt-dev (1.1.33-r2)
(51/51) Installing build-dependencies (20191113.125826)
Executing busybox-1.30.1-r2.trigger
Executing ca-certificates-20190108-r0.trigger
OK: 244 MiB in 65 packages
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
[91mWARNING: [0m[91mIgnoring http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)
[0mfetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
[91mWARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz: network error (check Internet connection and firewall)
[0m[91mERROR: unsatisfiable constraints:
[0m  openssl (missing):
    required by: world[openssl]
ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The command '/bin/sh -c apk --update add --no-cache --virtual build-dependencies gcc git curl py2-pip swig         tinyxml-dev python2-dev musl-dev openssl-dev libffi-dev libxslt-dev     && apk --update --no-cache add python2 musl openssl libxslt tinyxml     && pip --no-cache-dir install wheel     && pip --no-cache-dir install -r requirements.txt     && addgroup spiderfoot     && adduser -G spiderfoot -h /home/spiderfoot -s /sbin/nologin                -g "SpiderFoot User" -D spiderfoot     && rmdir /home/spiderfoot     && cd /home     && curl -sSL https://github.com/smicallef/spiderfoot/archive/master.tar.gz        | tar -v -C /home -xz     && mv /home/spiderfoot-master /home/spiderfoot     && chown -R spiderfoot:spiderfoot /home/spiderfoot     && apk del --purge build-dependencies     && rm -rf /var/cache/apk/*     && rm -rf /root/.cache' returned a non-zero code: 1
The install of spiderfoot.docker.fireeye was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\spiderfoot.docker.fireeye\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - spiderfoot.docker.fireeye (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\spiderfoot.docker.fireeye\tools\chocolateyinstall.ps1'.
 See log for details.

COMMANDO 13/11/2019 13:59:04,19
C:\Users\Administrator\Desktop+>

**Comment by day1player** [comment]
Appears to have been an issue with a Docker file
