### ISSUE TITLE
BUG several packages are not installing correctly

### ISSUE THREAD

**Issue by Shkk1337** [fireeye/commando-vm#106]
I have noticed that during the execution of the install.ps1 script and the call of commandovm.win10.installer.fireeye several packages are throwing errors and not installing correctly:

python3 (error can be ignored)
x64dbg (ERROR: Cannot bind argument to parameter 'Path' because it is null.)
proxycap (Checksum error)
metasploit (404 not found error)
PoshC2	(404 not found error)
spiderfoot (success after manual install)
spiderfoot.docker.fireeye as well (check issue https://github.com/fireeye/commando-vm/issues/105)
wfuzz (Not found)
FOCA (threw errors)
Watson (404 https://github.com/rasta-mouse/Watson/releases/download/2.0/Watson_Net35.exe)
openvpn (threw errors / manual install revealed it is installed [openvpn.fireeye v2.4.6.20190317 already installed])

**Comment by Pa55w0rd** [comment]
I had the same problem

**Comment by martialhax** [comment]
Same here right now with Metasploit, Neo4J, PoshC2 and many others....bad URL or file doesn't exist or forbidden errors...

**Comment by day1player** [comment]
Packages have been updated. Please open a new issue for new packages.
