### ISSUE TITLE
BUG Kali on WSL has no packages in it

### ISSUE THREAD

**Issue by Shkk1337** [fireeye/commando-vm#107]
Hello again,

after the install script went through, I have noticed that the installed Kali on WSL does not have any packages installed. This leads to errors when trying to start the Kali Gui, which can for example be resolved by installing xfce4 inside WSL manually.

**Comment by htnhan** [comment]
@Shkk1337  do you mind uploading the content of %programdata%\chocolatey\logs\chocolatey.log and %programdata%\chocolatey\logs\summary.log? 

Thank you,

**Comment by Shkk1337** [comment]
Sure! :)

[chocolatey.log](https://github.com/fireeye/commando-vm/files/3845084/chocolatey.log)
[choco.summary.log](https://github.com/fireeye/commando-vm/files/3845085/choco.summary.log)

**Comment by day1player** [comment]
Unable to reproduce errors.
