### ISSUE TITLE
unmanaged dependency on chrome.exe with cyberchef.flare

### ISSUE THREAD

**Issue by tonykarre** [fireeye/commando-vm#11]
The installation of cyberchef.flare fails during the attempted association of ".htm" with chrome.exe, because chrome.exe did not exist.

Started with a clean Windows 10 VM from Win10_1809Oct_v2_English_x64.iso
Chrome was not manually installed by me prior to the attempt to install Commando.

During installation, cyberchef.flare failed with this error in the Chocolately log file:

Running 'ChocolateyScriptRunner' for cyberchef.flare v8.27.0.20190328 with packageScript 'C:\ProgramData\chocolatey\lib\cyberchef.flare\tools\chocolateyInstall.ps1', packageFolder:'C:\ProgramData\chocolatey\lib\cyberchef.flare', installArguments: '', packageParameters: '',
Running 'C:\ProgramData\chocolatey\lib\cyberchef.flare\tools\chocolateyInstall.ps1'
Running Install-ChocolateyFileAssociation -extension '.htm' -executable 'C:\Program Files (x86)\Google\Chrome\Application\chrome.exe' 
'C:\Program Files (x86)\Google\Chrome\Application\chrome.exe' does not exist, not able to create association
ERROR: 'C:\Program Files (x86)\Google\Chrome\Application\chrome.exe' does not exist, not able to create association
Built-in PowerShell host called with ['[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1';& Import-Module 'C:\ProgramData\boxstarter\Boxstarter.chocolatey\Boxstarter.chocolatey.psd1' -DisableNameChecking -ArgumentList $true; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\cyberchef.flare\tools\chocolateyInstall.ps1' -installArguments '' -packageParameters '''] exited with '-1'.
Calling command ['"C:\Windows\System32\shutdown.exe" /a']
Command ['"C:\Windows\System32\shutdown.exe" /a'] exited with '1116'

**Comment by tonykarre** [comment]
I subsequently manually installed chrome, then re-ran the install.ps1 script.  The ".htm" file association was then able to be accomplished, and cyberchef.flare was successfully installed.

**Comment by htnhan** [comment]
@tonykarre  We recently pushed a new version of Cyberchef to fix this. Thank you for reporting this issue.
