### ISSUE TITLE
cup all errors

### ISSUE THREAD

**Issue by darkknightuk** [fireeye/commando-vm#112]
`citrix-receiver.fireeye`` v2019.03.14.3
citrix-receiver.fireeye package files upgrade completed. Performing other installation steps.
ERROR: Cannot bind argument to parameter 'Path' because it is null.
The upgrade of citrix-receiver.fireeye was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\citrix-receiver.fireeye\tools\chocolateyInstall.ps1'.
 See log for details.`

`Failed to install git
WARNING: [!] Installing using host choco.exe! Errors are ignored. Please check to confirm adobereader.fireeye is installed properly
WARNING: [!] Executing: iex choco upgrade adobereader.fireeye --cacheLocation C:\Users\batman\AppData\Local\ChocoCache -y
Chocolatey v0.10.15 Upgrading the following packages: adobereader.fireeye By upgrading you accept licenses for the packages.  You have adobereader.fireeye v2019.03.17.0 installed. Version 2019.03.17.3 is available based on your source(s).  Progress: Downloading adobereader.fireeye 2019.03.17.3... 61% Progress: Downloading adobereader.fireeye 2019.03.17.3... 100%  adobereader.fireeye v2019.03.17.3 adobereader.fireeye package files upgrade completed. Performing other installation steps. ERROR: Cannot bind argument to parameter 'Path' because it is null. The upgrade of adobereader.fireeye was NOT successful. Error while running 'C:\ProgramData\chocolatey\lib\adobereader.fireeye\tools\chocolateyInstall.ps1'.  See log for details.  Chocolatey upgraded 0/1 packages. 1 packages failed.  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).  Failures  - adobereader.fireeye (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\adobereader.fireeye\tools\chocolateyInstall.ps1'.  See log for details.`
`ExitCode: -1
Failed to install adobereader.fireeye`

Various similar errors when trying to update I have recently updated Windows 10 Pro 1909

**Comment by darkknightuk** [comment]
[chocolatey.log](https://github.com/fireeye/commando-vm/files/4016741/chocolatey.log)

**Comment by day1player** [comment]
Investigating... 👍

**Comment by goremageddon** [comment]
> Investigating... 👍

Directory: C:\ProgramData\chocolatey\lib-bad

Mode LastWriteTime Length Name

d----- 1/27/2020 7:58 PM commandovm.win10.config.fireeye
d----- 1/27/2020 7:44 PM dnspy.flare
d----- 1/27/2020 7:48 PM metasploit.flare
d----- 1/27/2020 7:51 PM PoshC2.fireeye
d----- 1/27/2020 7:47 PM proxycap.fireeye
d----- 1/27/2020 7:43 PM python3
d----- 1/27/2020 7:55 PM Watson.fireeye
d----- 1/27/2020 7:55 PM wfuzz.fireeye
d----- 1/27/2020 7:46 PM x64dbg.fireeye

This is what im getting consistently.

**Comment by day1player** [comment]
Unable to reproduce errors.
