### ISSUE TITLE
BUG: Request Covenant version bump

### ISSUE THREAD

**Issue by sctlfb** [fireeye/commando-vm#113]
Requesting a Covenant version bump, so that users can issue command "cup Covenant.fireeye" to easily/quickly update to latest version (0.4), which has enhanced functionality.

**To Reproduce**
1. Github shows that version is now at 0.4 (https://github.com/cobbr/Covenant/releases)
2. C:\Tools\Covenant\Changelog.md shows that installed version on Commando VM is ver 0.2

**Version**
 - OS: Win 10

An update to Covenant C2 vers 0.4 will bring improved functionality, but will deprecate requirement for Elite as a client to the Covenant C2 broker/listener. As per Github for Elite (https://github.com/cobbr/Elite)

**Comment by day1player** [comment]
Thank you for the issue.

We are working on updating all of our packages for the next release.

We will also be releasing a new version of Covenant with Docker soon.

**Comment by day1player** [comment]
Temporarily removed support for Covenant. Will be looking to automate install in a future release.
