### ISSUE TITLE
Metasploit upgrade failing

### ISSUE THREAD

**Issue by challberg** [fireeye/commando-vm#115]
I've been trying to upgrade metasploit for some time now, and finally digging into the cause of the failure.

My results for trying a new install (after deleting) are below, but I'll sum up here. Using "cinst metasploit.flare", or the previous "choco upgrade metasploit flare -f", the install tries to upgrade to version 5.0.53, from 5.0.16, but windows.metasploit.com currently only goes back as far as 5.0.69, which explains the errors below. My question then is this - where does the version info for the install come from?  I've tried putting in the correct filename in the install.ps1 script, but that seems to get overwritten every time I try to install.  Running the script on its own doesn't work either.

Thanks!

COMMANDO 1/21/2020 8:29:05 PM
PS C:\ProgramData\chocolatey\lib > cinst metasploit.flare
Chocolatey v0.10.15
Installing the following packages:
metasploit.flare
By installing you accept licenses for the packages.

metasploit.flare v5.0.53.20191010
metasploit.flare package files install completed. Performing other installation steps.
Attempt to get headers for https://windows.metasploit.com/metasploit-framework-5.0.53%2B20191010152730.git.6.2bb1605-1rapid7-1-x64.msi failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://windows.metasploit.com/metasploit-framework-5.0.53%2B20191010152730.git.6.2bb1605-1rapid7-1-x64.msi'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
Downloading metasploit.flare 64 bit
  from 'https://windows.metasploit.com/metasploit-framework-5.0.53%2B20191010152730.git.6.2bb1605-1rapid7-1-x64.msi'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://windows.metasploit.com/metasploit-framework-5.0.53%2B20191010152730.git.6.2bb1605-1rapid7-1-x64.msi'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
The install of metasploit.flare was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\metasploit.flare\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs
[chocolatey.log](https://github.com/fireeye/commando-vm/files/4095376/chocolatey.log)
[chocolatey.log](https://github.com/fireeye/commando-vm/files/4095378/chocolatey.log)

\chocolatey.log).

Failures
 - metasploit.flare (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\metasploit.flare\tools\chocolateyInstall.ps1'.
 See log for details.

**Comment by RlinFinn** [comment]
from 'https://windows.metasploit.com/metasploit-framework-5.0.53%2B20191010152730.git.6.2bb1605-1rapid7-1-x64.msi'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://windows.metasploit.com/metasploit-framework-5.0.53%2B20191010152730.git.6.2bb1605-1rapid7-1-x64.msi'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
The upgrade of metasploit.flare was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\metasploit.flare\tools\chocolateyInstall.ps1'.
 See log for details.



i have the same issue !!

**Comment by challberg** [comment]
I see this was confirmed in issue #127 yesterday.  Any thoughts on a fix?

**Comment by day1player** [comment]
Package has been updated, please install with `cinst -y metasploit.flare`
