### ISSUE TITLE
Question: How to install Mimikatz on command line

### ISSUE THREAD

**Issue by shankar-shankar** [fireeye/commando-vm#118]
Tried to install Mimikatz and get the following error. Kindly help

Installing the following packages:
mimikatz
By installing you accept licenses for the packages.
mimikatz not installed. The package was not found with the source(s) listed.
 Source(s): 'https://www.myget.org/F/fireeye/api/v2;https://chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://chocolatey.org/docs/troubleshooting for more
 assistance.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - mimikatz - mimikatz not installed. The package was not found with the source(s) listed.
 Source(s): 'https://www.myget.org/F/fireeye/api/v2;https://chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://chocolatey.org/docs/troubleshooting for more
 assistance.

**Comment by day1player** [comment]
Try installing with the package name:

`cinst -y mimikatz.fireeye`

It looks like you are leaving out the `.fireeye`
