### ISSUE TITLE
Package installation fails with Received an unexpected EOF or 0 bytes from the transport stream

### ISSUE THREAD

**Issue by tonykarre** [fireeye/commando-vm#12]
Several packages fail with "Received an unexpected EOF or 0 bytes from the transport stream" error.  The following packages always fail:

tortoisesvn 1.11.1.28492
autoit.install 3.3.14.5
putty.portable 0.71
vlc 3.0.6
winscp.install 5.15
autohotkey.portable 1.1.30.01
gimp 2.10.8
fiddler 5.0.20182.28034
HxD 2.2.1.0
openvpn.fireeye 2.4.6.20190314
commandovm.win10.config.fireeye 1.0.0.2

This occurs on a clean Windows 10 VM created from this ISO: Win10_1809Oct_v2_English_x64

For each one, you can see the package downloading from 0% to almost 100%. Something must fail and it retries the download, going from 0% to 90-ish%.  Then the failure is registered in the command window.  For instance:

Progress: Downloading openvpn.fireeye 2.4.6.20190314... 91%                                                            openvpn.fireeye not installed. An error occurred during installation:
 Received an unexpected EOF or 0 bytes from the transport stream.

I see this in the boxstarter log file:

openvpn.fireeye is not installed. Installing...
[NuGet] Attempting to resolve dependency 'chocolatey (â‰¥ 0.10.8)'.
openvpn.fireeye not installed. An error occurred during installation:
 Received an unexpected EOF or 0 bytes from the transport stream.
openvpn.fireeye package files upgrade completed. Performing other installation steps.
No package information as package is null.
No package information as package is null.
No package information to save as package is null.
No package information to save as package is null.
Sending message 'HandlePackageResultCompletedMessage' out if there are subscribers...
The upgrade of openvpn.fireeye was NOT successful.
openvpn.fireeye not installed. An error occurred during installation:
 Received an unexpected EOF or 0 bytes from the transport stream.

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - openvpn.fireeye (exited 1) - openvpn.fireeye not installed. An error occurred during installation:
 Received an unexpected EOF or 0 bytes from the transport stream.
Sending message 'PostRunMessage' out if there are subscribers...
[2019-03-31T15:25:37.6996320-07:00:::PID 7848] Boxstarter: restoring current directory location to C:\Windows\system32
VERBOSE: Boxstarter: restoring current directory location to C:\Windows\system32
[2019-03-31T15:25:37.6996320-07:00:::PID 7848] Boxstarter: Exit Code: 1
VERBOSE: Boxstarter: Exit Code: 1
Chocolatey reported an unsuccessful exit code of 1. See C:\Users\tonyk\AppData\Local\Boxstarter\boxstarter.log for details.
[2019-03-31T15:25:37.7152552-07:00:::PID 7848] + Boxstarter finished Calling Chocolatey to install openvpn.fireeye. This may take several minutes to complete... 00:03:46.7459448
[2019-03-31T15:25:37.7152552-07:00:::PID 7848] + Boxstarter finished Calling Chocolatey to install openvpn.fireeye. This may take several minutes to complete... 00:03:46.7459448
+ Boxstarter finished Calling Chocolatey to install openvpn.fireeye. This may take several minutes to complete... 00:03:46.7459448
[2019-03-31T15:25:37.7309341-07:00:::PID 7848] 

[2019-03-31T15:25:37.7465312-07:00:::PID 7848] ExitCode: 1
ExitCode: 1
Failed to install openvpn.fireeye

**Comment by machGhosTine** [comment]
I am having this same issue, and the installer just keeps looping and trying to install tortoisesvn, python3 upgrade, and vlc.

**Comment by htnhan** [comment]
Folks, can you confirm that you do not have any networking issues?

Also, if you are connected to your corporate VPN, or if your host system has any end point software, these security software may block the download thinking they are malicious and only provide an empty file.

**Comment by machGhosTine** [comment]
@htnhan I have no network issues, and no software interfering. it seems to have an issue with python, it has tried grabbing it for over an hour now with no success.

**Comment by magicallizard** [comment]
Can confirm this issue also

**Comment by tonykarre** [comment]
@htnhan I'm not on a VPN, and I just disabled my host Kaspersky, so I don't have anything running.  I reran the installer, and the same packages failed.  I did see that it picked up the new version of cyberchef and successfully installed that.  But my set of failing packages still fail in the same way.  Note that when I reran the installer several times, it always fails with the exact same set of packages.  The majority of the packages downloaded and installed fine.

**Comment by machGhosTine** [comment]
I'm in the same boat as @tonykarre I also use Kaspersky and have it disabled running the script. same packages fail for me as well, but the majority are g2g

**Comment by MalwareMechanic** [comment]
@machGhosTine @tonykarre Can you try manually downloading a package to test for EOF? Go to Chocolatey, type the name of the package, and look for the download link on the left-hand side. Here's the link for TortoiseSVN: https://chocolatey.org/api/v2/package/tortoisesvn/1.11.1.28492

If this works, also try manually installing it using an admin PowerShell prompt via: `choco install tortoisesvn`

Hopefully this will help narrow down the issue

**Comment by tonykarre** [comment]
Manual downloading of tortoisesvn was successful using Edge.  I was also able to manually install it manually:

PS C:\Windows\system32> choco install tortoisesvn
Chocolatey v0.10.13
Installing the following packages:
tortoisesvn
By installing you accept licenses for the packages.
Progress: Downloading tortoisesvn 1.11.1.28492... 100%

tortoisesvn v1.11.1.28492 [Approved]
tortoisesvn package files install completed. Performing other installation steps.
Installing 64 bit version
Installing tortoisesvn...
tortoisesvn has been installed.
  tortoisesvn may be able to be automatically uninstalled.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
 The install of tortoisesvn was successful.
  Software installed as 'msi', install location is likely default.

Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).


My other install.ps1 is still running (takes FOREVER for gimp), so I'll rerun it later to see if it recognizes that tortoisesvn is OK now.

**Comment by machGhosTine** [comment]
@MalwareMechanic this worked for me, used ps prompt to install python. I'll use this to install the rest of the packages that are failing. thank you!

**Comment by tonykarre** [comment]
@MalwareMechanic I was able to manually install gimp.  Here's my main observation - when manually installing it, the download sequence ran about 20x faster than when through the install.ps1 script.  I'm wondering why they would be different.  I also notiPS C:\Windows\system32> choco install gimp.fireeye
Chocolatey v0.10.13
Installing the following packages:
gimp.fireeye
By installing you accept licenses for the packages.
Progress: Downloading gimp 2.10.8... 100%
Progress: Downloading gimp.fireeye 1.0.0.0... 100%

gimp v2.10.8 [Approved]
gimp package files install completed. Performing other installation steps.
Installing gimp...
gimp has been installed.
  gimp can be automatically uninstalled.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
 The install of gimp was successful.
  Software installed to 'C:\Program Files\GIMP 2\'

gimp.fireeye v1.0.0.0
gimp.fireeye package files install completed. Performing other installation steps.
 The install of gimp.fireeye was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

Chocolatey installed 2/2 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
PS C:\Windows\system32>ced that with tortoisesvn.  So definitely something is different between the two methods.

**Comment by machGhosTine** [comment]
I agree with @tonykarre that they ran much faster through ps choco command. in any event, I was able to get all failing packages installed through this method, then re-ran installer and all is good now.

**Comment by tonykarre** [comment]
@machGhosTine @MalwareMechanic 
I manually installed the remaining packages, then reran the installer to confirm that everything is OK.  I think the root of this problem is the interaction between boxstarter and chocolately.  Like maybe some kind of timing or race condition where boxstarter can't correctly determine the actual status of chocolately.   It almost acts like Boxstarter fires up chocolately and polls whether it is done or not, and something goes wrong.

For instance, after manually installing hxd.fireeye, then rerunning the installer, look at what is produced by the installer:

+ Boxstarter starting Calling Chocolatey to install hxd.fireeye. This may take several minutes to complete...
+ Boxstarter starting Calling Chocolatey to install hxd.fireeye. This may take several minutes to complete...
Upgrading the following packages:
hxd.fireeye
By upgrading you accept licenses for the packages.
hxd.fireeye is not installed. Installing...
[NuGet] Attempting to resolve dependency 'hxd '.
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
Progress: Downloading hxd.fireeye 1.0.0.0... 100%
[NuGet] Installing 'hxd.fireeye 1.0.0.0'.
[NuGet] Successfully installed 'hxd.fireeye 1.0.0.0'.

hxd.fireeye v1.0.0.0
hxd.fireeye package files upgrade completed. Performing other installation steps.
 The upgrade of hxd.fireeye was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

Chocolatey upgraded 1/1 packages. 0 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
+ Boxstarter finished Calling Chocolatey to install hxd.fireeye. This may take several minutes to complete... 00:00:02.9111089
+ Boxstarter finished Calling Chocolatey to install hxd.fireeye. This may take several minutes to complete... 00:00:02.91

So I think that there is some weakness in the boxstarter/chocolately interaction that is causing these failures.

OK - I think I'm done for the day  :)

**Comment by MalwareMechanic** [comment]
@tonykarre Thanks for the insight! I know Boxstarter uses a slightly different version of Chocolatey and we try to use Boxstarter's version as much as we can because it handles restarts really well. Let's keep an eye on this and see how many others are affected by it as well.

**Comment by unashamedgeek** [comment]
I've experienced these issues. After the first run attempt I had a number of missing tools and ran it a second time. It installed more tools on the second pass, but tools  like gimp and SecLists failed. I'm now running a third time to watch what fails and will see if anything in my logs show different from what others experience. This as on a new Windows 10 vm on Vmware Fusion running from a home network and no network issues.

**Comment by machGhosTine** [comment]
thanks to @tonykarre for the logs and the great insight, and @MalwareMechanic for the choco install fix. I used that to install the broken packages I was getting (gimp, vlc, openvpn, python3), then re-ran the installer to verify and all is good. only thing I see is an issue with visualstudio-installer not matching source, but doesn't seem effect anything though.
