### ISSUE TITLE
No proxy support

### ISSUE THREAD

**Issue by ST8Z6FR57ABE6A8RE9UF** [fireeye/commando-vm#13]
Installing on a vanilla Win10 VM fails when a proxy is configured which requires authentication:
```
[ * ] Installing Boxstarter
Exception calling "DownloadString" with "1" argument(s): "The remote server returned an error: (407) Proxy
Authentication Required."
At C:\Users\user\Desktop\commando-vm-master\install.ps1:60 char:3
+   iex ((New-Object System.Net.WebClient).DownloadString('http://boxst ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
```

**Comment by htnhan** [comment]
@ST8Z6FR57ABE6A8RE9UF  Can you elaborate more on your use case, why you need to support a proxy and specifically what support do you need?

**Comment by ST8Z6FR57ABE6A8RE9UF** [comment]
My organisation requires a proxy for Internet access which needs authentication. The install prompts for the logged on users password, but not a proxy a credential, resulting in the above error. I tried some variations on this code prior to .\install.ps1 without luck.
https://serverfault.com/questions/689949/powershell-set-default-proxy-configuration-for-all-ps-cmdlets

We also have an unauthenticated proxy, however only whitelisted URLs are accessible. Using this proxy does not give connection errors, however the module is not downloaded:
```
Import-Module : The specified module 'C:\ProgramData\boxstarter\boxstarter.chocolatey\boxstarter.chocolatey.psd1' was not loaded because no valid module file was found in any module directory.
At line:41 char:9
+         Import-Module "$env:ProgramData\boxstarter\boxstarter.chocola ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (C:\ProgramData\...chocolatey.psd1:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
```

**Comment by ST8Z6FR57ABE6A8RE9UF** [comment]
This issue can be closed.
I manually configured the proxy settings in install.ps1 which downloaded https://boxstarter.org/bootstrapper.ps1. I even updated proxy references in those functions.

However the Chocolatey install itself makes similar calls to when running https://chocolatey.org/install.ps1
I will attempt to build when off-site, and connected without a proxy.

**Comment by day1player** [comment]
@ST8Z6FR57ABE6A8RE9UF Thanks I will close this issue shortly. If you would like to, feel free to detail how you manually configured proxy settings in the install.ps1 file that way others who might run into the issue can use this as reference.

**Comment by ST8Z6FR57ABE6A8RE9UF** [comment]
I split out lines similar to this
```
iex ((New-Object System.Net.WebClient).DownloadString('https://boxstarter.org/bootstrapper.ps1'))
```
Adding proxy properties to the WebClient object
```
$wc = New-Object System.Net.WebClient
$wc.Proxy = [System.Net.WebProxy]::new("<proxy server>",<proxy port>)
$wc.Proxy.Credentials = (Get-Credential)
iex ($wc.DownloadString('https://boxstarter.org/bootstrapper.ps1'))
```
In hindsight, this would not be sustainable since basically every downloaded script (including chocolatey) makes similar calls. Updating `$Global:PSDefaultParameterValues` would also not work since we are referencing the .Net object directly and not using `Invoke-WebRequest` cmdlets.
If an authenticated proxy is needed, the only option which worked was to configure it as the system proxy in Control Panel > Internet Options, and run the install.ps1 in the context of an allowed user.
