### ISSUE TITLE
libraries.python2.fireeye error when updating python3

### ISSUE THREAD

**Issue by digitalohm** [fireeye/commando-vm#131]
**Describe the bug and expected behavior**
Error upgrading python using cup all

 Updating 'python3 3.7.2' to 'python3 3.8.2' failed. Unable to find a version of 'libraries.python2.fireeye' that is compatible with 'python3 3.8.2'.

from chocolatey.log 
2020-04-17 23:37:27,317 9396 [ERROR] - Failures
2020-04-17 23:37:27,319 9396 [ERROR] -  - python3 (exited 1) - python3 not upgraded. An error occurred during installation:
 Updating 'python3 3.7.2' to 'python3 3.8.2' failed. Unable to find a version of 'libraries.python2.fireeye' that is compatible with 'python3 3.8.2'.
2020-04-17 23:37:27,322 9396 [DEBUG] - Sending message 'PostRunMessage' out if there are subscribers...
2020-04-17 23:37:27,339 9396 [DEBUG] - Exiting with 1

**To Reproduce**
1. Powershell Admin
2. cup all

**Screenshots**
<img width="1221" alt="Screen Shot 2020-04-17 at 11 46 58 PM" src="https://user-images.githubusercontent.com/5267192/79630494-9eaac500-8106-11ea-8944-244d695702f0.png">

**Version**
[System.Environment]::OSVersion.Version
10.0.18363.0

**Comment by yellow-starburst** [comment]
same error

**Comment by day1player** [comment]
fixed in #147 removed libraries package from install
