### ISSUE TITLE
Multiple packages failing install: No error output

### ISSUE THREAD

**Issue by dwizel** [fireeye/commando-vm#132]
New install of CommandoVM after the resolution to Metapsloit updating failing consistently. New install is showing a lot of apps not being installed. 
![image](https://user-images.githubusercontent.com/34634731/80273234-d5d73280-8713-11ea-8deb-960fc6df69d7.png)

**Version**
 - OS: [e.g. Win7]

**Additional context**

**Comment by cherkie** [comment]
I have the same issue, a bit less apps, though:
![image](https://user-images.githubusercontent.com/36137163/80370891-e5c45300-8888-11ea-9f17-b655de8f0d81.png)

And they all come back with similar errors - packages not found at the destination.

![2020-04-27 13_03_23-Cmder](https://user-images.githubusercontent.com/36137163/80370935-faa0e680-8888-11ea-808e-e3d2bae43560.png)

**Comment by mrpogden** [comment]
Such a shame this isnt properly maintained, as It has such potential. Come on Mandiant, update the links in the chocolatey repo to the correct/newest versions and these bugs disappear. Its not that difficult.  Otherwise, you're going to loose a lot of interest very quickly.

**Comment by day1player** [comment]
@mrpogden this recurring issue is specific to only one package, Metasploit. Unfortunately Metasploit removes their old `.msi` files as soon as a new one is available, and they constantly change the name. This makes it very hard to automate the creation/updating of this package.

We also need to make sure we download the file and calculate the correct checksum before updating the package for install. As it is now, it is a manual effort from us to keep everything updated and we do so as time permits. We have, admittedly, dropped the ball on this one particular package, but we are working on a better solution for self notifying and fixing when the package breaks.

Users can always manually download and execute the [Metasploit installer](https://windows.metasploit.com) on their own if the package fails to install.

**Comment by mrpogden** [comment]
@day1player actually, there are at least 4 packages that come back with 404 errors. It’s not just metasploit.  Mimikatz tried to download a binary version that doesn’t even exist.  Someone raised that weeks ago and there was a reply saying it would be fixed but wasn’t.

**Comment by martialhax** [comment]
I am in the process of installing right now and using the exact recommended stats - Windows 10 1903 etc. Fresh OS install with all MS Updates. Multiple packages have failed for me too including apimonitor and GoogleChrome. I tried manually as well while the rest continues per install Notes - "...You can check what packages failed install by listing the C:\ProgramData\chocolatey\lib-bad
directory. Failed packages are stored by folder name. You can attempt manual install with the
following command: cinst -y <package name>..." and per https://github.com/fireeye/commando-vm/issues/123

<Insert sad face here>

**Comment by day1player** [comment]
@martialhax do they continue to fail upon manual install? If so could you post some error output?

**Comment by martialhax** [comment]
Well Google Chrome succeeded manually today but the others did not (yet). I'm running the install script again after it finished sometime late last night. It finished but the readme was not placed on Desktop and the background didn't change etc. I'll see after it finishes again. Screenshots of other manual runs for stuff in the C:\ProgramData\chocolatey\lib-bad
directory here:
![Screen Shot 2020-05-21 at 11 29 44 AM](https://user-images.githubusercontent.com/17996721/82581699-93f4ad00-9b56-11ea-95ae-d4ef45f795e6.png)
![Screen Shot 2020-05-21 at 11 31 04 AM](https://user-images.githubusercontent.com/17996721/82581757-ab339a80-9b56-11ea-89b3-2ae95c81932b.png)

**Comment by day1player** [comment]
@martialhax the API Monitor failling looks like a new issue so I have created an issue for us to update it. As for Spiderfoot and AMASS. Do you have docker installed?

Before you continue trying to install docker images, are you on a Windows host machine?

**Comment by day1player** [comment]
@martialhax as for the Readme and Desktop image, after you finish with the install script (if that doesnt fix it) you will need to manually install the config package (make sure you are in an admin prompt):
```
cinst -y commandovm.win10.config.fireeye
```

**Comment by martialhax** [comment]
> @martialhax the API Monitor failling looks like a new issue so I have created an issue for us to update it. As for Spiderfoot and AMASS. Do you have docker installed?
> 
> Before you continue trying to install docker images, are you on a Windows host machine?

The Win 10 1903 is running in Fusion on a Mac OS 10.15.4 host box and the script did install Docker Desktop but when it runs auto at startup or manually it gives the attached screenshot error. Personally I'm not keen on running the Kali or Docker in this VM anyway. I see no benefit vs running either in the host (maybe make them optional installs?) I had thought Virtualization Support in the VM was optional anyway (just needed by these if used).

![Screen Shot 2020-05-21 at 11 39 55 AM](https://user-images.githubusercontent.com/17996721/82583666-f3ec5300-9b58-11ea-91be-84c0a3f5c346.png)

**Comment by martialhax** [comment]
> @martialhax as for the Readme and Desktop image, after you finish with the install script (if that doesnt fix it) you will need to manually install the config package (make sure you are in an admin prompt):
> 
> ```
> cinst -y commandovm.win10.config.fireeye
> ```

OK will do.

**Comment by day1player** [comment]
@martialhax thats good, Fusion should have no issues.. Can you make sure you have set the 'Enable hypervisor' setting for the VM? It will be under Settings -> Processors & Memory -> Advanced Options

<img width="626" alt="image" src="https://user-images.githubusercontent.com/37482972/82583889-f0ed6480-9b50-11ea-8b2a-9281c083343e.png">

> Personally I'm not keen on running the Kali or Docker in this VM anyway. I see no benefit

I have found that my workflow on Commando is much better with these options. For example text file processing in bash is much easier than cmd or powershell, and some programs are much easier to install with Docker such as Covenant. A lot of times on internal pentests or when using a VPN you can only connect one machine to the network, so having the capabilities of everything on one VM can be really clutch. If you can get it working, give it a try, if you decide you would rather run multiple VMs then I can also help you set up a custom profile so that Docker/Kali WSL are not installed :-)

**Comment by martialhax** [comment]
Ahh good catch....no its not set. I'll have to wait until I can power it down however. AFA Docker and  Kali in the VM I'll just try to get everything installed/working and then will give it a try. I won't knock it completely until I try it :-) Thanks.

**Comment by day1player** [comment]
Thanks for posting 👍 let me know if you have further issues.

I will be changing the default install profile in a few weeks to remove Docker and Kali (I will also be creating other optional profiles which will include them). My hope is to speed up the default install by removing some more problematic packages and having less stuff to download unless the user wants it.. the build will then be much easier to install and will take less space.

**Comment by martialhax** [comment]
Only things left in lib-bad now are - libraries.python2.fireeye and wfuzz.fireeye now. (they have related dependencies looks like). I had to run "cinst -y commandovm.win10.config.fireeye" manually cause it error out in the script run. Only noticed one Warning (red):

![Screen Shot 2020-05-21 at 9 00 17 PM](https://user-images.githubusercontent.com/17996721/82623606-2c664e00-9ba6-11ea-9430-d227d0f74c9c.png)

**Comment by day1player** [comment]
fixed in #147 added logging capabilities to the installer
