### ISSUE TITLE
Question: How to resize Kali GUI window

### ISSUE THREAD

**Issue by TheD3C4Y** [fireeye/commando-vm#133]
**Is your feature request related to a problem? Please describe.**
is there an option to resize the kali GUI window. I use it on a tripple monitor Setup in a Hyper-V VM an dneed to use kali for some tasks but the bar is stretching across all screens. is there an config file somewhere where i can resize it so it is  a smaller window ?

**Comment by day1player** [comment]
Yes there should be a way to change the size using the xlaunch utility: `C:\Program Files\VcXsrv\xlaunch.exe`

I am looking into it.

**Comment by day1player** [comment]
stale
