### ISSUE TITLE
Question: PTT with mimikatz

### ISSUE THREAD

**Issue by rhp2001** [fireeye/commando-vm#137]
Once below commands are executed for pass the ticket error occurs at the final stage.
mimikatz.exe "privilege::debug" 
"kerberos::ptt GTnuckc.kirbi"

is returning with below error

* File: 'GTnuckc.kirbi': ERROR kuhl_m_kerberos_ptt_File ; kull_m_file_readData (0x00000002)

**To Reproduce**
below required to be executed in the same environment
mimikatz.exe 
privilege::debug 
kerberos::ptt GTnuckc.kirbi

**Screenshots**
![image](https://user-images.githubusercontent.com/65563295/82247854-3266ef80-9958-11ea-88c4-175b5bd26824.png)

**Version**
 - OS: [e.g. Win10]

**Additional context**
Prerequisites for the above command was successfully executed.

**Comment by day1player** [comment]
I believe the error code you are seeing is [Error code 2 "file not found"](https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-). Have you tried passing in the full path to the `kirbi` file?
