### ISSUE TITLE
Update Readme to address lack of support for insider preview versions of Windows

### ISSUE THREAD

**Issue by y0sh188** [fireeye/commando-vm#140]
The build number of Win 10 1903 is "18362" but if condition use the value "18361". 
Installer script prompted error message if we used the tested version of Windows 10.

OS: [Windows 10, 1903]

**Comment by day1player** [comment]
It looks to me like that is the Insider Preview version of Windows 10 which, while you are correct, it is Windows 10 1903, it is not something we plan on supporting. I will make an update to the readme.

Thank you!

**Comment by day1player** [comment]
fixed in #147
