### ISSUE TITLE
Question: Certain packages appearing to hang during install

### ISSUE THREAD

**Issue by samirpeu** [fireeye/commando-vm#142]
Hi!

I am trying to install on Windows 10 64 bit VM, but installation will not continue when trying to install 64bit GIT.

Would be nice, if you could fix it or tell me what to do.
Thanks!

**Comment by day1player** [comment]
@samirpeu what is the error you are getting? Is this happening during install?

**Comment by samirpeu** [comment]
I get no error. Yes, it`s happening during install.
This is my screen. After 2 hours, still the same.
https://ibb.co/TWdBb2L

**Comment by day1player** [comment]
@samirpeu can you please paste photo in github here?

**Comment by samirpeu** [comment]
![Screenshot](https://user-images.githubusercontent.com/66269626/83439489-8d621180-a443-11ea-9478-784c1ca906ec.jpg)

**Comment by day1player** [comment]
@samirpeu is the install hanging there?

**Comment by day1player** [comment]
Try clicking in the terminal window and hitting enter a few times.. Sometimes that will stop it from hanging

**Comment by samirpeu** [comment]
Yes, it`s hanging there. I hit enter many times, but it seems not to continue. But at moment I am not sure, if it accepted hitting Enter, because it takes 100% of CPU. I can`t do anything at moment.

**Comment by day1player** [comment]
@samirpeu I would let it keep going for a while longer, if it hangs for more than 30 mins or an hour, just try canceling it and restarting the install script

**Comment by samirpeu** [comment]
don't know why, but now it continues. But now it's hanging again at adobe install :-( Would it be possible, that you upload install package, containing all files, so that it could be installed offline? I think it would be much better.

**Comment by day1player** [comment]
That is not really possible the way that Chocolatey is built. A lot of packages themselves will call out to the internet to download the actual installers, so even if you could download every package you would still need some internet connection. 

I've seen some packages like this hang randomly on installs, I think the best thing to do is keep checking in, hitting enter in the box, and waiting for it to continue. You might also try to increase the resources for the vm, such as increasing the CPUs or RAM.

The last option is to try manually installing some packages like this as described in #123 . You could maybe ctrl+c to cancel the current package, it will fail, but then you can manually install and let the install process continue.
