### ISSUE TITLE
Metasploit Fails to Install via install.ps1 & via choco install metasploit.flare

### ISSUE THREAD

**Issue by divinehand** [fireeye/commando-vm#143]
I didn't have too many issues with the install, couple failed packages, one big one was metasploit.  It failed during the automated install and afterwards via manual method:  choco install metasploit.flare

Any help would much appreciated, thanks!

See below this line for output:
-------------------------------
PS C:\Windows\system32 > choco install metasploit.flare
Chocolatey v0.10.13
Installing the following packages:
metasploit.flare
By installing you accept licenses for the packages.
Progress: Downloading metasploit.flare 5.0.90.20200518... 100%

metasploit.flare v5.0.90.20200518
metasploit.flare package files install completed. Performing other installation steps.
**Attempt to get headers for http://windows.metasploit.com/metasploit-framework-5.0.90%2B20200518152542.git.2.33708c2-1rapid7-1-x64.msi failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url** **'http://windows.metasploit.com/metasploit-framework-5.0.90%2B20200518152542.git.2.33708c2-1rapid7-1-x64.msi'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
Downloading metasploit.flare 64 bit
  from 'http://windows.metasploit.com/metasploit-framework-5.0.90%2B20200518152542.git.2.33708c2-1rapid7-1-x64.msi'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'http://windows.metasploit.com/metasploit-framework-5.0.90%2B20200518152542.git.2.33708c2-1rapid7-1-x64.msi'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
The install of metasploit.flare was NOT successful.**
Error while running 'C:\ProgramData\chocolatey\lib\metasploit.flare\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - metasploit.flare (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\metasploit.flare\tools\chocolateyInstall.ps1'.
 See log for details.
COMMANDO 6/2/2020 11:43:37 AM

**Comment by divinehand** [comment]
Fyi, I'm guessing the specific version being called isn't at that URL or something has changed or it requires TLS connection instead of HTTP but I'd like someone to weigh in because I'm a CommandoVM noob    =)

**Comment by day1player** [comment]
@divinehand thanks for the issue. You are correct, the version isnt there anymore! The 404 error means the server was not able to find the file. 

I have updated and uploaded the package again, please try manually installing again:
`cinst -y metasploit.flare`

If it fails with a 404 again, please wait 15 mins then try again as the package might be cached. Please let me know if you have any issues.

**Comment by divinehand** [comment]
Awesome, thank you very much!  I'll give it a try    =)

**Comment by divinehand** [comment]
Wicked! It worked, thanks very much for your time!

**Comment by day1player** [comment]
No prob!
