### ISSUE TITLE
Question: How to setup anonymous SMB share - smbserver.py 

### ISSUE THREAD

**Issue by digitalohm** [fireeye/commando-vm#144]
**Describe the bug and expected behavior**
When attempting to use the smbserver.py script, access permissions are denied.

**To Reproduce**

```
COMMANDO 6/16/2020 7:18:53 AM
PS C:\Users\me\Documents\loot > smbserver.py loot C:\Users\me\Documents\loot
Impacket v0.9.22.dev1 - Copyright 2020 SecureAuth Corporation

Traceback (most recent call last):
  File "C:\Python27\Scripts\smbserver.py", line 68, in <module>
    server = smbserver.SimpleSMBServer(listenAddress=options.interface_address, listenPort=int(options.port))
  File "C:\Python27\lib\site-packages\impacket\smbserver.py", line 4620, in __init__
    self.__server = SMBSERVER((listenAddress,listenPort), config_parser = self.__smbConfig)
  File "C:\Python27\lib\site-packages\impacket\smbserver.py", line 3746, in __init__
    socketserver.TCPServer.__init__(self, server_address, handler_class)
  File "C:\Python27\lib\SocketServer.py", line 420, in __init__
    self.server_bind()
  File "C:\Python27\lib\SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "C:\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 10013] An attempt was made to access a socket in a way forbidden by its access permissions
```

**Screenshots**
NA

**Version**
```
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      18363  0
```

**Additional context**

Since windows is already listening on 139,445 this error makes sense.  However, does anyone know the steps in getting this to work?  I've gone through a plethora of potential fixes involving; guest account, anonymous access, different port number etc, with little luck.  The goal would be to somehow get anonymous smb sharing capabilities like using the smbserver.py on a linux distro would allow :(

**Comment by day1player** [comment]
I would look at setting up an anonymous share, similar to what is described in [this post](https://nikolar.com/2015/03/10/creating-network-share-with-anonymous-access/). 

AFAIK a lot of impacket was created in order to mimic Windows functionality, in this case, the Windows OS has the ability to host SMB shares, so you shouldn't need impacket to recreate that.

**Comment by digitalohm** [comment]
Thanks @day1player 

I've tried a few different ways and something is escaping me.  I must be missing something simple.  After editing the settings in the security policy as described in the link: 

I will normally run: 

```
New-SmbShare -Name "loot" -Path $pwd.Path -FullAccess "Everyone", "Guest", "ANONYMOUS LOGON"
Enable-LocalUser -Name "Guest"
```

The above is a quick way to bring up the share, and enable/disable the Guest account, and to enabled the share from the current directory 

Regardless of what system I try to connect with (OS X, Kali, Windows 10), the share always requires authentication

some examples: 

```
PS C:\Users\User> net use \\someip\loot /user:Guest
Enter the password for 'Guest' to connect to 'someip':
System error 1385 has occurred.

Logon failure: the user has not been granted the requested logon type at this computer.

PS C:\Users\User> net use \\someip\loot /user:COMMANDO\Guest
Enter the password for 'COMMANDO\Guest' to connect to 'someip':
System error 1385 has occurred.

Logon failure: the user has not been granted the requested logon type at this computer.

PS C:\Users\User> net use \\someip\loot
Enter the user name for 'someip':
System error 1223 has occurred.

The operation was canceled by the user.
```

**Comment by digitalohm** [comment]
Thanks @day1player 

I've tried a few different ways and something is escaping me.  I must be missing something simple.  After editing the settings in the security policy as described in the link: 

I will normally run: 

```
New-SmbShare -Name "loot" -Path $pwd.Path -FullAccess "Everyone", "Guest", "ANONYMOUS LOGON"
Enable-LocalUser -Name "Guest"
```

The above is a quick way to bring up the share, and enable/disable the Guest account, and to enabled the share from the current directory 

Regardless of what system I try to connect with (OS X, Kali, Windows 10), the share always requires authentication

some examples: 

```
PS C:\Users\User> net use \\someip\loot /user:Guest
Enter the password for 'Guest' to connect to 'someip':
System error 1385 has occurred.

Logon failure: the user has not been granted the requested logon type at this computer.

PS C:\Users\User> net use \\someip\loot /user:COMMANDO\Guest
Enter the password for 'COMMANDO\Guest' to connect to 'someip':
System error 1385 has occurred.

Logon failure: the user has not been granted the requested logon type at this computer.

PS C:\Users\User> net use \\someip\loot
Enter the user name for 'someip':
System error 1223 has occurred.

The operation was canceled by the user.
```

**Comment by day1player** [comment]
Understandably frustrating, my guess is it might have something to do with your network settings (home, public, etc.). There may be some helpful answers [here](https://superuser.com/questions/513730/cannot-access-network-share-the-user-has-not-been-granted-the-requested-logon)?

**Comment by digitalohm** [comment]
Perfect, one of the comments had the solution:

[Another thing to check is the 'Deny access to this computer from the network' policy, which overrides the 'allow access' policy if the same user is in both.](https://superuser.com/a/632095)

Looks like this setting had the Guest user in it, once removed, reloaded security policy and then: 

```
PS C:\Users\User> net use \\someip\loot /user:COMMANDO\Guest
Local name
Remote name       \\someip\loot
Resource type     Disk
Status            OK
# Opens           0
# Connections     1
The command completed successfully.

PS C:\Users\User> dir \\someip\loot


    Directory: \\someip\loot


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         6/17/2020   9:53 AM              0 proof.txt
```

thank you very much @day1player your Google fu is greater than mine!

**Comment by digitalohm** [comment]
so after the security changes are made:

we can use the following to quickly setup an anonymous share and enable the guest account, transfer files to/from the target, then remove the share and disable the Guest account

-FullAccess might not be needed (but we want to read/write)

```
New-SmbShare -Name "loot" -Path $pwd.Path -FullAccess "Everyone", "Guest", "ANONYMOUS LOGON"
Enable-LocalUser -Name Guest
Remove-SmbShare -Name loot -force
Disable-LocalUser -Name Guest
```

**Comment by day1player** [comment]
Awesome thank you for posting the solution here 👍 let me know if you have any more issues!
