### ISSUE TITLE
how many hours does this take to install?

### ISSUE THREAD

**Issue by angrypapa** [fireeye/commando-vm#145]
I've been installing this for 9 hours with very good internet connection speed and very fast hardware. Is this normal? I wonder if I should just cancel it.

Any way to measure progress? Am I stuck in a bogus loop or...?

**Comment by day1player** [comment]
@angrypapa that does seem like an incredibly long time. I would recommend increasing resources if you need to, and also restarting the install script. Please make sure to read issues #123  and #122 as those two issues can seriously delay install.

**Comment by day1player** [comment]
@angrypapa please reach out if you continue to have issues

**Comment by angrypapa** [comment]
I don't think the issues I had were related with the issues you pointed. Basically it seems that after installing it tries to upgrade the packages. Correct? This seems to go in a loop due to a bug I didn't track. I basically had to cancel. I've been trying to get a clean install of this and it happened to me twice. What's the point of trying to upgrade right after the installation?

**Comment by day1player** [comment]
Yes you are correct the installer did try to do that, there was no real point to it and I actually just fixed it [here](https://github.com/fireeye/commando-vm/blob/a2b96c9a60ffce41fb28fbc7f88ea354e754127c/commandovm.win10.installer.fireeye/tools/chocolateyinstall.ps1#L138).

Perhaps try giving it another shot with the new install script. I've also created a [Lite](https://github.com/fireeye/commando-vm/tree/master/Profiles) profile that could also help decrease install time.
