### ISSUE TITLE
Script installs WSL and Hyper-V unnecessarily

### ISSUE THREAD

**Issue by deltaclock** [fireeye/commando-vm#146]
**Remove any docker dependencies from profile.json, expect no wsl or hyper-v install**

I believe the bug comes from the `commandovm.win10.preconfig.fireeye` package which has enabled `InstallLinuxSubsystem` and `InstallHyperV` in the Default.preset

Changing anything in the chocolateyinstall.ps1 of the package doesnt seem to work since chocolatey pulls the packages from `https://www.myget.org/F/fireeye/api/v2` so my local preset doesnt get honored.

What is the best way to modify all those scripts based on my needs without breaking everything else?

**Version**
 - OS: [e.g. Win10-2004]

**Comment by day1player** [comment]
@deltaclock your timing is impeccable. I will be fixing this today in order to solve some other related issues (#120, #95)

**Comment by day1player** [comment]
Please give me a few hours and the issue will be resolved

**Comment by day1player** [comment]
Fixed in #147 , please let me know if you continue to have issues.
