### ISSUE TITLE
dnSpy fails to install

### ISSUE THREAD

**Issue by Passenger23** [fireeye/commando-vm#148]
Fresh install 6/24, dnSpy.flare fails.

Appears dnSpy updated 6/23 to v6.1.5. Install script calls v6.1.4

Thanks

**Comment by 6a306265** [comment]
way I fixed it-

go to the C:\ProgramData\chocolatey\lib-bad\dnspy.flare\tools\ folder

change the url and checksum filelds in the chocolateyInstall.ps1 file to below -

  url           = 'https://github.com/0xd4d/dnSpy/releases/download/v6.1.5/dnSpy-net472.zip'
  checksum      = 'C5046BDA93B3D4C23CDD715CED2F92E3D5A5F95CA6CDB6245D9BE68733891583'

then as admin run  "choco install C:\ProgramData\chocolatey\lib-bad\dnspy.flare\dnspy.flare.nuspec"

This downloaded latest dnSpy and created shortcuts for me

**Comment by day1player** [comment]
Package has been updated. manually install with `cinst -y dnspy.flare`
