### ISSUE TITLE
Question: Pivoting

### ISSUE THREAD

**Issue by digitalohm** [fireeye/commando-vm#154]
I've been wondering what the best way to accomplish pivoting with commando vm would be.

Was hoping someone could bounce some ideas around, I've seen this https://github.com/shunf4/proxychains-windows but haven't heard too much about it.  Initially I suppose we could just do all this from within a docker container but it would be cool to find out if this is something we can accomplish through the WSL2 or Windows OS level.  I'm sure we can create a single tunnel, but what about performing something akin to: `proxychains nmap -p- targetip`

**Comment by day1player** [comment]
@digitalohm Sorry I did not respond earlier. I would recommend using a C2 framework for this. C2's such as Covenant (or Cobalt Strike) have built in port scanners within their implants.

**Comment by day1player** [comment]
This could also be a whole conversation because it also might depend on what your goals are and what situation you are in. I would invite you to join the [BloodHound Gang Slack channel](https://twitter.com/_wald0/status/1116492036696186880?s=20) if you would like to chat about it. You can join the #commando-vm channel or DM me directly (day1player).

**Comment by digitalohm** [comment]
Thanks @day1player the herokuapp links for the invites do not seem to be working :(

**Comment by day1player** [comment]
Uh oh.. Slack is kind of a pain. Are you getting an error?

**Comment by digitalohm** [comment]
Yeah the link [](https://bloodhoundgang.herokuapp.com) will time-out With he following error 

```

Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail

```

**Comment by day1player** [comment]
@digitalohm it looks like they disabled that invite link for the time being, can you send me your email to commandovm@fireeye.com? I can submit a request in the bloodhound slack to get you an invite.

**Comment by digitalohm** [comment]
@day1player 

```
Your message to commandovm@fireeye.com couldn't be delivered.
The group commandovm only accepts messages from people in its organization =
or on its allowed senders list, and your email address isn't on the list.
```
:(

**Comment by day1player** [comment]
@digitalohm 🤦 

You can email me directly, jacob.barteaux@mandiant.com
