### ISSUE TITLE
not exist "TamperProtection"

### ISSUE THREAD

**Issue by MakeDangerousWarning** [fireeye/commando-vm#155]
there is a screepshot.

[+] No custom profile is provided...
[+] Checking if script is running as administrator..
        this is the way
[+] Checking to make sure Windows Defender Tamper Protection is disabled
Get-ItemProperty : 路径 HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Defender\Features 处不存在属性 TamperProtection。
所在位置 C:\Users\Administrator\Downloads\commando-repository\commando-vm-master (1)\commando-vm-master\install.ps1:285
 字符: 7
+   if (Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows Defend ...
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (TamperProtection:String) [Get-ItemProperty]，PSArgumentException
    + FullyQualifiedErrorId : System.Management.Automation.PSArgumentException,Microsoft.PowerShell.Commands.GetItemPr
   opertyCommand

        Tamper Protection is off, looks good.
[+] Checking to make sure Operating System is compatible
        Windows build 17763 supported.
[+] Checking if host has been configured with updates
        [ERR] This machine has not been updated in the last 30 days, do you want to try installing updates automatically? Y/N

**Comment by day1player** [comment]
@MakeDangerousWarning did the install fail?

**Comment by MakeDangerousWarning** [comment]
> @MakeDangerousWarning did the install fail?

installed successfully .
