### ISSUE TITLE
Metasploit bcrypt Issue

### ISSUE THREAD

**Issue by KarmicElk** [fireeye/commando-vm#157]
OS: Windows 10 2004 build 19041.388
CommandoVM version 2020.2
Metasploit-framework v5.0.101

Unable to run Metasploit latest build installed via MSI installer downloaded directly from windows.metasploit.com.

When trying to run msfconsole from an Administrator cmd prompt, I get the following error:

![2020-07-25 16_42_53-Window](https://user-images.githubusercontent.com/49791682/88467749-a3b2a980-ce97-11ea-859f-156c21ce1bbf.png)

I have tried running "choco upgrade metasploit.flare -f" from an Administrator PowerShell prompt after the manual install, but that does not work either.

![2020-07-25 16_41_23-Window](https://user-images.githubusercontent.com/49791682/88467753-aad9b780-ce97-11ea-9d4c-76eec4baab7e.png)

I'm not sure where to go from here. Any help would be appreciated!

**Comment by day1player** [comment]
@KarmicElk looks like an interesting error to say the least.. I would try manually installing metasploit from https://windows.metasploit.com

You might also want to uninstall your current version first which I believe can be done through Windows Apps & Features panel

**Comment by day1player** [comment]
updated metasploit to 0729

**Comment by KarmicElk** [comment]
@day1player Sorry for the late reply, haven't had time to test. The update worked so using _choco upgrade metasploit.flare_ works for install, but I still have the same bcrypt issue. Maybe it's a problem with the Metasploit installer? Should I post an issue over there?

**Comment by day1player** [comment]
@KarmicElk it might be worth posting an issue there to see what they say, I am not too familiar with the workings behind Metasploit on Windows. It could be an issue with Ruby.

**Comment by KarmicElk** [comment]
@day1player Ok thanks, I'll open one over there. Seems weird though since I can see that bcrypt is installed, it's just not seeing it for some reason.

**Comment by day1player** [comment]
@KarmicElk I saw that too.. Its one of those frustrating issues 😂

**Comment by KarmicElk** [comment]
@day1player Someone over at the metasploit guthub recommended a fix that worked:

https://github.com/rapid7/metasploit-framework/issues/13933#issuecomment-667881372

Change the file:
\metasploit-framework\embedded\framework\metasploit-framework.gemspec, line 56
from: spec.add_runtime_dependency 'bcrypt', '3.1.12'
to: spec.add_runtime_dependency 'bcrypt', '~> 3.1.12'

**Comment by day1player** [comment]
Thank you @KarmicElk for posting the solution.. The internet doesn't deserve you!
