### ISSUE TITLE
commandovm.win10.config.fireeye FAIL

### ISSUE THREAD

**Issue by TeRompoErQ** [fireeye/commando-vm#158]
**Describe the bug and expected behavior**
commandovm.win10.config.fireeye FAIL with this output:

COMMANDO 28/07/2020 13:22:08,14
C:\Users\Peppe>cinst -y commandovm.win10.config.fireeye -f
Chocolatey v0.10.15
Installing the following packages:
commandovm.win10.config.fireeye
By installing you accept licenses for the packages.
Progress: Downloading commandovm.win10.config.fireeye 2.0.0.7... 100%

commandovm.win10.config.fireeye v2.0.0.7 (forced)
commandovm.win10.config.fireeye package files install completed. Performing other installation steps.
[+] Beginning host configuration...
[-] Disabling services
        [+] Disabled OpenVPN Services
        [+] Disabled Neo4j
        [+] Disabled OpenSSH Service
[+] Cleaning up the Desktop
[+] Timestamps added to cmd prompt and PowerShell
[+] Fixed shift+space keybinding in PowerShell
[-] Pinning items to Taskbar
        Pinning C:\Windows\explorer.exe to taskbar
        Pinning C:\Windows\system32\cmd.exe to taskbar
        Pinning C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe to taskbar
[+] Renaming host to 'commando'
        [-] Change will take effect after a restart
[+] Changing Desktop Background
        [+] Alternative backgrounds copied to C:\Users\Peppe\Pictures
        [+] Commando logos copied to C:\Users\Peppe\Pictures
[+] Copying README.txt to Desktop

OPERAZIONE RIUSCITA: valore specificato salvato.
Refreshing environment variables from the registry for powershell.exe. Please wait...
Finished
[+] Executing C:\ProgramData\chocolatey\lib\commandovm.win10.config.fireeye\tools\UNCPathSoftening.ahk
Chocolatey timed out waiting for the command to finish. The timeout
 specified (or the default value) was '2700' seconds. Perhaps try a
 higher `--execution-timeout`? See `choco -h` for details.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
The install of commandovm.win10.config.fireeye was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\commandovm.win10.config.fireeye\tools\chocolateyinstall.ps1'.
 See log for details.
This is try 1/3. Retrying after 300 milliseconds.
 Error converted to warning:
 (5) Accesso negato: [\\?\C:\ProgramData\chocolatey\lib-bad\commandovm.win10.config.fireeye]
This is try 2/3. Retrying after 400 milliseconds.
 Error converted to warning:
 (5) Accesso negato: [\\?\C:\ProgramData\chocolatey\lib-bad\commandovm.win10.config.fireeye]
Maximum tries of 3 reached. Throwing error.
This is try 1/3. Retrying after 300 milliseconds.
 Error converted to warning:
 (32) Impossibile accedere al file. Il file è utilizzato da un altro processo: [\\?\C:\ProgramData\chocolatey\lib\commandovm.win10.config.fireeye\tools]
This is try 2/3. Retrying after 400 milliseconds.
 Error converted to warning:
 (32) Impossibile accedere al file. Il file è utilizzato da un altro processo: [\\?\C:\ProgramData\chocolatey\lib\commandovm.win10.config.fireeye\tools]
Maximum tries of 3 reached. Throwing error.
Could not move bad package to failure directory It will show as installed.
 C:\ProgramData\chocolatey\lib\commandovm.win10.config.fireeye
 The error:
 (32) Impossibile accedere al file. Il file è utilizzato da un altro processo: [\\?\C:\ProgramData\chocolatey\lib\commandovm.win10.config.fireeye\tools]

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - commandovm.win10.config.fireeye (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\commandovm.win10.config.fireeye\tools\chocolateyinstall.ps1'.
 See log for details.

**To Reproduce**
Follow standard installation, after first fail, reboot the machine and execute:  **cinst -y commandovm.win10.config.fireeye -f** as administrator

**Version**
 Windows 10 2004 fully update.

**Comment by day1player** [comment]
@TeRompoErQ Thank you for the issue. So that I can try to recreate the issue, did this package fail before you rebooted? Did you execute this command from cmd.exe?

**Comment by TeRompoErQ** [comment]
Hi @day1player  Thank you for support.
Yes the package fail before reboot, and i had try to reboot the machine and force again installation of this packet, with same result...
and Yes, i had execute this command both from cmd.exe with administrative priviledge and with PS, with the same result.

**Comment by day1player** [comment]
@TeRompoErQ It looks like something caused the autohotkey scripts to fail. Can you see if `AutoHotKey` is in your path? You should be able to execute that command from cmd.exe. If so, you should also be able to manually finish the configuration which is those two AutoHotKey scripts, and enabling PowerShell logging.. If AutoHotKey is present, you can type these two commands:
```
AutoHotKey C:\ProgramData\chocolatey\lib\commandovm.win10.config.fireeye\tools\UNCPathSoftening.ahk
AutoHotKey C:\ProgramData\chocolatey\lib\commandovm.win10.config.fireeye\tools\EnableWinRM.ahk
```
If AutoHotKey is not present, you should be able to install it with `cinst -y autohotkey` and then run the above commands.

And then you can enable PowerShell logging by pasting this into an administrative powershell prompt:
```
if ($PSVersionTable -And $PSVersionTable.PSVersion.Major -ge 5) {
  Write-Host "[+] Enabling PowerShell Script Block Logging" -ForegroundColor Green
  $psLoggingPath = 'HKLM:\SOFTWARE\Wow6432Node\Policies\Microsoft\Windows\PowerShell'
  if (-Not (Test-Path $psLoggingPath)) {
    New-Item -Path $psLoggingPath -Force | Out-Null
  }
  $psLoggingPath = 'HKLM:\SOFTWARE\Wow6432Node\Policies\Microsoft\Windows\PowerShell\Transcription'
  if (-Not (Test-Path $psLoggingPath)) {
    New-Item -Path $psLoggingPath -Force | Out-Null
  }
  New-ItemProperty -Path $psLoggingPath -Name "EnableInvocationHeader" -Value 1 -PropertyType DWORD -Force | Out-Null
  New-ItemProperty -Path $psLoggingPath -Name "EnableTranscripting" -Value 1 -PropertyType DWORD -Force | Out-Null
  New-ItemProperty -Path $psLoggingPath -Name "OutputDirectory" -Value (Join-Path ${Env:UserProfile} "Desktop\PS_Transcripts") -PropertyType String -Force | Out-Null
  
  $psLoggingPath = 'HKLM:\SOFTWARE\Wow6432Node\Policies\Microsoft\Windows\PowerShell\ScriptBlockLogging'
  if (-Not (Test-Path $psLoggingPath)) {
    New-Item -Path $psLoggingPath -Force | Out-Null
  }
  New-ItemProperty -Path $psLoggingPath -Name "EnableScriptBlockLogging" -Value 1 -PropertyType DWORD -Force | Out-Null
  Write-Host "`t[i] Powershell transcripts will be saved to the desktop." -ForegroundColor Green
}
```

**Comment by TeRompoErQ** [comment]
Ok, thank you for help
