### ISSUE TITLE
BUG: WinDbg failing with 404 not found error

### ISSUE THREAD

**Issue by AstralPresence** [fireeye/commando-vm#159]
**Describe the bug and expected behavior**
The following packages fails to install with 404 Not found error- windbg.fireeye, windbg.flare 

**To Reproduce**
1. Setup VM of win10 build number18363 with latest updates
2. Run install script
3. above mentioned packages have failed to install, upon retyring install with cisnt, following errors are seen

**Screenshots**
Fireye
![image](https://user-images.githubusercontent.com/17882541/89702601-70c0e900-d960-11ea-9c04-995d71d2564e.png)
Flare
![image](https://user-images.githubusercontent.com/17882541/89702622-bc739280-d960-11ea-9e82-cfc82ef593d6.png)

**Version**
 - OS: win10 build number18363 with latest updates

**Comment by AstralPresence** [comment]
just realized that 18363 is not one of the supported builds.

**Comment by AstralPresence** [comment]
Will try with a compatible version.

**Comment by AstralPresence** [comment]
I'm trying with version 2004, build 19041 now.

**Comment by AstralPresence** [comment]
Ran into same issue with version 2004 too

**Comment by day1player** [comment]
@AstralPresence thanks for the issue, we will look into WinDBG but everything else sounds like it was good!

**Comment by AstralPresence** [comment]
thanks for the VM xD

**Comment by day1player** [comment]
Package is updated, please install with `cinst -y windbg.fireeye -f`

**Comment by djjoa** [comment]
Still having this issue: 

PS C:\Users\commando\Downloads\commando-vm-master\commando-vm-master> cinst -y windbg.fireeye -f
Chocolatey v0.10.15
Installing the following packages:
windbg.fireeye
By installing you accept licenses for the packages.
Progress: Downloading windbg.fireeye 10.0.10586.21... 100%

windbg.fireeye v10.0.10586.21 (forced)
windbg.fireeye package files install completed. Performing other installation steps.
Attempt to get headers for https://codemachine.com/downloads/win10rs1/X86%20Debuggers%20And%20Tools-x86_en-us.msi failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://codemachine.com/downloads/win10rs1/X86%20Debuggers%20And%20Tools-x86_en-us.msi'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
Downloading windbg.fireeye
  from 'https://codemachine.com/downloads/win10rs1/X86%20Debuggers%20And%20Tools-x86_en-us.msi'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://codemachine.com/downloads/win10rs1/X86%20Debuggers%20And%20Tools-x86_en-us.msi'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
The install of windbg.fireeye was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\windbg.fireeye\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - windbg.fireeye (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\windbg.fireeye\tools\chocolateyInstall.ps1'.
 See log for details.
PS C:\Users\commando\Downloads\commando-vm-master\commando-vm-master>

**Comment by day1player** [comment]
@djjoa thanks for the comment, this is a new issue again, we will need to update the old package. Follow along with issue #189
