### ISSUE TITLE
BUG: Kali issue: No update or install possible: Error/Failure with libc6 and `sleep` command

### ISSUE THREAD

**Issue by OneTastic** [fireeye/commando-vm#160]
**Describe the bug and expected behavior**
When trying to Update or Install anything it failes:
```
sleep: cannot read realtime clock: Invalid argument
dpkg: error processing package libc6:amd64 (--configure):
 installed libc6:amd64 package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 libc6:amd64
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**To Reproduce**
- I finished install kali.fireeye 
- entered kali with command kali
- #apt update
- #apt-get update && apt-get dist-upgrade
- Above command ends with error message in the first section
- When now trying to install something:

```
root@commando:~# apt install theharvester
Reading package lists... Done
Building dependency tree
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 bsdmainutils : Depends: calendar but it is not going to be installed
                Depends: ncal but it is not going to be installed
 libc-bin : Depends: libc6 (< 2.28) but 2.31-2 is to be installed
            Recommends: manpages but it is not going to be installed
 theharvester : Depends: python3 but it is not going to be installed
                Depends: python3-aiodns but it is not going to be installed
                Depends: python3-bs4 but it is not going to be installed
                Depends: python3-dnspython but it is not going to be installed
                Depends: python3-gevent but it is not going to be installed
                Depends: python3-grequests but it is not going to be installed
                Depends: python3-netaddr but it is not going to be installed
                Depends: python3-plotly but it is not going to be installed
                Depends: python3-requests but it is not going to be installed
                Depends: python3-shodan but it is not going to be installed
                Depends: python3-texttable but it is not going to be installed
                Depends: python3-yaml but it is not going to be installed
                Depends: python3:any
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

- #apt --fix-broken install  (ends also with error in the first section)

**Version**
![commandvm](https://user-images.githubusercontent.com/69734946/90333801-098ede80-dfc9-11ea-8ed4-e5819bb13075.jpg)

```
root@commando:~# cat /etc/os-release
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2020.3"
VERSION_ID="2020.3"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"

```

**Additional context**
```
root@commando:~# sleep 1
sleep: cannot read realtime clock: Invalid argument
root@commando:~# time

real    0m0.000s
user    0m0.000s
sys     0m0.000s
root@commando:~# date
Sun 16 Aug 2020 01:57:22 PM CEST

```

**Comment by day1player** [comment]
@OneTastic I have not seen this issue before, I would recommend removing this install of Kali WSL and reinstalling..

**Comment by aarongpower** [comment]
I had this issue and resolved it by changing Kali to run in WSL v2.

At a command prompt or powershell prompt:
`wsl --set-version kali-linux 2`

**Comment by day1player** [comment]
@tijldeneut are you not able to change to WSL2? Version 2004 should be no problem

**Comment by tijldeneut** [comment]
I have, but there are many reasons to stick with WSL1 for now. Main issue is that I use VMware Workstation and Hyper-V + Nested Virtualization in Workstation does not work (e.g. Proxmox or ESXi as a VM in Workstation on top of Hyper-V).

Regardless of WSL2, I assume Kali WSL1 should still work, no? 
(Kali 2020.3 released today, will try later if that fixes something)

**Comment by day1player** [comment]
I see.. Let me know how that goes, also, if you can please try updating and installing things _without_ doing the `apt dist-upgrade`... I'm curious to know if it will work using the older version of Kali... OffSec specifically created that version for WSL and I'm wondering if upgrading to the newest distribution breaks things.

**Comment by tijldeneut** [comment]
Just tried it and that fails too, the last command in the post above can also be:
> apt update && apt install -y vim
It fails at the step "Setting up libc6:amd64 (2.31-2)" (with again the sleep error).

My Ubuntu 20.04 WSLv1 works great so far...

**Comment by day1player** [comment]
Hm. Very interesting. I will have to try a new install to see if I can reproduce. I am using W10 2004 with Kali WSL v1 and I am not getting those errors.

I believe the above mentioned patch looks like the proper fix, but I dont think you are showing it in your updates because it is supposed to target 1903 and 1909. Did you by chance upgrade from one of those versions?

If not, perhaps there is a way to install that manually?

**Comment by Phillip-C** [comment]
Edit the following file
find the following line:
telinit u 2>/dev/null || true ; sleep 1
and comment out the sleep call like:
telinit u 2>/dev/null || true ; #sleep 1

It doesn't resolve the issue with sleep, but at least you can update/install.

**Comment by OneTastic** [comment]
Good to see I'm not the only with this issue.. I already expected the issue is because my more uncomming virtualisation done by QNAP Virtualisation Station on my NAS. While by default nested-virtualisation is not allowed, but can  be changed within a setting file. But after enabling the system it felt like the NAS system wasn't running that stable anymore, so i disabled again. As far as I understand WSL2 isn't an option in that case, right? I will check the windows patch and else at least the workaround of Phillip-C. While I'm already thinking about of grab out my old HP ML350 G6, which should be the better solution for a LAB than my QNAP ;-)

**Comment by OneTastic** [comment]
Installing the patch seems not to be possible. While Phillip-C's solution helped at least a bit..I was able to start update.. but it failes again on sleep, when there are services to stop/start for the installation.

**Comment by gehkah** [comment]
remove kali and start again here: 

https://docs.microsoft.com/de-de/windows/wsl/install-win10

than download and install the kernel update for windows:

https://docs.microsoft.com/de-de/windows/wsl/wsl2-kernel

install kali from the MS store again and do the wsl --set-version kali-linux 2 command

that was my way to fix this issue :)

**Comment by tijldeneut** [comment]
Yes, WSL2 is a fix, but not everyone wants or can use WSL2 (and the Hyper-V consequences).
The workaround from @Phillip-C works pretty well untill there is a proper MS Patch for Windows b2004:

> sed -i 's/sleep/#sleep/g' /var/lib/dpkg/info/libc6\:amd64.postinst

**Comment by Otimun** [comment]
Not sure if this will work for you guys but I followed the advise found here:

https://malware-guide.com/blog/ubuntu-20-04-lts-for-windows-10-is-available-for-download#:~:text=While%20running%2C%20if%20%E2%80%9Csleep%3A,it%20back%20after%20the%20upgrade.&text=After%20the%20upgrade%2C%20move%20%2Fbin,~%20to%20%2Fbin%2Fsleep.

basically I created a dummy sleep file:
cd bin
sudo mv sleep sleep.tmp
sudo touch sleep
sudo chmod 777 sleep
sudo apt --fix-broken install
sudo apt upgrade
sudo mv sleep.tmp sleep

After that it all seems fixed.

**Comment by Devastation2020** [comment]
Hi i had the same issue but with the libc6 that's what i did 

- sudo -i 
- sudo mv /bin/sleep /bin/sleep~ ; touch /bin/sleep ; chmod +x /bin/sleep
- sudo apt update
- sudo apt upgrade -y   " after the error message" 
- sudo apt --fix-broken 
- sudo apt upgrade -y

**Comment by cdead2** [comment]
its like what philip says
 Edit the following file: /var/lib/dpkg/info/libc6:amd64.postinst
find the following line (towards very bottom):
telinit u 2>/dev/null || true ; sleep 1
when you join into the file the line will be maybe after 40 line

and comment out the sleep call like:
telinit u 2>/dev/null || true ; #sleep 1

**Comment by Marc23h** [comment]
> Hi i had the same issue but with the libc6 that's what i did
> 
> * sudo -i
> * sudo mv /bin/sleep /bin/sleep~ ; touch /bin/sleep ; chmod +x /bin/sleep
> * sudo apt update
> * sudo apt upgrade -y   " after the error message"
> * sudo apt --fix-broken
> * sudo apt upgrade -y

that worked for me, thank you!

**Comment by bradgepfert** [comment]
Using Kali as a subsystem of windows is wonderful, no "Phooey-GUI". John The Ripper works great! I'm trying to run Tomcat/Apache for an smtp server. wml

Thank you for your hard work and intelligence with that solution you gave us! <3

~~~~~Goose

**Comment by YmClash** [comment]
i have  the  same  issue
