### ISSUE TITLE
packages.csv Package Discrepancy 

### ISSUE THREAD

**Issue by syth3** [fireeye/commando-vm#168]
### Bug Description
In the packages.csv file, there is a discrepancy between the BloodHound-Custom-Queries.fireeye package and Custom-BloodHound-Queries.fireeye package. Under the **Package Name** column, the package is listed as *BloodHound-Custom-Queries.fireeye*. But, under the **How to install** column, the command is `cinst -y Custom-BloodHound-Queries.fireeye`. When I try to run that command, I receive an error message of *The package was not found with the source(s) listed*. If I'm understanding this properly, the command should be changed to `cinst -y BloodHound-Custom-Queries.fireeye`

### How To Reproduce
1. View data under columns **Package Name** and **How to install** in row 21 of packages.csv
2. Run the command found in row 21, under the **How to install** column

### Screenshots
**Custom-BloodHound-Queries.fireeye**
![Custom-BloodHound-Queries.fireeye Chocolatey Install](https://user-images.githubusercontent.com/63307106/94026813-249efc00-fd88-11ea-8ebc-a2a84a6983c2.png)

### Version
 - OS: Windows 10 Version 2004 Build 19041.508

### Extra Information
This issue also is found with the Gadgettojscript.fireeye package in row 73 of packages.csv

**Comment by day1player** [comment]
updated, thank you!
