### ISSUE TITLE
windbg.pykd.flare Chocolatey Installation Error

### ISSUE THREAD

**Issue by syth3** [fireeye/commando-vm#169]
### Bug Description
When attempting to install the windbg.pykd.flare package from Chocolatey, I receive this error: *ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not find a part of the path.* 
Here is my Chocolatey log relating to this install: [windbg.pykd.flare Install Log.txt](https://github.com/fireeye/commando-vm/files/5276549/windbg.pykd.flare.Install.Log.txt)

### Steps To Reproduce
1. Run the following command in an elevated PowerShell prompt: 
`cinst -y windbg.pykd.flare`

### Screenshots
![windbg pykd flare Install Screenshot](https://user-images.githubusercontent.com/63307106/94155071-8a54bc00-fe4c-11ea-838c-e4c5e747f106.png)

### Version
 - OS: Windows 10 Version 2004 Build 19041.508
- $Env:FEVM_PROFILE: Commando_Default

**Comment by day1player** [comment]
@syth3 thank you for the issues.. Can you tell me what profile/version you installed? 
You should be able to see in PowerShell with `$Env:FEVM_PROFILE`

**Comment by syth3** [comment]
@day1player this is what I see
![Profile-Version](https://user-images.githubusercontent.com/63307106/94213261-5a390780-fea4-11ea-9e26-4e828bd21134.png)

**Comment by day1player** [comment]
@syth3 thank you very much, this will help us identify if there are problems with dependencies.

We are taking a look at all of the issues you have created, it will take some time for us to address everything but we really appreciate each issue.

For what its worth, FlareVM (and its toolsets) is meant for Windows 7, so not everything has been fully tested on Windows 10. We are in the process of creating and supporting Windows 10 for FlareVM soon but until then we may see some instability in the tooling. The issues you have created will only help in our support for Win10 soon!

**Comment by syth3** [comment]
@day1player Thank you for the support! I'm glad that the issues I created can help this project and were not viewed as spamming.

**Comment by day1player** [comment]
fixed with june update #262
