### ISSUE TITLE
windbg.ollydumpex.flare Install Error

### ISSUE THREAD

**Issue by syth3** [fireeye/commando-vm#170]
### Bug Description
When attempting to install the windbg.ollydumpex.flare package from Chocolatey, I receive this error: *ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not find a part of the path.*
Here is my Chocolatey log relating to this install: 
[windbg.ollydumpex.flare Install Log.txt](https://github.com/fireeye/commando-vm/files/5276726/windbg.ollydumpex.flare.Install.Log.txt)

### Steps To Reproduce**
1. Run the following command in an elevated PowerShell prompt:
`cinst -y windbg.ollydumpex.flare`

### Screenshots
![windbg ollydumpex flare Install Screenshot txt](https://user-images.githubusercontent.com/63307106/94157857-aefe6300-fe4f-11ea-9896-ca14687dfb83.png)

### Version
 - OS: Windows 10 Version 2004 Build 19041.508
- $Env:FEVM_PROFILE: Commando_Default

**Comment by htnhan** [comment]
Hi @syth3 ,

Can you provide the logs file under `C:\ProgramData\chocolatey\logs`? As you can see in my screenshot, I install `windbg.ollydumpex.flare` version `1.7.2.3` successfully without any issues

![image](https://user-images.githubusercontent.com/8796047/94506522-30008600-01d3-11eb-88e0-24b18fe859a3.png)

**Comment by syth3** [comment]
Sure thing. Attached below are all logs underneath `C:\ProgramData\chocolatey\logs`

[chocolatey.log](https://github.com/fireeye/commando-vm/files/5312275/chocolatey.log)
[chocolatey.1.log](https://github.com/fireeye/commando-vm/files/5312278/chocolatey.1.log)
[choco.summary.log](https://github.com/fireeye/commando-vm/files/5312279/choco.summary.log)

**Comment by htnhan** [comment]
@syth3 We just upgrade `windbg.ollydumpex.flare` package. Depending on the version of windbg, the path for the x86 and x64 versions of windbg may change, which cause ollydumpex installation to fail. It should be fixed to support the latest version of windbg now. Please give it another shot.

**Comment by day1player** [comment]
fixed with june update #262
