### ISSUE TITLE
openssl.flare Install Error

### ISSUE THREAD

**Issue by syth3** [fireeye/commando-vm#171]
### Bug Description
When attempting to install the openssl.flare package from Chocolatey, I receive this error: *ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://slproweb.com/download/Win64OpenSSL-1_1_1g.exe'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found*
Here is my Chocolatey log relating to this install: 
[openssl.flare Install Log.txt](https://github.com/fireeye/commando-vm/files/5276785/openssl.flare.Install.Log.txt)

### Steps To Reproduce
1. Run the following command in an elevated PowerShell prompt: 
`cinst -y openssl.flare`

### Screenshots
![openssl flare Install Screenshottxt](https://user-images.githubusercontent.com/63307106/94158773-c853df00-fe50-11ea-8659-0eb55e9e7343.png)

### Version
 - OS: Windows 10 Version 2004 Build 19041.508
- $Env:FEVM_PROFILE: Commando_Default

**Comment by htnhan** [comment]
Thank you for the bug report @syth3! we've updated the `OpenSSL.flare`  package to `v1.1.0.20200928` to fix the URL.

**Comment by syth3** [comment]
It works great now. Thanks for the update!
