### ISSUE TITLE
fakenet-ng.python.fireeye Install Error

### ISSUE THREAD

**Issue by syth3** [fireeye/commando-vm#172]
### Bug Description
When attempting to install the fakenet-ng.python.fireeye package from Chocolatey, I receive this error: *ERROR: The term 'New-InstallLog' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again*
Here is my Chocolatey log relating to this install: 
[fakenet-ng.python.fireeye Install Log.txt](https://github.com/fireeye/commando-vm/files/5276853/fakenet-ng.python.fireeye.Install.Log.txt)

### Steps To Reproduce
1. Run the following command in an elevated PowerShell prompt: 
`cinst -y fakenet-ng.python.fireeye`

### Screenshots
![fakenet-ng python fireeye Install Screenshot](https://user-images.githubusercontent.com/63307106/94159861-0b628200-fe52-11ea-90d4-6a02bd08af3a.png)

### Version
 - OS: Windows 10 Version 2004 Build 19041.508
- $Env:FEVM_PROFILE: Commando_Default

**Comment by htnhan** [comment]
@syth3 We just pushed a fix for this issue. Please update `common.fireeye` package and try to install again by executing the following commands:
```
cup -y common.fireeye
cinst -y fakenet-ng.python.fireeye
```

**Comment by syth3** [comment]
Thanks for the update! It now installs properly. It does spit out this warning, however. I'm not sure if this is an issue or not.

![fakenet-ng.python.fireeye warning](https://user-images.githubusercontent.com/63307106/94816670-23924e00-03ca-11eb-867f-e10247fe9606.png)
