### ISSUE TITLE
lonelypotato.fireeye Install Error

### ISSUE THREAD

**Issue by syth3** [fireeye/commando-vm#174]
### Bug Description
When attempting to install the lonelypotato.fireeye package from Chocolatey, I receive this error: *ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://github.com/decoder-it/lonelypotato/archive/1845a19662856abd1e3f84f3ebdb9c029e93ab8d.zip'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."*
Here is my Chocolatey log relating to this install: 
[lonelypotato.fireeye Install Log.txt](https://github.com/fireeye/commando-vm/files/5279886/lonelypotato.fireeye.Install.Log.txt)

### Steps To Reproduce
1. Run the following command in an elevated PowerShell prompt: 
`cinst -y lonelypotato.fireeye`

### Screenshots
![lonelypotato fireeye Install Screenshot](https://user-images.githubusercontent.com/63307106/94213788-c5370e00-fea5-11ea-892b-ccb8d9466403.png)

### Version
 - OS: Windows 10 Version 2004 Build 19041.508
- $Env:FEVM_PROFILE: Commando_Default

**Comment by day1player** [comment]
@syth3 this looks like the file may be being blocked by a proxy of sorts. Can you confirm you are not installing this behind a firewall/proxy that may be interfering?

**Comment by syth3** [comment]
@day1player I am pretty certain I am not installing it behind a firewall/proxy. My current setup is a Windows 10 computer running Commando VM inside of VMWare workstation. The Commando VM is configured to use NAT networking. My Windows 10 host computer is connected directly to my ISP-given router running their default firewall. Because of this, the only firewall/proxy that seem to be of interest are any Windows 10 firewalls running on either the Commando VM or my host machine, or the default firewall on my router. Additionally, I have tested installing this package in a different VM on a different network entirely and face the same issues. When I visit the [url listed in the error message](https://github.com/decoder-it/lonelypotato/archive/1845a19662856abd1e3f84f3ebdb9c029e93ab8d.zip) in my web browser, I also receive a HTTP 404.

**Comment by day1player** [comment]
Right on it looks like that was definitely removed then. We will have to update the package. I will let you know when it is done, thank you!

**Comment by syth3** [comment]
Sure thing. Thanks for the help!

**Comment by day1player** [comment]
fixed with june update #262
