### ISSUE TITLE
libraries.python3.fireeye stringsifter Install Error

### ISSUE THREAD

**Issue by syth3** [fireeye/commando-vm#175]
### Bug Description
When attempting to install the stringsifter package within the libraries.python3.fireeye package from Chocolatey, I receive this error: *[libraries.python3.fireeye] chocolateyinstall.ps1 [+] ERROR : Failed to install stringsifter*
Here is my Chocolatey log relating to this install: 
[libraries.python3.fireeye Install Log.txt](https://github.com/fireeye/commando-vm/files/5279949/libraries.python3.fireeye.Install.Log.txt)
And here is the module_output.txt file for more information: 
[module_output.txt](https://github.com/fireeye/commando-vm/files/5279951/module_output.txt)

### Steps To Reproduce
1. Run the following command in an elevated PowerShell prompt: 
`cinst -y libraries.python3.fireeye`

### Screenshots
![libraries python3 fireeye Install Screenshot Part 1](https://user-images.githubusercontent.com/63307106/94215066-66739380-fea9-11ea-890a-8ec46efea3d4.png)
![libraries python3 fireeye Install Screenshot Part 2](https://user-images.githubusercontent.com/63307106/94215069-68d5ed80-fea9-11ea-802f-0cb2e79db8d6.png)

### Version
 - OS: Windows 10 Version 2004 Build 19041.508
- $Env:FEVM_PROFILE: Commando_Default

**Comment by day1player** [comment]
fixed with june update #262
