### ISSUE TITLE
map.flare Install Error - Checksum Issue

### ISSUE THREAD

**Issue by syth3** [fireeye/commando-vm#176]
### Bug Description
When attempting to install the lonelypotato.fireeye package from Chocolatey, I receive this error: *ERROR: Checksum for 'C:\Users\Jake\AppData\Local\Temp\map_setup.exe' did not meet 'd8333d8757e23d32545225bc30271656a2886f77607f69d32c05900769dba144' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.*
Here is my Chocolatey log relating to this install: 
[map.flare Install Log.txt](https://github.com/fireeye/commando-vm/files/5280003/map.flare.Install.Log.txt)

### Steps To Reproduce
1. Run the following command in an elevated PowerShell prompt: 
`cinst -y map.flare`

### Screenshots
![map flare Install Screenshot](https://user-images.githubusercontent.com/63307106/94216151-aab46300-feac-11ea-9dff-6149eb396936.png)

### Version
 - OS: Windows 10 Version 2004 Build 19041.508
- $Env:FEVM_PROFILE: Commando_Default

**Comment by htnhan** [comment]
@syth3 We have updated `MAP.flare` to fix the checksum mismatch. Please give it another shot and let us know if you still have the issue.

**Comment by syth3** [comment]
It works great now. Thanks for the update!
