### ISSUE TITLE
Burpsuite doesn't start after install (JNI Error)

### ISSUE THREAD

**Issue by dkorzhevin** [fireeye/commando-vm#177]
Hello,

Right after successful install, Burpsuite unable to start:

Screenshot1:

<img width="979" alt="image" src="https://user-images.githubusercontent.com/762235/95617687-7deb7880-0a74-11eb-9043-ae0dfbee2075.png">

Screenshot2:

<img width="958" alt="image" src="https://user-images.githubusercontent.com/762235/95617720-8b086780-0a74-11eb-9dd3-e6ed0797d9d6.png">

**Comment by samjou** [comment]
I had the same problem and installing a different jdk version and launching burp with it solved it.
1. Install openjdk with chocolatey **_choco install openjdk11_**
![image](https://user-images.githubusercontent.com/43219837/98458335-73003280-215d-11eb-9591-129cc55713cf.png)

2. Chenge the default target n the burp shortcut options from **_C:\Program Files\Java\jdk1.8.0_211\bin\javaw.exe_** to **_C:\Program Files\OpenJDK\openjdk-11.0.9_11\bin\javaw.exe_**
![image](https://user-images.githubusercontent.com/43219837/98458270-df2e6680-215c-11eb-8a58-21d5c83a519f.png)

3. Burps launchs without any problems
![image](https://user-images.githubusercontent.com/43219837/98458283-fb320800-215c-11eb-82a7-090bc2597082.png)

**Comment by nguyenphuc241** [comment]
Hi, BurpSuite v2020 above doesn't support other Java version, it's only compatible with Java 9+, version 2016. I got stuck and this solution helped me a lot. Hope you too! This is Java 9+ download link: https://drive.google.com/uc?export=download&id=1XCYEzAJWY2QS0mfGZg0Oj-5MId2LFTot

**Comment by limbernie** [comment]
Open a command prompt as Administrator.

`ftype jarfile` <= This should show you the current JAR file handler, likely `javaw.exe` from JDK 8.

Change the JAR file handler to JDK 9 or later. The example below uses JDK 13.

`ftype jarfile="C:\Program Files\OpenJDK\jdk-13.0.2\bin\javaw.exe" -jar "%1" %*`
