### ISSUE TITLE
PATH environment variable causes errors with expected commands

### ISSUE THREAD

**Issue by day1player** [fireeye/commando-vm#18]
Example: 
 - `ping` refers to `C:\Python27\Scripts\ping.py`
 - `reg` refers to impacket's `reg` script

**Comment by htnhan** [comment]
@day1player  Impacket installs a bunch of scripts into the Python Script directory, which is higher in the search list within %PATH%. We can specify `ping.exe`, or `reg.exe` to access the system binaries.

**Comment by day1player** [comment]
Opened issue #1255 with Chocolatey 
https://github.com/chocolatey/chocolatey-coreteampackages/issues/1255

**Comment by day1player** [comment]
Users may enter the following command from an administrative PowerShell prompt to fix:
`set /M PATH "C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files\Microsoft VS Code\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Boxstarter;C:\Python37\Scripts\;C:\Python37\;C:\Python27\;C:\Python27\Scripts;C:\Go\bin;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Java\jdk1.8.0_201\bin;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\metasploit-framework\bin\;C:\Program Files\dotnet\;$Home\AppData\Local\Microsoft\WindowsApps;$Home\go\bin;C:\Program Files (x86)\Nmap"`

This will provide a temporary fix until we can address the issue

**Comment by day1player** [comment]
Issue is not resolvable with Chocolatey, will update config packages in next release of Commando to set the PATH variable after installation

**Comment by day1player** [comment]
fixed with version 1.1
