### ISSUE TITLE
Mimikatz: Readline error

### ISSUE THREAD

**Issue by cutaway** [fireeye/commando-vm#182]
**Describe the bug and expected behavior**
Attempted to run mimikatz from command line.

```
PS C:\Users\admin > mimikatz
Traceback (most recent call last):
  "File C:\Python27\Scripts\mimikatz.py", line 40, in <module>
    import readline
ImportError: No module named readline
```

**To Reproduce**
1. Open terminal
2. Run 'mimikatz'

**Version**
 - OS: Windows 10 Pro 1909
 - CommandVM: Updated Oct 29, 2020

**Additional context**
Review of the mimikatz.py code shows that the mimikatz.py script tests for PyReadline first and then tries to use the flagged readline import.

The following update worked for me. From terminal:

```
PS C:\Users\admin > cd C:\Python27
PS C:\Python27 > ./python -m pip install pyreadline
[snip installation output]

PS C:\Python27 > mimikatz
[snip normal mimikatz usage output]
```

**Comment by day1player** [comment]
This seems to be operating normally, please let me know if it is not working as expected.
