### ISSUE TITLE
What is the problem？

### ISSUE THREAD

**Issue by ZZtac** [fireeye/commando-vm#183]
Get-ItemProperty : 路径 HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Defender\Features 处不存在属性 TamperProtection。
所在位置 C:\freeeye\install.ps1:285 字符: 7
+   if (Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows Defend ...
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (TamperProtection:String) [Get-ItemProperty]，PSArgumentException
    + FullyQualifiedErrorId : System.Management.Automation.PSArgumentException,Microsoft.PowerShell.Commands.GetItemPr
   opertyCommand

**Comment by day1player** [comment]
@ZZtac what version of windows are you trying to install on?

**Comment by ZZtac** [comment]
win10 1809

**Comment by day1player** [comment]
@ZZtac I believe this registry key was put in place in 1903.. You can safely ignore this error
