### ISSUE TITLE
Install fails during boxstarter istallation

### ISSUE THREAD

**Issue by sfuthings** [fireeye/commando-vm#187]
I'm installing in Windows 10 2004, and installation always fails during boxtstarter installation.

Using install script, errors include:
The term 'Install-BoxstarterPackage' is not recognized as a name of a cmdlet, function, script file, or executable program. 
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

When manually install int boxstarter using cinst -y boxstarter:
[NuGet] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 104.20.74.28:80
boxstarter not installed. An error occured during installation:
 Unable to resolve dependency 'Boxstarter.Common (= 2.13.0)'.

I have tried accessing the IP address and its a Cloudflare IP address with an error 1003, Direct IP access not allowed.

**Comment by day1player** [comment]
@sfuthings are you sitting behind a firewall of some sort? Recommend installing from a home internet connection.

**Comment by sfuthings** [comment]
@day1player I'm not behind a firewall, but turns out the issue was caused by cloudflare blocking my IP address. Used a VPN and the installation seems fine and is currently progressing past the boxstarter install as of now. Fingers crossed.
Thanks!
