### ISSUE TITLE
dnspy windbg install error

### ISSUE THREAD

**Issue by sfuthings** [fireeye/commando-vm#189]
I have these issues that was reported by some. Windbg and dnspy failed during installation.

I tried manually installing these packages following some recommendations here, modifying the dead URLs and it worked fine.

But how do I continue the commando vm installation? I resumed by **_.\install.ps1 -nochecks 1 mypass_** but in the end it just tried to reinstall the above two packages using the broken URLs. I can't seem to get past this issue for the proper installation (background changed and readme.txt on desktop).

**Comment by sfuthings** [comment]
it seems the issue is from boxstarter but installation of packages seems fine? What appears to be restarting, the machine does not restart. Rebooting manually will autorun the script again with the same error.
-------------------------------------------------------------
This is the logs from boxstarter: 


Chocolatey installed 1/1 packages. 0 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Packages requiring reboot:
 - commandovm.win10.installer.fireeye (exit code 3010)

The recent package changes indicate a reboot is necessary. 
 Please reboot at your earliest convenience.
Sending message 'PostRunMessage' out if there are subscribers...
[2021-02-01T08:46:44.4974874+08:00:::PID 3924] Boxstarter: restoring current directory location to C:\Windows\system32
[2021-02-01T08:46:44.4974874+08:00:::PID 3924] Boxstarter: found C:\Users\xxxx\AppData\Local\Boxstarter\Boxstarter.3924.restart we are restarting
[2021-02-01T08:46:44.4974874+08:00:::PID 3924] Boxstarter: found C:\Users\xxxx\AppData\Local\Boxstarter\Boxstarter.3924.restart we are restarting
[2021-02-01T08:46:44.5131656+08:00:::PID 3924] Boxstarter: Exit Code: 3010
[2021-02-01T08:46:44.6069584+08:00:::PID 3924] Boxstarter: There was an error calling Chocolatey
[2021-02-01T08:46:44.6069584+08:00:::PID 3924] Boxstarter: Error from Chocolatey: 

Message        : Chocolatey reported an unsuccessful exit code of 3010. See 
                 C:\Users\xxxx\AppData\Local\Boxstarter\boxstarter.log for details.
Data           : {}
InnerException : 
TargetSite     : 
StackTrace     : 
HelpLink       : 
Source         : 
HResult        : -2146233087




[2021-02-01T08:46:44.6069584+08:00:::PID 3924] Boxstarter: Error from Chocolatey: 

Message        : Chocolatey reported an unsuccessful exit code of 3010. See 
                 C:\Users\xxxx\AppData\Local\Boxstarter\boxstarter.log for details.
Data           : {}
InnerException : 
TargetSite     : 
StackTrace     : 
HelpLink       : 
Source         : 
HResult        : -2146233087




[2021-02-01T08:46:44.6225147+08:00:::PID 3924] Boxstarter: Chocolatey install returned a rebootable exit code (3010)
[2021-02-01T08:46:44.6225147+08:00:::PID 3924] ++ Boxstarter finished Calling Chocolatey to install commandovm.win10.installer.fireeye. This may take several minutes to complete... 00:00:25.1470480
[2021-02-01T08:46:44.6225147+08:00:::PID 3924] ++ Boxstarter finished Calling Chocolatey to install commandovm.win10.installer.fireeye. This may take several minutes to complete... 00:00:25.1470480
[2021-02-01T08:46:44.6388262+08:00:::PID 3924] Boxstarter: Removing C:\ProgramData\chocolatey\lib\commandovm.win10.installer.fireeye in progress
[2021-02-01T08:46:44.6388262+08:00:::PID 3924] Boxstarter: writing restart file
[2021-02-01T08:46:44.6388262+08:00:::PID 3924] Boxstarter: writing restart file
[2021-02-01T08:46:44.8571996+08:00:::PID 3924] Boxstarter: Restore Automatic Updates from Windows Update
[2021-02-01T08:46:44.8882345+08:00:::PID 3924] Boxstarter: Enabling UAC
[2021-02-01T08:46:44.9041559+08:00:::PID 3924] Boxstarter: UAC Enabled. Disabling...
[2021-02-01T08:46:44.9041559+08:00:::PID 3924] Boxstarter: Disabling UAC
[2021-02-01T08:46:44.9201147+08:00:::PID 3924] + Boxstarter finished Installation session. 00:00:26.4562950
[2021-02-01T08:46:44.9201147+08:00:::PID 3924] Boxstarter: Restart Required. Restarting now...

**Comment by djjoa** [comment]
I'm running into a similar problem as OP: 
( this was run using the `.\install.ps1 -password "password"` as described as solution to  issue 122)
--- 

dnspy.flare v6.1.7.0
dnspy.flare package files upgrade completed. Performing other installation steps.
Attempt to get headers for https://github.com/0xd4d/dnSpy/releases/download/v6.1.7/dnSpy-net472.zip failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://github.com/0xd4d/dnSpy/releases/download/v6.1.7/dnSpy-net472.zip'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
Attempt to get headers for https://github.com/0xd4d/dnSpy/releases/download/v6.1.7/dnSpy-net472.zip failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://github.com/0xd4d/dnSpy/releases/download/v6.1.7/dnSpy-net472.zip'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
Downloading dnspy
  from 'https://github.com/0xd4d/dnSpy/releases/download/v6.1.7/dnSpy-net472.zip'
Downloading dnspy
  from 'https://github.com/0xd4d/dnSpy/releases/download/v6.1.7/dnSpy-net472.zip'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://github.com/0xd4d/dnSpy/releases/download/v6.1.7/dnSpy-net472.zip'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
The upgrade of dnspy.flare was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\dnspy.flare\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - dnspy.flare (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\dnspy.flare\tools\chocolateyInstall.ps1'.
 See log for details.
Chocolatey reported an unsuccessful exit code of 404. See C:\Users\commando\AppData\Local\Boxstarter\boxstarter.log for details.
Boxstarter: Error from Chocolatey:

Message        : Chocolatey reported an unsuccessful exit code of 404. See C:\Users\commando\AppData\Local\Boxstarter\boxstarter.log for detai
                 ls.
Data           : {}
InnerException :
TargetSite     :
StackTrace     :
HelpLink       :
Source         :
HResult        : -2146233087




Boxstarter: Error from Chocolatey:

Message        : Chocolatey reported an unsuccessful exit code of 404. See C:\Users\commando\AppData\Local\Boxstarter\boxstarter.log for detai
                 ls.
Data           : {}
InnerException :
TargetSite     :
StackTrace     :
HelpLink       :
Source         :
HResult        : -2146233087




+ Boxstarter finished Calling Chocolatey to install dnspy.flare. This may take several minutes to complete... 00:00:08.2047708
+ Boxstarter finished Calling Chocolatey to install dnspy.flare. This may take several minutes to complete... 00:00:08.2047708


ExitCode: 404
ExitCode: 404
2021/02/06 18:44:32 [dnspy.flare] chocolateyinstall.ps1 [+] ERROR : Failed to install dnspy.flare
2021/02/06 18:44:32 [dnspy.flare] chocolateyinstall.ps1 [+] ERROR : Failed to install dnspy.flare
2021/02/06 18:44:32 [dnspy.flare] chocolateyinstall.ps1 [+] INFO : Attempting install of windbg.fireeye
2021/02/06 18:44:32 [dnspy.flare] chocolateyinstall.ps1 [+] INFO : Attempting install of windbg.fireeye
WARNING: [!] Installing using host choco.exe! Errors are ignored. Please check to confirm windbg.fireeye is installed properly
WARNING: [!] Executing: iex choco upgrade windbg.fireeye --cacheLocation C:\Users\commando\AppData\Local\ChocoCache -y
+ Boxstarter starting Calling Chocolatey to install windbg.fireeye. This may take several minutes to complete...
+ Boxstarter starting Calling Chocolatey to install windbg.fireeye. This may take several minutes to complete...
Upgrading the following packages:
windbg.fireeye
By upgrading you accept licenses for the packages.
windbg.fireeye is not installed. Installing...
[NuGet] Attempting to resolve dependency 'common.fireeye '.
Progress: Downloading windbg.fireeye 10.0.10586.21... 100%
Progress: Downloading windbg.fireeye 10.0.10586.21... 100%
Progress: Downloading windbg.fireeye 10.0.10586.21... 100%
Progress: Downloading windbg.fireeye 10.0.10586.21... 100%
Progress: Downloading windbg.fireeye 10.0.10586.21... 100%
[NuGet] Installing 'windbg.fireeye 10.0.10586.21'.
[NuGet] Successfully installed 'windbg.fireeye 10.0.10586.21'.

windbg.fireeye v10.0.10586.21
windbg.fireeye package files upgrade completed. Performing other installation steps.
Attempt to get headers for https://codemachine.com/downloads/win10rs1/X86%20Debuggers%20And%20Tools-x86_en-us.msi failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://codemachine.com/downloads/win10rs1/X86%20Debuggers%20And%20Tools-x86_en-us.msi'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
Attempt to get headers for https://codemachine.com/downloads/win10rs1/X86%20Debuggers%20And%20Tools-x86_en-us.msi failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://codemachine.com/downloads/win10rs1/X86%20Debuggers%20And%20Tools-x86_en-us.msi'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
Downloading windbg.fireeye
  from 'https://codemachine.com/downloads/win10rs1/X86%20Debuggers%20And%20Tools-x86_en-us.msi'
Downloading windbg.fireeye
  from 'https://codemachine.com/downloads/win10rs1/X86%20Debuggers%20And%20Tools-x86_en-us.msi'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://codemachine.com/downloads/win10rs1/X86%20Debuggers%20And%20Tools-x86_en-us.msi'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
The upgrade of windbg.fireeye was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\windbg.fireeye\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - windbg.fireeye (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\windbg.fireeye\tools\chocolateyInstall.ps1'.
 See log for details.
Chocolatey reported an unsuccessful exit code of 404. See C:\Users\commando\AppData\Local\Boxstarter\boxstarter.log for details.
Boxstarter: Error from Chocolatey:

Message        : Chocolatey reported an unsuccessful exit code of 404. See C:\Users\commando\AppData\Local\Boxstarter\boxstarter.log for detai
                 ls.
Data           : {}
InnerException :
TargetSite     :
StackTrace     :
HelpLink       :
Source         :
HResult        : -2146233087




Boxstarter: Error from Chocolatey:

Message        : Chocolatey reported an unsuccessful exit code of 404. See C:\Users\commando\AppData\Local\Boxstarter\boxstarter.log for detai
                 ls.
Data           : {}
InnerException :
TargetSite     :
StackTrace     :
HelpLink       :
Source         :
HResult        : -2146233087




+ Boxstarter finished Calling Chocolatey to install windbg.fireeye. This may take several minutes to complete... 00:00:06.8246048
+ Boxstarter finished Calling Chocolatey to install windbg.fireeye. This may take several minutes to complete... 00:00:06.8246048


ExitCode: 404

**Comment by day1player** [comment]
It looks like some of the other resources with this package are no longer available, will update.

**Comment by kiraitachi** [comment]
Yes I can agree this issue still happens. Any workaround proposed meantime? Thanks.

**Comment by day1player** [comment]
@kiraitachi I would recommend checking out the instructions/releases on the [dnspy github page](https://github.com/dnSpy/dnSpy)

**Comment by kiraitachi** [comment]
@day1player  sorry Im not very sure this is related to dns spy. I will open a different case.

**Comment by day1player** [comment]
fixed with june update #262
