### ISSUE TITLE
Issue updating visualstudio-installer

### ISSUE THREAD

**Issue by pamurp7789** [fireeye/commando-vm#19]
Receiving the following error when running "cup all" post installation.

...
vcredist2015 v14.0.24215.20170201 is the latest version available based on your source(s).
vcredist2017 v14.16.27027.1 is the latest version available based on your source(s).

visualstudio-installer was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""; Source(s): "https://www.myget.org/F/fireeye/api/v2;https://chocolatey.org/api/v2/"

visualstudio2017-workload-netcoretools v1.2.2 is the latest version available based on your source(s).
visualstudio2017community v15.9.10.0 is the latest version available based on your source(s).
...

I reran the install.ps1 script to be certain everything was installed and I received all green results (no red).

**Comment by day1player** [comment]
closing stale issue
