### ISSUE TITLE
Installation instructions regarding Windows 10 20H2

### ISSUE THREAD

**Issue by johanssontobbe** [fireeye/commando-vm#190]
The installation instruction currently say "Ensure VM is updated completely. You may have to check for updates, reboot, and check again until no more remain."

Following these instructions, I got Windows 10 20H2 installed.
Windows 10 20H2 is not supported by the CommandoVM installer.

Perhaps clarify this fact in the installation instructions.

**Comment by johanssontobbe** [comment]
In case this helps anyone, here are instructions on how to remove the 20H2 update:
https://www.bleepingcomputer.com/news/microsoft/how-to-uninstall-and-downgrade-windows-10-20h2-to-previous-versions/

**Comment by day1player** [comment]
@johanssontobbe thanks for the issue and suggestion. I will look to add support for the newer Windows OS in the near future.

**Comment by day1player** [comment]
fixed with june update #262
