### ISSUE TITLE
Installation of commandovm.win10.installer.fireeye fails.

### ISSUE THREAD

**Issue by johanssontobbe** [fireeye/commando-vm#191]
I get this message:
```
Failures
 - commandovm.win10.installer.fireeye (exited 1) - commandovm.win10.installer.fireeye not installed. An error occurred during installation:
 The remote name could not be resolved: 'az774065.vo.msecnd.net'
```

**Comment by day1player** [comment]
This message is pretty interesting: 
```
The remote name could not be resolved: 'az774065.vo.msecnd.net'
```
I am not sure exactly what that is. If you are on a home network, I would recommend trying to install on a VPN to see if the DNS resolution is fixed.

**Comment by johanssontobbe** [comment]
I can reach the site (az774065.vo.msecnd.net), but it returns this message:
`<Error>
<Code>InvalidQueryParameterValue</Code>
<Message>
Value for one of the query parameters specified in the request URI is invalid. RequestId:32f5e45c-501e-0081-62ac-fbb750000000 Time:2021-02-05T10:47:30.7507449Z
</Message>
<QueryParameterName>comp</QueryParameterName>
<QueryParameterValue/>
<Reason/>
</Error>`

**Comment by ryandalbert** [comment]
> This message is pretty interesting:
> 
> ```
> The remote name could not be resolved: 'az774065.vo.msecnd.net'
> ```
> 
> I am not sure exactly what that is. If you are on a home network, I would recommend trying to install on a VPN to see if the DNS resolution is fixed.

I am having the same issue.  Obtained it both by running with my ExpressVPN service on and off.

**Comment by day1player** [comment]
@ryandalbert do you have a full tunnel VPN configured? Where did you VPN to?

**Comment by ryandalbert** [comment]
It is a full tunnel starting at my host system. The termination point varies. Typically Houston Texas or New Jersey.

**Comment by johanssontobbe** [comment]
My VPN exits pretty randomly around the world. I tried to exit at a few different countries, but I get the same error.
