### ISSUE TITLE
commando-vm installation doesn't seem to complete

### ISSUE THREAD

**Issue by fzrGit** [fireeye/commando-vm#193]
Hello

I am filling in using google translate.

I'm using win10 with virtualBox. The commando-vm installation doesn't seem to complete. Fill in the log for "C: \ Users \ IEUser \ AppData \ Local \ Boxstarter \ Boxstarter.log".

Also, even if I execute "cinst -y commandovm.win10.config.fireeye -f", the wallpaper will be restored when I restart.

Thank you.
[boxstarter.log](https://github.com/fireeye/commando-vm/files/5938760/boxstarter.log)

**Comment by fzrGit** [comment]
Hello

1 Rebooted.
2 After restarting, the command prompt will start every time you log in automatically.
3 win10 is "17763.r5 release.180914-1434".

Thank you.

**Comment by day1player** [comment]
it sounds like boxstarter is caught in a loop, what happens when you let it finish?

**Comment by fzrGit** [comment]
Hello

The command prompt that appears after a reboot will close automatically. When you reboot, the command prompt will be displayed and it will close automatically.
It looks like the installation is running every time because the installation ends with an error.

Thank you.

**Comment by day1player** [comment]
@fzrGit I would recommend running the `.\install.ps1` script again and letting it run through to completion again. You will probably see some errors along the install but I think that will clear the auto login from boxstarter

**Comment by fzrGit** [comment]
Hello

I ran install.ps with administrator privileges and rebooted, but the command prompt continues to appear after the reboot. I will attach the log.

Thank you.
[boxstarter.log](https://github.com/fireeye/commando-vm/files/5963191/boxstarter.log)
[PowerShell_transcript.COMMANDO.2h0MI+S1.20210211133300.txt](https://github.com/fireeye/commando-vm/files/5963194/PowerShell_transcript.COMMANDO.2h0MI%2BS1.20210211133300.txt)
[PowerShell_transcript.COMMANDO.5alScMGb.20210211133342.txt](https://github.com/fireeye/commando-vm/files/5963195/PowerShell_transcript.COMMANDO.5alScMGb.20210211133342.txt)
[PowerShell_transcript.COMMANDO.65IOVEUz.20210211133437.txt](https://github.com/fireeye/commando-vm/files/5963196/PowerShell_transcript.COMMANDO.65IOVEUz.20210211133437.txt)
[PowerShell_transcript.COMMANDO.AK5u1r1e.20210211133440.txt](https://github.com/fireeye/commando-vm/files/5963197/PowerShell_transcript.COMMANDO.AK5u1r1e.20210211133440.txt)
[PowerShell_transcript.COMMANDO.BXLoJGES.20210211133336.txt](https://github.com/fireeye/commando-vm/files/5963198/PowerShell_transcript.COMMANDO.BXLoJGES.20210211133336.txt)

**Comment by day1player** [comment]
@fzrGit you shouldnt have to manually reboot.. Please run the install script again as administrator and let it run through to completion.

Looking through the log it looks like the auto run was not removed from the registry. Boxstarter will do that automatically if you let the install script complete

**Comment by fzrGit** [comment]
Hello

I waited for about an hour without restarting manually, but it doesn't seem to go beyond the screenshot screen.

Thank you.
![screenshot](https://user-images.githubusercontent.com/78683762/107840193-09469300-6df4-11eb-933e-64e4c66907d2.png)

**Comment by fzrGit** [comment]
Hello

I tried running cinst-y commandovm.win10.config.fireeye--force with boxstarter-post-restart.bat disabled. The background changes to the commando-vm background, but it will be restored on reboot.
Also, when I run cinst-y commandovm.win10.config.fireeye--force, the operation stops at the screenshot screen.

Thank you very much.

![2](https://user-images.githubusercontent.com/78683762/107874714-c4f3e980-6efe-11eb-91c2-da87c740a296.png)
![1](https://user-images.githubusercontent.com/78683762/107874716-c7564380-6efe-11eb-8ed2-0384ddfbf4a3.png)

**Comment by day1player** [comment]
@fzrGit can you try running the following command?
```
C:\ProgramData\Boxstarter\Boxstarter.Bootstrapper\Cleanup-Boxstarter.ps1; Cleanup-Boxstarter
```

You will probably also have to use regedit to change the following key/value from 1 to 0:
```
HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon\AutoAdminLogon
```
This looks to be a boxstarter problem, but this should fix it temporarily.. Please let me know if the issues continue

**Comment by fzrGit** [comment]
Hello

I did the method you taught me and restarted. After restarting, it became as follows.
1 You can no longer log in automatically.
2 The command prompt is no longer displayed.

After rebooting, I installed with install.ps1. It became as follows.
1 You will not be logged in automatically.
2 The command prompt is not displayed.
3 The wallpaper remains the attached image.

Thank you.
![screenshot](https://user-images.githubusercontent.com/78683762/108191674-c1f33600-7156-11eb-916f-a64ed49b4d87.png)
[boxstarter.log](https://github.com/fireeye/commando-vm/files/5994963/boxstarter.log)

**Comment by day1player** [comment]
@fzrGit can you run this command?

```
cinst -y commandovm.win10.config.fireeye -f
```

**Comment by day1player** [comment]
If that doesnt work I would assume your trial has expired and you can run `slrmgr /rearm` and then run the above command again

**Comment by fzrGit** [comment]
Hello

1 The reboot will be completed automatically. The background changed after the reboot, but after about a minute it returned to the original background.

2 slmgr / rearm completed successfully.

3 I'm trying to reinstall.

**Comment by fzrGit** [comment]
Hello

I reinstalled it.
1 The command execution window was not displayed after installation.
2 The background has not changed.

It seems that it can be used.
Thank you very much.
