### ISSUE TITLE
Getting the Same Error over and Over

### ISSUE THREAD

**Issue by cameronww7** [fireeye/commando-vm#196]
Below is my error and some of the Powershell response.

I have rebooted like 10 times, did both a normal script start .\install.ps1 -password <password> and .\install.ps1 -nochecks 1 [<password>] about 5 times each

Cannot get pass the current error.

Running Windows 10 1909 VirtualBox VM

Attached also is the boxstarter logs
Logss
[boxstarter.log](https://github.com/fireeye/commando-vm/files/5963023/boxstarter.log)

`d%20Tools-x86_en-us.msi'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
Downloading windbg.fireeye
  from 'https://codemachine.com/downloads/win10rs1/X86%20Debuggers%20And%20Tools-x86_en-us.msi'
Downloading windbg.fireeye
  from 'https://codemachine.com/downloads/win10rs1/X86%20Debuggers%20And%20Tools-x86_en-us.msi'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://codemachine.com/downloads/win10rs1/X86%20Debuggers%20And%20Tools-x86_en-us.msi'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
The upgrade of windbg.fireeye was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\windbg.fireeye\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - windbg.fireeye (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\windbg.fireeye\tools\chocolateyInstall.ps1'.
 See log for details.
Chocolatey reported an unsuccessful exit code of 404. See C:\Users\camwwspam7@gmail.com\AppData\Local\Boxstarter\boxstarter.log for details.
Boxstarter: Error from Chocolatey:

Message        : Chocolatey reported an unsuccessful exit code of 404. See C:\Users\camwwspam7@gmail.com\AppData\Local\
                 Boxstarter\boxstarter.log for details.
Data           : {}
InnerException :
TargetSite     :
StackTrace     :
HelpLink       :
Source         :
HResult        : -2146233087

Boxstarter: Error from Chocolatey:

Message        : Chocolatey reported an unsuccessful exit code of 404. See C:\Users\camwwspam7@gmail.com\AppData\Local\
                 Boxstarter\boxstarter.log for details.
Data           : {}
InnerException :
TargetSite     :
StackTrace     :
HelpLink       :
Source         :
HResult        : -2146233087

+ Boxstarter finished Calling Chocolatey to install windbg.fireeye. This may take several minutes to complete... 00:00:08.3775519
+ Boxstarter finished Calling Chocolatey to install windbg.fireeye. This may take several minutes to complete... 00:00:08.3775519

ExitCode: 404
ExitCode: 404
2021/02/10 19:31:24 [windbg.fireeye] chocolateyinstall.ps1 [+] ERROR : Failed to install windbg.fireeye
2021/02/10 19:31:24 [windbg.fireeye] chocolateyinstall.ps1 [+] ERROR : Failed to install windbg.fireeye
2021/02/10 19:31:24 [windbg.fireeye] chocolateyinstall.ps1 [+] INFO : Attempting install of proxycap.fireeye
2021/02/10 19:31:24 [windbg.fireeye] chocolateyinstall.ps1 [+] INFO : Attempting install of proxycap.fireeye
WARNING: [!] Installing using host choco.exe! Errors are ignored. Please check to confirm proxycap.fireeye is installed properly
WARNING: [!] Executing: iex choco upgrade proxycap.fireeye --cacheLocation C:\Users\camwwspam7@gmail.com\AppData\Local\ChocoCache -y
+ Boxstarter starting Calling Chocolatey to install proxycap.fireeye. This may take several minutes to complete...
+ Boxstarter starting Calling Chocolatey to install proxycap.fireeye. This may take several minutes to complete...
Upgrading the following packages:
proxycap.fireeye
By upgrading you accept licenses for the packages.
proxycap.fireeye is not installed. Installing...
Progress: Downloading proxycap.fireeye 5.36.0.3... 100%
Progress: Downloading proxycap.fireeye 5.36.0.3... 100%
Progress: Downloading proxycap.fireeye 5.36.0.3... 100%
Progress: Downloading proxycap.fireeye 5.36.0.3... 100%
Progress: Downloading proxycap.fireeye 5.36.0.3... 100%
Progress: Downloading proxycap.fireeye 5.36.0.3... 100%
Progress: Downloading proxycap.fireeye 5.36.0.3... 100%
[NuGet] Installing 'proxycap.fireeye 5.36.0.3'.
[NuGet] Successfully installed 'proxycap.fireeye 5.36.0.3'.

proxycap.fireeye v5.36.0.3
proxycap.fireeye package files upgrade completed. Performing other installation steps.
WARNING: Url has SSL/TLS available, switching to HTTPS for download
File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
Hashes match.
Hashes match.
C:\Users\camwwspam7@gmail.com\AppData\Local\ChocoCache\ProxyCap.installer.msi
Installing proxycap.fireeye...
Installing proxycap.fireeye...
proxycap.fireeye has been installed.
proxycap.fireeye has been installed.
 The upgrade of proxycap.fireeye was successful.
  Software installed as 'msi', install location is likely default.

Chocolatey upgraded 1/1 packages. 0 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Packages requiring reboot:
 - proxycap.fireeye (exit code 3010)

The recent package changes indicate a reboot is necessary.
 Please reboot at your earliest convenience.

Did you know the proceeds of Pro (and some proceeds from other
 licensed editions) go into bettering the community infrastructure?
 Your support ensures an active community, keeps Chocolatey tip top,
 plus it nets you some awesome features!
 https://chocolatey.org/compare
Chocolatey reported an unsuccessful exit code of 3010. See C:\Users\camwwspam7@gmail.com\AppData\Local\Boxstarter\boxstarter.log for details.
Boxstarter: Error from Chocolatey:

Message        : Chocolatey reported an unsuccessful exit code of 3010. See C:\Users\camwwspam7@gmail.com\AppData\Local
                 \Boxstarter\boxstarter.log for details.
Data           : {}
InnerException :
TargetSite     :
StackTrace     :
HelpLink       :
Source         :
HResult        : -2146233087

Boxstarter: Error from Chocolatey:

Message        : Chocolatey reported an unsuccessful exit code of 3010. See C:\Users\camwwspam7@gmail.com\AppData\Local
                 \Boxstarter\boxstarter.log for details.
Data           : {}
InnerException :
TargetSite     :
StackTrace     :
HelpLink       :
Source         :
HResult        : -2146233087

+ Boxstarter finished Calling Chocolatey to install proxycap.fireeye. This may take several minutes to complete... 00:00:09.3321866
+ Boxstarter finished Calling Chocolatey to install proxycap.fireeye. This may take several minutes to complete... 00:00:09.3321866
Boxstarter: writing restart file
Boxstarter: writing restart file
 The install of commandovm.win10.installer.fireeye was successful.
  Software installed to 'C:\Program Files\DBeaver'

Chocolatey installed 1/1 packages. 0 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Packages requiring reboot:
 - commandovm.win10.installer.fireeye (exit code 3010)

The recent package changes indicate a reboot is necessary.
 Please reboot at your earliest convenience.
Boxstarter: found C:\Users\camwwspam7@gmail.com\AppData\Local\Boxstarter\Boxstarter.1336.restart we are restarting
Chocolatey : Chocolatey reported an unsuccessful exit code of 3010. See
C:\Users\camwwspam7@gmail.com\AppData\Local\Boxstarter\boxstarter.log for details.
At C:\ProgramData\boxstarter\boxstarter.chocolatey\Invoke-ChocolateyBoxstarter.ps1:240 char:5
+     Chocolatey install $bootstrapPackage -source $source -force:$forc ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,chocolatey

Boxstarter: Error from Chocolatey:

Message        : Chocolatey reported an unsuccessful exit code of 3010. See
                 C:\Users\camwwspam7@gmail.com\AppData\Local\Boxstarter\boxstarter.log for details.
Data           : {}
InnerException :
TargetSite     :
StackTrace     :
HelpLink       :
Source         :
HResult        : -2146233087

++ Boxstarter finished Calling Chocolatey to install commandovm.win10.installer.fireeye. This may take several minutes to complete... 00:00:44.1162888
Boxstarter: writing restart file
Boxstarter: Restore Automatic Updates from Windows Update
Boxstarter: Enabling UAC
Boxstarter: UAC Enabled. Disabling...
Boxstarter: Disabling UAC
Boxstarter: Securely Storing DESKTOP-28VB67S\camwwspam7@gmail.com credentials for automatic logon
Boxstarter: Logon Set
Boxstarter: Restart Required. Restarting now...

Errors       : {One or more errors occurred., Chocolatey reported an unsuccessful exit code of 3010. See
               C:\Users\camwwspam7@gmail.com\AppData\Local\Boxstarter\boxstarter.log for details.}
ComputerName : localhost
Completed    : False
FinishTime   : 2/10/2021 7:31:35 PM
StartTime    : 2/10/2021 7:30:49 PM

Restart-Computer : One or more errors occurred.
At C:\ProgramData\boxstarter\Boxstarter.Bootstrapper\Invoke-Boxstarter.ps1:145 char:5
+     Restart-Computer -force -ErrorAction SilentlyContinue
+     ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], AggregateException
    + FullyQualifiedErrorId : System.AggregateException`

**Comment by Balr0g404** [comment]
Exactly the same error here

**Comment by day1player** [comment]
Currently looking into this issue, I believe it is related to #193

**Comment by day1player** [comment]
Please try the steps detailed [here](https://github.com/fireeye/commando-vm/issues/193#issuecomment-780190496)

**Comment by cameronww7** [comment]
@day1player I have done the steps you detailed no progress 
When I execute the command recommend 
C:\ProgramData\Boxstarter\Boxstarter.Bootstrapper\Cleanup-Boxstarter.ps1; Cleanup-Boxstarter


All it does it display a txt file
Screenshot of the following
![Capture](https://user-images.githubusercontent.com/16950739/108798291-550ae200-7542-11eb-9854-7c745d95b738.PNG)

**Comment by day1player** [comment]
@cameronww7 try executing that in powershell, it should work then

**Comment by cameronww7** [comment]
@day1player I should have said I did attempt that, this is the what I got
![Capture](https://user-images.githubusercontent.com/16950739/108947013-7dfba780-7614-11eb-8f9c-79243230741b.PNG)

**Comment by cameronww7** [comment]
@day1player Any Ideas?

**Comment by day1player** [comment]
Can you make sure that file exists? You might also be able to import it with `import-module` and then running the command. if that doesnt work you might be able to execute it with `.\Cleanup-Boxstarter.ps1`

If none of that works you might want to just start fresh. It looks like there are a few things that might not have been cleaned up properly. Also if you are able to make sure you are using Win10 2004, I will be rolling out support for newer versions in the coming months but right now 2004 is the latest tested install.

**Comment by cameronww7** [comment]
![1](https://user-images.githubusercontent.com/16950739/110571712-d484dd80-810c-11eb-9d02-1cf1c6c317bc.PNG)

Thanks for replying @day1player !

I am currently using 1909, since the 2004 weren't working well.

Looks like the script doesn't exists. I am confused on what you mean import-module command, I don't have much experience in how this works. Would you be able to explain what you mean? I also have done 3 fresh install attempts on 2004, and 2 on 1909, they all stop at this point it seems.

That's awesome you still working on it, Super excited to get this working, look forward to your releases.

Also is this built on the premise we have valid windows keys? Cause my instance doesn't have a valid key, just was gonna ride it without key.

**Comment by n3tl0kr** [comment]
Not sure if you're still working on this but the easiest way to load this is with

` . C:\ProgramData\Boxstarter\Boxstarter.Bootstrapper\Cleanup-Boxstarter.ps1; Cleanup-Boxstarter`

The "dot space" in the beginning tells Powershell to load this module into memory and then the function can be called by daisy chaining with a semi-colon.

**Comment by day1player** [comment]
fixed with june update #262
