### ISSUE TITLE
[Tool Request] DomainPasswordSpray

### ISSUE THREAD

**Issue by BeanBagKing** [fireeye/commando-vm#2]
Summary from authors GitHub

> DomainPasswordSpray is a tool written in PowerShell to perform a password spray attack against users of a domain. By default it will automatically generate the userlist from the domain. BE VERY CAREFUL NOT TO LOCKOUT ACCOUNTS!

https://github.com/dafthack/DomainPasswordSpray

I searched for this in the readme and saw no reference of it. I apologize if I missed it.

**Comment by Rettila** [comment]
I think this task can be performed using CrackMapExec.

**Comment by xmidopro** [comment]
Add ghidra reverse engineering tool,

**Comment by day1player** [comment]
> Add ghidra reverse engineering tool,

If you're trolling, nice one :-) 

If not, we will have that available as soon as it is available for FLARE VM

**Comment by day1player** [comment]
> I searched for this in the readme and saw no reference of it. I apologize if I missed it.

Thank you for the suggestion! We will get this added.

**Comment by day1player** [comment]
Added to Roadmap

**Comment by day1player** [comment]
Added to 1.1 release
