### ISSUE TITLE
BUG Installation does not finish (2004 Win 10 Pro)

### ISSUE THREAD

**Issue by mueller** [fireeye/commando-vm#200]
**Describe the bug and expected behavior**
When installing commando-vm to a new Windows 10 Pro VM the installation process does not finish, but stop at some point (after one or two restarts, see picture below)

**To Reproduce**
1. Setup base 2004 Windows 10 Pro VM (Virtualbox, 100GB, offline install)
2. Download `install.ps1`
3. Disable tamper protection
4. Go to download folder and execute `Unblock-File .\install.ps1` and `Set-ExecutionPolicy Unrestricted -f`
5. Start the install script `.\install.ps1`
6. Confirm to try and install updates automatically
7. Start installation

**Screenshots**
First screenshot shows the start of the installation script, second the confirmation screen and the third shows where the  installation stops.

![start-install](https://user-images.githubusercontent.com/29411434/112673505-14fe8e00-8e65-11eb-94d2-9ca7e1775ba6.png)
![enter-credentials](https://user-images.githubusercontent.com/29411434/112673509-16c85180-8e65-11eb-86e2-e6f3fef527b2.png)
![end](https://user-images.githubusercontent.com/29411434/112673511-18921500-8e65-11eb-914a-d36381888b25.png)

**Version**
 - Guest-OS: Win10 Pro (2004)
 - Host-OS: Pop!_OS 20.10
 - Commando-VM: Most recent (4f04875)

**Additional context**
I hope that I didn't do some stupid blatant mistake. If you need more information I am happy to help.

**Comment by mueller** [comment]
I forgot to mention: 

I tried to restart the installation with the `-nochecks` flag like mentioned in the install notes (screenshot 2). But then after a few seconds it stops with the following error:

![nocheck-restart](https://user-images.githubusercontent.com/29411434/112676664-fef2cc80-8e68-11eb-9740-3b9912b8619f.png)

**Comment by ybfe1853** [comment]
Funny, I was coming on here to post the exact same issue. Seems to be failing at installing proxycap.fireeye.

**Comment by steelcamp** [comment]
try a ps command 
cinst -y proxycap.fireeye
restart

**Comment by mueller** [comment]
Executing that command (after the installation "aborted") and restarting seems to fix it. The installation is resuming, I will update this comment when it (hopefully) finishes. Thanks!

**Comment by day1player** [comment]
fixed with june update #262
