### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by lucabigoni1992** [fireeye/commando-vm#202]
**Describe the bug and expected behavior**

**To Reproduce**
1 oper cmd like asministrator
2 execute comand: _cd c:\temp_ (folder where i can write  wit all o.s. User)
2 execute comand: _git clone --depth 1 https://github.com/danielmiessler/SecLists.git_
3. See error

**example**

C:\temp>git clone https://github.com/danielmiessler/SecLists.git
Cloning into 'SecLists'...
remote: Enumerating objects: 64, done.
remote: Counting objects: 100% (64/64), done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 9861 (delta 22), reused 55 (delta 20), pack-reused 9797
Receiving objects: 100% (9861/9861), 791.64 MiB | 8.12 MiB/s, done.
Resolving deltas: 100% (5135/5135), done.
error: invalid path 'Payloads/File-Names/traversal/..::..::;'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

the folder C:\temp\SecLists now exist, but it is empty

**Screenshots**
![Cattura](https://user-images.githubusercontent.com/62895248/114320964-ddf0d380-9b18-11eb-85d7-eeae885972d0.PNG)

**Version**
 - OS: Win10

**Comment by GeneralBison** [comment]
How is this an issue with Commando? Surely this is an issue with Git having an issue with the directory traversal payload (which you would expect)

**Comment by day1player** [comment]
we ran in to this issue when creating the seclists.fireeye package.. We remove all of the file traversal payloads in order to have a clean install. You can install this package with `cinst -y seclists.fireeye` instead of using git clone (but yes, you will be missing the directory traversal payloads)
