### ISSUE TITLE
BUG vcpython27 not installed

### ISSUE THREAD

**Issue by Kabindji** [fireeye/commando-vm#204]
**Failures**`

Chocolatey v0.10.15
Installing the following packages:
vcpython27
By installing you accept licenses for the packages.
vcpython27 not installed. The package was not found with the source(s) listed.
 Source(s): 'https://www.myget.org/F/fireeye/api/v2;https://chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify --pre
 the package may not be found.
Please see https://chocolatey.org/docs/troubleshooting for more
 assistance.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures

ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://download.microsoft.com/download/7/9/6/796EF2E4-801B-4FC4-AB28-B59FBF6D907B/VCForPython27.msi'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
The install of vcpython27 was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\vcpython27\tools\chocolateyinstall.ps1'.
 See log for details.

 vcpython27 - vcpython27 not installed. The package was not found with the source(s) listed.
 Source(s): 'https://www.myget.org/F/fireeye/api/v2;https://chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://chocolatey.org/docs/troubleshooting for more
 assistance

**Comment by crahan** [comment]
I ran into the same issue with Flare VM. Microsoft removed the installer file as it's not supported anymore and as a result the Chocolatey package fails to properly install.

Please see my workaround at https://github.com/fireeye/flare-vm/issues/364#issuecomment-827819774

**Comment by day1player** [comment]
fixed with june update #262
