### ISSUE TITLE
install.ps1 execution error

### ISSUE THREAD

**Issue by alvahdati** [fireeye/commando-vm#21]
when executing the script the following error displays:
`At C:\install.ps1:147 char:190
+ ... ata-ga-click="(Logged out) Header, go to Features">Features <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\install.ps1:147 char:261
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in 
double quotation marks ("&") to pass it as part of a string.
At C:\install.ps1:160 char:255
+ ... ogged out) Header, go to Customer stories">Customer stories <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\install.ps1:160 char:326
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in 
double quotation marks ("&") to pass it as part of a string.
At C:\install.ps1:161 char:231
+ ... ata-ga-click="(Logged out) Header, go to Security">Security <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\install.ps1:161 char:302
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in 
double quotation marks ("&") to pass it as part of a string.
At C:\install.ps1:181 char:222
+ ... a-click="(Logged out) Header, go to Explore">Explore GitHub <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\install.ps1:181 char:293
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in 
double quotation marks ("&") to pass it as part of a string.
At C:\install.ps1:184 char:102
+ ... light text-normal text-mono f5 mb-2  border-top pt-3">Learn &amp; con ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in 
double quotation marks ("&") to pass it as part of a string.
At C:\install.ps1:217 char:185
+ ... r" data-ga-click="(Logged out) Header, go to Pricing">Plans <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : RedirectionNotSupported`
set-executionpolicy unrestricted is done, so i expected not to ask whether to run install.ps1 or not. any ideas?

**Comment by day1player** [comment]
What version of Windows is this? 

Is the machine fully updated with windows updates?

**Comment by alvahdati** [comment]
@day1player
Windows 10 enterprise latest version latest build. Yes fully updated and no more update available.

**Comment by day1player** [comment]
Try copying the contents from here and creating a new install script:
https://raw.githubusercontent.com/fireeye/commando-vm/master/install.ps1

It looks like there is some HTML in there which should not exist.

**Comment by alvahdati** [comment]
@day1player thanks. seems like started to install and configure.
