### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by SchellerCyberSecurity** [fireeye/commando-vm#22]
**Describe the bug and expected behavior**
Commando install script is not finding the metasploit install file.

Downloading metasploit.flare 64 bit                                                                                       from 'https://windows.metasploit.com/metasploit-framework-5.0.14%2B20190325163246-1rapid7-1-x64.msi'                  Downloading metasploit.flare 64 bit                                                                                       from 'https://windows.metasploit.com/metasploit-framework-5.0.14%2B20190325163246-1rapid7-1-x64.msi'                  ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://windows.metasploit.com/metasploit-framework-5.0.14%2B20190325163246-1rapid7-1-x64.msi'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."                                                                    The upgrade of metasploit.flare was NOT successful.                                                                     Error while running 'C:\ProgramData\chocolatey\lib\metasploit.flare\tools\chocolateyInstall.ps1'.                        See log for details.                                                                                                                           

**Version**
 - OS: Win10 Pro

**Additional context**

**Comment by SecurityAddicted** [comment]
The script is trying to download a Metasploit version that doesn't exist anymore on the build server
IMHO it should just pull the -latest.msi file.

**Comment by SchellerCyberSecurity** [comment]
That's what I was thinking, so I don't know why it is failing. Possibly the script is hard coded with that version instead of a wildcard to pull the newest?

**Comment by SecurityAddicted** [comment]
Yep hardcoded version I guess.

**Comment by KuriosCurious** [comment]
The Commando-VM scripts are linked to Flare-VM. There is an issue open for it there.

https://github.com/fireeye/flare-vm/issues/203

> We are aware that Metasploit pushes out update very regularly, which causes the installer to fails often. We are working a permanent solution. Currently, we can't use the metasploitframework-latest.msi since we can not verify the hash using a different source other than the .asc file available on metasploit server. We also can not/should not include the entire metasploit installer in our chocolatey package. Any recommendation to address this is welcome.

**Comment by htnhan** [comment]
We have pushed a new version for metasploit. Please try the installation again, and let us know if you still have issues installing metasploit.

**Comment by JamesIbarra12** [comment]
I too was receiving the above errors, after you pushed a new version for metasploit i pulled a fresh clone and ran install.ps1 again. Now I receive different errors:  

ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path 'C:\metasploit-framework\bin' because it does not exist.
The upgrade of metasploit.flare was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\metasploit.flare\tools\chocolateyInstall.ps1'.
See log for details.
Failed to install metasploit.flare

I now have a metasploit folder in tools, however it is empty.
