### ISSUE TITLE
[Tool Request] Additional programming languages

### ISSUE THREAD

**Issue by veeral-patel** [fireeye/commando-vm#25]
I think we should add Choco packages for additional programming languages:

- [Perl](https://chocolatey.org/packages/StrawberryPerl)
- [Ruby](https://chocolatey.org/packages/ruby)
- [PHP](https://chocolatey.org/packages/php)

This'll help pentesters build tools quickly, without worrying about how to install software on Commando. Also, this'll help pentesters who don't have Internet access on their VM or computer and can't download additional software. 

Feel free to assign this to me.

**Comment by veeral-patel** [comment]
I submitted a pull request: https://github.com/fireeye/commando-vm/pull/26

**Comment by day1player** [comment]
Closing this as you can now add programming languages via chocolatey packages with custom installs
