### ISSUE TITLE
Install.ps1 error

### ISSUE THREAD

**Issue by mobychien** [fireeye/commando-vm#27]
install.ps1 error under Windows 10 Enterprise fully updated:

> _Chocolatey

Chocolatey : Chocolatey reported an unsuccessful exit code of 1. See
C:\Users\Admin\AppData\Local\Boxstarter\boxstarter.log for details.
At C:\ProgramData\boxstarter\BoxStarter.Chocolatey\Invoke-ChocolateyBoxstarter.ps1:199 char:5
+     Chocolatey install $bootstrapPackage -source $source -force:$forc ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,chocolatey

**Comment by htnhan** [comment]
@mobychien  I am not sure if I have seen the WriteErrorException before. Please post the entire boxstarter log at C:\Users\Admin\AppData\Local\BoxStarter\boxstarter.log, as well as the chocolatey log at C:\ProgramData\chocolatey\logs\chocolatey.log, to help us troubleshoot this issue.

Thank you

**Comment by mobychien** [comment]
Here are the two log files.
[boxstarter.log](https://github.com/fireeye/commando-vm/files/3051594/boxstarter.log)
[chocolatey.log](https://github.com/fireeye/commando-vm/files/3051596/chocolatey.log)

**Comment by yaffeweb** [comment]
I too am having trouble installing Boxstarter. 
```
Failures
 - Boxstarter - Boxstarter not installed. The package was not found with the source(s) listed.
 Source(s): 'https://www.myget.org/F/fireeye/api/v2;https://chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Version was specified as '2.12.0'. It is possible that version
 does not exist for 'Boxstarter' at the source specified.
```
This then followed by several other errors about the not being loaded because no valid module file was found in any module directory.

Windows 10 pro fully updated. 
[chocolatey.log](https://github.com/fireeye/commando-vm/files/3179841/chocolatey.log)

I have no boxstarter.log I assume cause it's not getting installed.

**Comment by ruudeee** [comment]
deactivating the windows firewall solved the problem for me

**Comment by day1player** [comment]
closing stale issue
