### ISSUE TITLE
Setup details

### ISSUE THREAD

**Issue by ben4361** [fireeye/commando-vm#29]
What are the setup details for Bloodhound, I tried the pw bloodhound and that did not work.

**Comment by ben4361** [comment]
No database found

**Comment by D3ano** [comment]
Start Neo4j
C:\Tools\neo4j-community\neo4j-community-3.5.1\bin>neo4j.bat console
May need to change default password on first setup.
Once setup and running, just start Bloodhound.

**Comment by day1player** [comment]
@D3ano is correct this should fix your issue. There is also a `Neo4j_start.bat` script it the Tools -> Utilities folder that will start the service for you if you "Run as Admin". If you've never logged into neo4j bloodhound will prompt you to visit http://localhost:7474 to set the initial password.
