### ISSUE TITLE
Can it do wifi montoring ?

### ISSUE THREAD

**Issue by minanagehsalalma** [fireeye/commando-vm#3]
Aircrack-ng   ?

**Comment by veeral-patel** [comment]
@minanagehsalalma Looking at the README, not yet

**Comment by minanagehsalalma** [comment]
OK I hope you add it soon :)

**Comment by day1player** [comment]
We will be adding wireless in the future.

**Comment by minanagehsalalma** [comment]
@day1player  yes please  cause this would make a huge difference ...
Cause  this the only thing that you can't  do on vm without external  adapter  .
