### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by jeffparkermodhd** [fireeye/commando-vm#36]
**Description**
The Bug is where outta nowhere it will start freezing and lagging hard.

**To Reproduce**
1.  It starts outta nowhere!

**Version**
 - OS: [e.g. Win10 Home]
 - Version: [10.0.17134]
 - Build [17134]

**Comment by day1player** [comment]
Sounds like a terrible problem! How much RAM are you using?

**Comment by jeffparkermodhd** [comment]
> 
> 
> Sounds like a terrible problem! How much RAM are you using?

I was not running any programs. It started right after installation.

**Comment by day1player** [comment]
@jeffparkermodhd let me know what I can do to help. If you can provide error output, hardware specs, etc, that would be appreciated.

**Comment by jeffparkermodhd** [comment]
> @jeffparkermodhd let me know what I can do to help. If you can provide error output, hardware specs, etc, that would be appreciated.

My pc link: https://www.amazon.com/gp/product/B07B6H4GNY/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1

Explanation: I won’t be able to give much more information I am moving to Linux specifically kali Linux to pursue my big hunting career.

**Comment by day1player** [comment]
@jeffparkermodhd thanks let us know if you have issues in the future!
