### ISSUE TITLE
FEATURE REQUEST - gobuster

### ISSUE THREAD

**Issue by 0xdf-0xdf** [fireeye/commando-vm#39]
**Would you like have a tool or script added? Please include a link**
gobuster
https://github.com/OJ/gobuster/releases

**Is your feature request related to a problem? Please describe.**
Web path enumeration

**If related to a problem, describe the solution you'd like**
Have gobuster installed

**Describe alternatives you've considered**
I can install it myself.

**Comment by day1player** [comment]
added to roadmap

**Comment by day1player** [comment]
Added to 1.2 release
