### ISSUE TITLE
FEATURE REQUEST - wfuzz

### ISSUE THREAD

**Issue by 0xdf-0xdf** [fireeye/commando-vm#40]
**Would you like have a tool or script added? Please include a link**
wfuzz
https://github.com/xmendez/wfuzz

**Is your feature request related to a problem? Please describe.**
Useful for some many things when interacting with a website. Can FUZZ paths, arguments, parameters, headers, cookies, subdomains, etc.

**If related to a problem, describe the solution you'd like**
Install and get working well on Windows system.

**Describe alternatives you've considered**
I can install it myself (`\python27\python -m pip install wfuzz`). It doesn't work great. The output is very laggy, and it runs slow.

**Comment by day1player** [comment]
added to roadmap

**Comment by day1player** [comment]
Added to 1.2 release
