### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by mycryptonite** [fireeye/commando-vm#44]
**Describe the bug and expected behavior**
Metasploit keeps getting re-downloaded again and again saying that the hashes don't match. Not sure if chocolatey is doing the checksum check. What can I do?

**Comment by day1player** [comment]
@mycryptonite Thanks for the report. Metasploit is occasionally updated and the hash we have with the install then no longer matches. We updated to the current hash. Please let us know if you are still having issues.
