### ISSUE TITLE
BUG: "An existing connection was forcibly closed by the remote host."

### ISSUE THREAD

**Issue by day1player** [fireeye/commando-vm#46]
**Describe the bug and expected behavior**

When using the install.ps1 script some packages may fail with the below error:
```
Failures
 - openvpn.fireeye (exited 1) - openvpn.fireeye not installed. An error occurred during installation:
 Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
Chocolatey reported an unsuccessful exit code of 1. See C:\Users\kevin\AppData\Local\Boxstarter\boxstarter.log for details.
```

**Screenshots**

**Version**
 - OS: [e.g. Win7]

Windows 7/10

**Work Around**
If you notice packages have failed when running the install.ps1 script, you may attempt to run the install.ps1 script again and that may resolve your issues, however, manually installing them seems much more reliable

Example:
```
cinst openvpn.fireeye
```

**Comment by MalwareMechanic** [comment]
Hmm seems related to #12. We're still trying to track down the root cause.

**Comment by day1player** [comment]
See #123
