### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by ostes** [fireeye/commando-vm#47]
i have this error when I tried execute ps1
![image](https://user-images.githubusercontent.com/50025344/56820239-be741980-6821-11e9-8ddd-da0fccc54bdf.png)

**Comment by day1player** [comment]
@ostes copy the contents from this link into that install file: https://raw.githubusercontent.com/fireeye/commando-vm/master/install.ps1

It looks like you have some HTML code in there.

**Comment by ostes** [comment]
gracias
