### ISSUE TITLE
Add a Packer template

### ISSUE THREAD

**Issue by veeral-patel** [fireeye/commando-vm#5]
Packer (https://www.packer.io) lets us write templates for virtual machines and turns them into VM images that can be deployed to AWS/DigitalOcean/VMWare/VirtualBox/etc

We should write 1 Packer template each for AWS, VMWare, and VirtualBox IMO, and then add additional providers later.

This would enable people to create VMs quickly, without leaving the command line.

Because Packer supports Powershell provisioners, we could keep our existing Powershell installation script and not replace it with another tool like Ansible.

Talked about this with Blaine Stancill from FLARE on 3/29/18

**Comment by day1player** [comment]
Added to our Roadmap.
