### ISSUE TITLE
BUG - Metasploit Fails to Install (due to new version release)

### ISSUE THREAD

**Issue by iAngelus** [fireeye/commando-vm#53]
Bug has recurred with another fresh release of Metasploit (i.e metasploit-framework-5.0.21+20190503200152-1rapid7-1-x64.msi)

[NuGet] Installing 'metasploit.flare 5.0.19.20190423'.
[NuGet] Successfully installed 'metasploit.flare 5.0.19.20190423'.
metasploit.flare v5.0.19.20190423
metasploit.flare package files upgrade completed. Performing other installation steps.
Attempt to get headers for https://windows.metasploit.com/metasploit-framework-5.0.19%2B20190423193305.git.7.b9e2e14-1rapid7-1-x64.msi failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://windows.metasploit.com/metasploit-framework-5.0.19%2B20190423193305.git.7.b9e2e14-1rapid7-1-x64.msi'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
Attempt to get headers for https://windows.metasploit.com/metasploit-framework-5.0.19%2B20190423193305.git.7.b9e2e14-1rapid7-1-x64.msi failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://windows.metasploit.com/metasploit-framework-5.0.19%2B20190423193305.git.7.b9e2e14-1rapid7-1-x64.msi'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
Downloading metasploit.flare 64 bit
  from 'https://windows.metasploit.com/metasploit-framework-5.0.19%2B20190423193305.git.7.b9e2e14-1rapid7-1-x64.msi'
Downloading metasploit.flare 64 bit
  from 'https://windows.metasploit.com/metasploit-framework-5.0.19%2B20190423193305.git.7.b9e2e14-1rapid7-1-x64.msi'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://windows.metasploit.com/metasploit-framework-5.0.19%2B20190423193305.git.7.b9e2e14-1rapid7-1-x64.msi'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
The upgrade of metasploit.flare was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\metasploit.flare\tools\chocolateyInstall.ps1'.
 See log for details.
Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Failures
 - metasploit.flare (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\metasploit.flare\tools\chocolateyInstall.ps1'.
 See log for details.
Chocolatey reported an unsuccessful exit code of 404. See C:\Users\user\AppData\Local\Boxstarter\boxstarter.log for details.
+ Boxstarter finished Calling Chocolatey to install metasploit.flare. This may take several minutes to complete... 00:00:10.3561916
+ Boxstarter finished Calling Chocolatey to install metasploit.flare. This may take several minutes to complete... 00:00:10.3561916
ExitCode: 404
ExitCode: 404
Failed to install metasploit.flare

**Comment by htnhan** [comment]
@iAngelus  Thank you for reporting this issue. We have update metasploit to 5.0.21.20190503. Please try to install metasploit again.

Nhan T. Huynh
