### ISSUE TITLE
BUG - Proxycap.fireeye filed to install (i.e. hashes do not match)

### ISSUE THREAD

**Issue by iAngelus** [fireeye/commando-vm#54]
[NuGet] Installing 'proxycap.fireeye 5.32.0.2'.
[NuGet] Successfully installed 'proxycap.fireeye 5.32.0.2'.

proxycap.fireeye v5.32.0.2
proxycap.fireeye package files upgrade completed. Performing other installation steps.
File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
**Error - hashes do not match. Actual value was 'A59426233B10B0CB4512CC5022AA9D40DF43CD98A361AD86A9A279EB640825D6'.**
Downloading proxycap.fireeye 64 bit
  from 'http://www.proxycap.com/download/pcap532_x64.msi'
Downloading proxycap.fireeye 64 bit
  from 'http://www.proxycap.com/download/pcap532_x64.msi'
WARNING: C:\Users\user\AppData\Local\Temp\ProxyCap.installer.msi is of content type text/html; charset=UTF-8
Progress: 100% - Completed download of C:\Users\user\AppData\Local\Temp\ProxyCap.installer.msi (8.55 KB).

Download of ProxyCap.installer.msi (8.55 KB) completed.
Download of ProxyCap.installer.msi (8.55 KB) completed.
Error - hashes do not match. Actual value was 'A59426233B10B0CB4512CC5022AA9D40DF43CD98A361AD86A9A279EB640825D6'.
ERROR: Checksum for 'C:\Users\user\AppData\Local\Temp\ProxyCap.installer.msi' did not meet '3B3FD836AB5D549E96D2A4C12C3884CEDC842EDF8397B7B555B83C79DBB7C40A' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
The upgrade of proxycap.fireeye was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\proxycap.fireeye\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - proxycap.fireeye (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\proxycap.fireeye\tools\chocolateyInstall.ps1'.
 See log for details.
Chocolatey reported an unsuccessful exit code of -1. See C:\Users\user\AppData\Local\Boxstarter\boxstarter.log for details.
+ Boxstarter finished Calling Chocolatey to install proxycap.fireeye. This may take several minutes to complete... 00:00:12.3780691
+ Boxstarter finished Calling Chocolatey to install proxycap.fireeye. This may take several minutes to complete... 00:00:12.3780691
ExitCode: -1
ExitCode: -1
Failed to install proxycap.fireeye

**Comment by day1player** [comment]
@iAngelus This is now fixed, please run `cup proxycap.fireeye` and it will install correctly.
