### ISSUE TITLE
metasploit fails 

### ISSUE THREAD

**Issue by cybersecdo** [fireeye/commando-vm#56]
hello 
i just install commando vm in my windows 10
after all the installation its all done without errors its looking like mtasploit  and nmap missing from the instalation pack
I have try to install manually "choco install metasploit" and i get this error:::

λ choco install metasploit                                                            
Chocolatey v0.10.13                                                                   
Installing the following packages:                                                    
metasploit                                                                            
By installing you accept licenses for the packages.                                   
metasploit not installed. The package was not found with the source(s) listed.        
 Source(s): 'https://www.myget.org/F/fireeye/api/v2;https://chocolatey.org/api/v2/'   
 NOTE: When you specify explicit sources, it overrides default sources.               
If the package version is a prerelease and you didn't specify `--pre`,                
 the package may not be found.                                                        
Please see https://chocolatey.org/docs/troubleshooting for more                       
 assistance.                                                                          
                                                                                      
Chocolatey installed 0/1 packages. 1 packages failed.                                 
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).             
                                                                                      
Failures                                                                              
 - metasploit - metasploit not installed. The package was not found with the source(s)
 listed.                                                                              
 Source(s): 'https://www.myget.org/F/fireeye/api/v2;https://chocolatey.org/api/v2/'   
 NOTE: When you specify explicit sources, it overrides default sources.               
If the package version is a prerelease and you didn't specify `--pre`,                
 the package may not be found.                                                        
Please see https://chocolatey.org/docs/troubleshooting for more                       
 assistance.                                                            

I INSTALL NMAP BUT ITS LOOKING I CAN NOT IND THE FILE ?
λ choco install nmap                                                         
Chocolatey v0.10.13                                                          
Installing the following packages:                                           
nmap                                                                         
By installing you accept licenses for the packages.                          
nmap v7.70 already installed.                                                
 Use --force to reinstall, specify a version to install, or try upgrade.     
                                                                             
Chocolatey installed 0/1 packages.                                           
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).    
                                                                             
Warnings:                                                                    
 - nmap - nmap v7.70 already installed.                                      
 Use --force to reinstall, specify a version to install, or try upgrade.     
                                                                             
Enjoy using Chocolatey? Explore more amazing features to take your           
experience to the next level at                                              
 https://chocolatey.org/compare                                              
                                                                             

λ nmap --help
Cannot find file at 'c:\program files (x86)\nmap\nmap.exe' (c:\program files (x86)\nmap\nmap.exe). This usually indicates a missing or moved file.
GUYS CAN YOU HELP ME HOW TO FIGURE OUT WHIT THIS 2 TOOLS?
I NEED THEM 
THANK YOU

**Comment by htnhan** [comment]
@cybersecdo For future references, please create an issue for each tool. It will help us track these issues better.

A new version of metasploit has been pushed to myget. Please try to install metasploit again. We'll look into nmap issue soon.

Nhan T. Huynh

**Comment by cybersecdo** [comment]
@htnhan {Install Again}? Can you please tell me how to install metasploit if whit choco command its not working?
thank you

**Comment by MalwareMechanic** [comment]
@cybersecdo Please try to install the following packages in an Admin PowerShell prompt:

- `choco upgrade metasploit.flare -f`
- `choco upgrade nmap.fireeye -f`

**Comment by C1S0** [comment]
@MalwareMechanic this is also returning an error

PS C:\Users\XXX> choco upgrade metasploit.flare -f
Chocolatey v0.10.13
Upgrading the following packages:
metasploit.flare
By upgrading you accept licenses for the packages.
metasploit.flare is not installed. Installing...
Progress: Downloading metasploit.flare 5.0.21.20190503... 100%
Progress: Downloading metasploit.flare 5.0.21.20190503... 100%

metasploit.flare v5.0.21.20190503 (forced)
metasploit.flare package files upgrade completed. Performing other installation steps.
File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
Hashes match.
Hashes match.
C:\Users\XXX\AppData\Local\Temp\metasploit.installer.msi
Installing metasploit...
metasploit has been installed.
ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path 'C:\metasploit-framework\bin' because it does not exist.
  metasploit.flare may be able to be automatically uninstalled.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
The upgrade of metasploit.flare was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\metasploit.flare\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - metasploit.flare (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\metasploit.flare\tools\chocolateyInstall.ps1'.
 See log for details.

**Comment by MalwareMechanic** [comment]
@C1S0 Did you run the command in an Admin PowerShell prompt? If not try it again in an Admin PowerShell prompt.

If you did, try executing `C:\Users\XXX\AppData\Local\Temp\metasploit.installer.msi` directly. If it installs fine, then verify that `C:\metasploit-framework\bin` exists and run `choco upgrade metasploit.flare -f` again from an Admin PowerShell prompt.

**Comment by C1S0** [comment]
@MalwareMechanic 
yes I used the admin PS and it didn't work. After the error above appears the installer is also deleted from the disk.
However, I tried to install the metasploit latest installer from https://windows.metasploit.com/metasploitframework-latest.msi and that seems running successfully (metasploit is added to the env variable path) but the files are not to be found on the disk.
Both issues happen only in the Commando VM.

**Comment by MalwareMechanic** [comment]
@C1S0 Interesting. Is Windows defender enabled? If so, it might be deleting the files as soon as they are dropped to disk.

**Comment by C1S0** [comment]
@MalwareMechanic 
nope, everything disabled, which is what the commando ps1 does, right?

**Comment by cybersecdo** [comment]
Guys just give up,i have try install whit all yours commands but at the end
I install Metasploit from the github
windows never be a hacking machine just office.
Respect kali linux no compare!

**Comment by C1S0** [comment]
@cybersecdo i respect your comment, but that's not the right attitude in my opinion.
I have several laptops with different setups for different jobs and requirements.
I think Commando VM has the real potential to change the perspective that Windows cannot be used for pen testing. And so, I still investigate what's wrong in my VM

**Comment by MalwareMechanic** [comment]
@C1S0 Yep, we disable it before installing other packages. However, it sounds like an issue with the metasploit installer -- not necessarily an issue, but the the MSI isn't dropping the files and creating the expected directories. I wonder, are there any other AV-products at play here (maybe on the host)?

**Comment by C1S0** [comment]
The latest metasploit installer solved this issue.

**Comment by BlackListSec** [comment]
Follow this to fix your issue. 
https://chocolatey.org/install. Worked for me!
