### ISSUE TITLE
Uninstall Commando-VM

### ISSUE THREAD

**Issue by Charon1609** [fireeye/commando-vm#57]
how to uninstall commando vm? 
i will use it at virtualbox
but thank you great work

**Comment by Charon1609** [comment]
??????

**Comment by MalwareMechanic** [comment]
@Charon1609 Commando VM is meant to be installed on a Windows virtual machine. Typically you'd remove/delete the virtual machine to get rid of Command VM. If you have snapshots, you could also revert to a state prior to installing Commando VM.

However, you can attempt to uninstall our packages by executing one of the following in an Admin PowerShell prompt depending on which version you installed:
- `choco uninstall commandovm.win10.installer.fireeye`
- `choco uninstall commandovm.win7.installer.fireeye`

It should be noted that this will only uninstall our direct packages (i.e., those listed in the `packages.json` file). This will not remove any dependencies installed. If you wish to remove the dependencies as well, you'll have to remove them manually. You can see what packages are installed on your system by executing: `choco list -l`.

If you find this extremely tiresome, want to remove literally everything related to Chocolatey, and don't mind potentially breaking your system, you can try to run what is listed here: https://chocolatey.org/docs/uninstallation

Hope this helps!
