### ISSUE TITLE
WARNING: Installation of this MSI is not supported on this platform.

### ISSUE THREAD

**Issue by SalvorinFex** [fireeye/commando-vm#6]
Hello, 
I am in the process of installing this on Win 10 Ent 64 VM through VirtualBox, but I keep seeing this message popping up during the install.
```
WARNING: Installation of this MSI is not supported on this platform. Contact package maintainer(s) if you feel this is in error or if you need an architecture that is not available with the current packaging.
```
Then whatever comes after it is in red text saying that the Install failed.

Is this a known issue, if so, how can I proceed to remedy this issue.

**Comment by htnhan** [comment]
@SalvorinFex  Which package causes this issue? Do you mind providing more logs to help us triage this?

**Comment by SalvorinFex** [comment]
It was happing on all MSI packages, from what I could tell.
Sure I can share the logs, just let me know where they are and how you would like me to share them.

**Comment by day1player** [comment]
@SalvorinFex are you still having this issue? What version of Windows are you using?

**Comment by SalvorinFex** [comment]
@day1player This is a Windows 10 Enterprise VM.  I have not pulled anything from this recently, but if something has changed I can try again.

**Comment by SalvorinFex** [comment]
Still waiting for some instructions on the logs you need @htnhan ??

@day1player Any other questions?

**Comment by htnhan** [comment]
@SalvorinFex Please provide the following logs:

C:\Users\<username>\AppData\Local\BoxStarter\boxstarter.log
C:\ProgramData\chocolatey\logs\chocolatey.log

**Comment by SalvorinFex** [comment]
Here's a link to those two log files:
https://1drv.ms/f/s!AnWO4CwHCufgmK81L76DSTwT4TO-Ww

**Comment by SalvorinFex** [comment]
@htnhan Hello again, any updates on the output form my logs?

**Comment by htnhan** [comment]
@SalvorinFex 

I apologize for the delay. I looked at the chocolatey.log (line 4866 and 4867). The log shows that the MSI installer fails with error code 1632. From googling, most people suggest that the error occurs when the MSI can not write to the %TEMP% directory, likely because there is not enough disk space. Can you check and confirm there is enough disk space for the installation?

**Comment by SalvorinFex** [comment]
@htnhan Yes, there's like 30gbs free in that VM.
I made a 60gb drive and Win 10 only used about 15 gbs, plus a bit for Commando.

**Comment by SalvorinFex** [comment]
@htnhan greetings, any other things I should/could check for this issue?

**Comment by htnhan** [comment]
@SalvorinFex  Unfortunately, I am unable to find the root cause, nor a plausible mitigation for this issue.  If possible, can you also try creating a completely new VM and installing Commando on the new VM? I would like to see if this issue is specific to your VM, or maybe your OS.

**Comment by SalvorinFex** [comment]
@htnhan Well, I was able to get a Win 10 Pro key working and activated, and Commando installed fine without any MSI issues.  So, I suspect that the Enterprise Version of Win 10 is what was causing the MSI issues.  I think it's worth investigating on your end, due to your system Requirements just say 'Windows 10" without any caveats.

**Comment by day1player** [comment]
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/37482972/58659744-fff45a80-82e0-11e9-9635-77a97669a2ce.png">
Windows 10 Enterprise working on latest version of Commando

**Comment by SalvorinFex** [comment]
@day1player Well, I followed the exact same process on each of mine, and for Enterprise I had the MSI issues and on Professional I did not.  I supplied my logs and you weren't around to look at them and maybe find a solution.  So, I had to start over and it worked.

**Comment by day1player** [comment]
@SalvorinFex Awesome. I'm not sure exactly what it was as I tested install on Enterprise edition almost exclusively pre and post release and didn't have any issues. I can only imagine it was a Windows Gremlin!!
