### ISSUE TITLE
No Utitlities

### ISSUE THREAD

**Issue by vkm0148** [fireeye/commando-vm#60]
After installation I have a folder named Tools which consist of only one folder named Utilities with only Adobe Reader and CMDer installed.
Are only these two apps were supposed to be installed or I had an issue with the installation.
If latter then please help me rectify it and get all other tools.

TIA

**Comment by day1player** [comment]
@vkm0148 It does appear that the installation was unsuccessful. You should have many folders in there, as well as many tools inside of each folder. 

Try running the install script again, it should fix your install.
