### ISSUE TITLE
BUG: Covenant out-of-date and broken

### ISSUE THREAD

**Issue by IppSec** [fireeye/commando-vm#61]
**Describe the bug and expected behavior**
When attempting to use The Covenant, my grunts have trouble executing commands.  It appears this has been fixed in a later build of The Covenant, as updating Covenant fixed this issue.  In order for the latest version to run, I needed to install the DotNet Core 2.2.106 (https://dotnet.microsoft.com/download/dotnet-core/2.2)

**To Reproduce**
1. Run Covenant and Elite
2. Execute a launcher to get a Grunt
3. Attempt to run any command.

**Version**
 - OS:  Win10

**Comment by day1player** [comment]
@IppSec Thank you for the info! I will add this to be completed with the May update (next week)

**Comment by day1player** [comment]
Update: Will have to push to June update.

**Comment by day1player** [comment]
Package has been updated and op-tested in the 1.3 release.

Thank you! Let us know if you have anymore issues/suggestions.
