### ISSUE TITLE
Out of date software

### ISSUE THREAD

**Issue by pamurp7789** [fireeye/commando-vm#62]
Hello,

Love the product, thanks for sharing.

I installed today and noticed I needed to manually update a few things.  Sharing here in case you want to incorporate so this doesn't need to be repeated by everyone.

Visual Studio Community - 2017 -> 2019
Cloud Explorer for VS - 1.2.1810.253 -> 1.2.1812.142
Adobe Reader - 19.010.20099 -> 19.012.20034
Citrix Receiver 14.12.0.18020 -> Citrix Workspace 19.4.1.41
DBbrowser for SQLITE - 3.10.1 -> 3.11.2
GPG4WIN - 2.3.4 -> 3.1.7
Java 8 JDK - 8 update 211 -> 8 update 212
Npcap - 0.99-r2 -> 0.99-r5
OpenVPN - 2.4.6 -> 2.4.7
Python (x86/x64) - 2.7.15 -> 2.7.16
SDK Debuggers - 10.1.10586.15 -> 10.0.18362.1
AutoIt for Scite - 3.5.4.0 -> 4.1.2.0
VMware Remote Console Plugin - 9.0.0.35586 -> 15.1.46741

vcredist 2005 x86 - 8.0.61001 -> 8.0.61187
vcredist 2005 x64 - 8.0.61000 -> 8.0.61186
vcredist 2008 x86/x64 - 9.0.30729.6161 -> 9.0.30729.7523
vcredist 2012 x86/x64 - 11.0.61030.0 -> removed all, 2013 is compatible with 2012
vcredist 2013 x86/x64 - various versions -> replaced with 12.0.40664
vcredist 2015-2019 x86/x64 - 14.20.27508.1 -> 14.21.27619

Let me know if you have any questions.

**Comment by day1player** [comment]
@pamurp7789 Thank you for the detailed notes, I will see what I can do to address this in the update next week.

**Comment by day1player** [comment]
@pamurp7789 I have been going through our repos and am discovering that a lot of these packages are in revision or awaiting approval from the Chocolatey staff. For example here: https://chocolatey.org/packages/sqlitebrowser/3.11.2 you can see they have a package but just haven't reviewed code for it yet. 

In order for us to minimize overhead for maintaining the VM we have to rely on Chocolatey for a lot of version updates. Another example would be that they do not yet have a Visual Studio 2019 package, however once that becomes available we will stick it in the build. 

That said, a lot of these will have to wait until one of the next releases! Your notes have been very useful, thank you.
