### ISSUE TITLE
Metaspolit Database not working

### ISSUE THREAD

**Issue by codesahil** [fireeye/commando-vm#66]
I updated Metasploit with chocolaty after installation but when i run msfconsole I get this error where database is unable to start or initialize.How can i fix this
[-] ***
[-] * WARNING: No database support: could not connect to server: Connection refused (0x0000274D/10061)
        Is the server running on host "127.0.0.1" and accepting
        TCP/IP connections on port 5433?

[-] ***

**Comment by day1player** [comment]
@codesahil please check this issue to see if it will resolve what you are seeing: https://github.com/fireeye/commando-vm/issues/8
