### ISSUE TITLE
Unharded UNC paths

### ISSUE THREAD

**Issue by Raikia** [fireeye/commando-vm#68]
Windows 10 now prevents users from accessing SYSVOL, NETLOGON, and other administrative shares via UNC path.  The error it gives you if you try is a cryptic "Network access is denied"

**To Reproduce**
1. Be on a network with a domain
2. Open cmd via runas netonly
3. dir \\\\domain\sysvol
4. See "Network Access Denied" error

**Version**
 - OS: Windows 10 only

**To Fix This Issue**
1. Run "gpedit.msc"
2. Go to "Computer" --> "Administrative Templates" --> "Network" --> "Network Provider" --> "Hardened UNC Paths"
3. Enable the policy and click "Show" button.
4. Under "Value Name", enter "\\\\*" (no quotes)
5. Under "Value", enter "RequireMutualAuthentication=0,RequireIntegrity=0,RequirePrivacy=0" (no quotes)
6. Apply all settings and close gpedit.msc
7. Profit

**Source**
https://www.web-workers.ch/index.php/2017/05/16/domain-joined-windows-10-network-access-is-denied-on-sysvol-and-netlogon/

**Comment by day1player** [comment]
Step 7

*drops mic*

**Comment by day1player** [comment]
Addressed in the 1.3 release

**Comment by Raikia** [comment]
@day1player it looks like the fix you applied to this is incorrect.

Your fix adds: "RequireMutualAuthentication=0,RequireIntegrity=0,RequirePrivacy=0RequireMutualAuthentication=0,RequireIntegrity=0,RequirePrivacy=0"
(accidentally pasted in there twice)

It needs to be: "RequireMutualAuthentication=0,RequireIntegrity=0,RequirePrivacy=0"

**Comment by day1player** [comment]
fixed in #147
