### ISSUE TITLE
Add logging for each package installed 

### ISSUE THREAD

**Issue by denevin** [fireeye/commando-vm#70]
It would be nice to have a summary report at the end of the installation which lists the tools that were successfully installed lets say in green color and which tools failed to be installed in red color.

This would help with figuring out which tools failed to install without having to look through detailed logs.

**Comment by day1player** [comment]
@denevin I agree, this would be a nice improvement. I will get it added to the roadmap

**Comment by Tarin** [comment]
This would make life so much easier, currently trying to screenshot or copy paste and save all errors is so difficult and means having to watch for the whole install

**Comment by day1player** [comment]
@denevin as a work around you can check this directory for a list of every package that failed: `C:\ProgramData\chocolatey\lib-bad`

**Comment by day1player** [comment]
fixed in #147
