### ISSUE TITLE
Error Install

### ISSUE THREAD

**Issue by ruudeee** [fireeye/commando-vm#73]
Hi, i'm getting an error while installing commando vm on a fully upated windows 10 machine:

[NuGet] An error occurred while loading packages from 'https://www.myget.org/F/fireeye/api/v2': Unable to connect to the remote server
commandovm.win10.installer.fireeye not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "C:\ProgramData\boxstarter\BuildPackages;https://www.myget.org/F/fireeye/api/v2;https://chocolatey.org/api/v2"

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - commandovm.win10.installer.fireeye - commandovm.win10.installer.fireeye not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "C:\ProgramData\boxstarter\BuildPackages;https://www.myget.org/F/fireeye/api/v2;https://chocolatey.org/api/v2"
Chocolatey : Chocolatey reported an unsuccessful exit code of 1. See
C:\Users\rku\AppData\Local\Boxstarter\boxstarter.log for details.
At C:\ProgramData\boxstarter\BoxStarter.Chocolatey\Invoke-ChocolateyBoxstarter.ps1:199 char:5
+     Chocolatey install $bootstrapPackage -source $source -force:$forc ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,chocolatey

[chocolatey.log](https://github.com/fireeye/commando-vm/files/3296520/chocolatey.log)

**Comment by day1player** [comment]
@ruudeee It looks like there might be something wrong with your network settings in the VM. Make sure you can browse to `www.myget.org` in your browser and then run the script again.
