### ISSUE TITLE
BUG: Wfuzz not working as expected

### ISSUE THREAD

**Issue by day1player** [fireeye/commando-vm#75]
Wfuzz -- is failing due to missing the python library "libcurl" in windows - I'm not entirely sure what the easiest way is to provide this library in windows, reading about it looks like it's one of those issues that will require some thinking as traditional installation methods don't apply. You can download pre-compiled binaries from 3rd party sources but that's not ideal.

**Comment by day1player** [comment]
from @pr0tean #74

**Comment by pr0tean** [comment]
Wfuzz is failing to install easily.

The cinst error bombs out with too little info:

![image](https://user-images.githubusercontent.com/52039659/60200494-2228bc00-983e-11e9-94de-d43d0ce4b132.png)

Directly running the pip install command gives a bit more information:

![image](https://user-images.githubusercontent.com/52039659/60200321-c9f1ba00-983d-11e9-8b7d-60af7241af00.png)

`PS C:\Windows\system32 > py -2 -m pip -qq install wfuzz -v                                                                                                      
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Please specify --curl-dir=/path/to/built/libcurl
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 10 in`

Attempting to `pip install pycurl` results in the same error.

**Comment by pollev** [comment]
I can confirm the same issue is affecting me

**Comment by day1player** [comment]
Issue is open in #134
