### ISSUE TITLE
unable to start db_nmap in msfconsole 

### ISSUE THREAD

**Issue by tgelliott196** [fireeye/commando-vm#8]
How do I start the postgresql to enable the db for msfconsole?

**Comment by veeral-patel** [comment]
Try -

```
systemctl start postgresql
msfdb init
```

From: https://www.offensive-security.com/metasploit-unleashed/using-databases/

**Comment by tgelliott196** [comment]
That’s a Linux cmd.

**Comment by tgelliott196** [comment]
#To use db with MSF in Commando-VM for Windows 10 you need to first:
Dowload  PostgreSQL: https://www.enterprisedb.com/downloads/postgres-postgresql-downloads
During the install add: pgAdmin 4
  Open the program pgAdmin: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\PostgreSQL 11
		#It will open in browser.
  Start POstgreSQL by clicking on server icon at top left
  Ensure to use pw you input during setup
     by default you should have one Server 
     by default you should have one data base: postgres
     by default you should have one user named: postgres

#You can set "PostgreSQL 11" port, pw, name, host address, username, role, etc
   Click PostgreSQL under server, then click properties next to dashboard, then click edit on right. 

#put "bin" and "lib" in windows system enviromental path to run cmd-line tool psql from Windows cmd-line
	PATHs C:\Program Files\PostgreSQL\11\bin and C:\Program Files\PostgreSQL\11\lib to add to envrioment path to run cmd-line: psql -
		To open evnironmental path: Control Panel\System and Security\System, the click Advanced Systems Settings, then click Environmental Variables tab -
		Then under System Variables click Path, click edit, click new, add \bin and \lib paths.
# you should now be able to use psql cmd-line from windows cmd.exe   

example: psql -p 5433 -U postgres postgres
	#This will start a database on local port 5433


MSF database.yml may need to be confiqued for pw and port(I used notepad++).  I also added the MSF user in pgAdmin to match MSF database.yml confiq

**Comment by day1player** [comment]
Thank you @tgelliott196 !! Appreciate the detailed response/solution.
