### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by SmarTIGer** [fireeye/commando-vm#80]
[NuGet] Installing 'winrar 5.71'.
[NuGet] Successfully installed 'winrar 5.71'.

winrar v5.71 [Approved]
winrar package files upgrade completed. Performing other installation steps.
ERROR: This package does not support 64 bit architecture.
The upgrade of winrar was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\winrar\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - winrar (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\winrar\tools\chocolateyInstall.ps1'.
 See log for details.
Chocolatey reported an unsuccessful exit code of -1. See C:\Users\QAX\AppData\Local\Boxstarter\boxstarter.log for details.
+ Boxstarter finished Calling Chocolatey to install winrar. This may take several minutes to complete... 00:00:06.7741226
+ Boxstarter finished Calling Chocolatey to install winrar. This may take several minutes to complete... 00:00:06.7741226
ExitCode: -1
ExitCode: -1
Failed to install winrar

Upgrading the following packages:
Elite.fireeye
By upgrading you accept licenses for the packages.
Elite.fireeye is not installed. Installing...
[NuGet] Attempting to resolve dependency 'kb2533623 '.
[NuGet] Attempting to resolve dependency 'chocolatey-windowsupdate.extension (≥ 1.0.4)'.
[NuGet] Attempting to resolve dependency 'kb2999226 '.
[NuGet] Attempting to resolve dependency 'kb2919355 (≥ 1.0.20160915)'.
[NuGet] Attempting to resolve dependency 'KB2919442 (≥ 1.0.20160915)'.
[NuGet] Attempting to resolve dependency 'visualstudio2017community '.
[NuGet] Attempting to resolve dependency 'chocolatey-visualstudio.extension (≥ 1.8.0)'.
[NuGet] Attempting to resolve dependency 'KB3033929 (≥ 1.0.0)'.
[NuGet] Attempting to resolve dependency 'KB3035131 (≥ 1.0.3)'.
[NuGet] Attempting to resolve dependency 'dotnetfx (≥ 4.6.2.0)'.
[NuGet] Attempting to resolve dependency 'visualstudio-installer (≥ 2.0.0)'.
[NuGet] Attempting to resolve dependency 'visualstudio2017-workload-netcoretools '.
[NuGet] Attempting to resolve dependency 'vcredist2013 (≥ 12.0.30501.20150616)'.
[NuGet] Attempting to resolve dependency 'vcredist140 (≥ 14.16.27027.1)'.
[NuGet] Attempting to resolve dependency 'chocolatey-core.extension (≥ 1.3.3)'.
[NuGet] Attempting to resolve dependency 'netfx-4.6.1-devpack (≥ 4.6.01055.00)'.
[NuGet] Attempting to resolve dependency 'DotNet4.6.1 (≥ 4.6.01055.00)'.
[NuGet] Attempting to resolve dependency 'netfx-4.5.2-devpack (≥ 4.5.5165101)'.
[NuGet] Attempting to resolve dependency 'DotNet4.5.2 (≥ 4.5.2.20140902)'.
[NuGet] Attempting to resolve dependency 'KB2882822 (≥ 1.0.0)'.
[NuGet] Attempting to resolve dependency 'dotnetcore (≥ 2.1.0)'.
[NuGet] Attempting to resolve dependency 'dotnetcore-runtime (= 2.2.5)'.
[NuGet] Attempting to resolve dependency 'dotnetcore-runtime.install (= 2.2.5)'.
Elite.fireeye not installed. An error occurred during installation:
 Unable to resolve dependency 'dotnetcore-runtime.install (= 2.2.5)'.
Elite.fireeye package files upgrade completed. Performing other installation steps.
The upgrade of Elite.fireeye was NOT successful.
Elite.fireeye not installed. An error occurred during installation:
 Unable to resolve dependency 'dotnetcore-runtime.install (= 2.2.5)'.

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - Elite.fireeye (exited 1) - Elite.fireeye not installed. An error occurred during installation:
 Unable to resolve dependency 'dotnetcore-runtime.install (= 2.2.5)'.

Did you know the proceeds of Pro (and some proceeds from other
 licensed editions) go into bettering the community infrastructure?
 Your support ensures an active community, keeps Chocolatey tip top,
 plus it nets you some awesome features!
 https://chocolatey.org/compare
Chocolatey reported an unsuccessful exit code of 1. See C:\Users\QAX\AppData\Local\Boxstarter\boxstarter.log for details.
+ Boxstarter finished Calling Chocolatey to install Elite.fireeye. This may take several minutes to complete... 00:00:10.2729344
+ Boxstarter finished Calling Chocolatey to install Elite.fireeye. This may take several minutes to complete... 00:00:10.2729344
ExitCode: 1
ExitCode: 1
Failed to install Elite.fireeye

[NuGet] Installing 'wfuzz.fireeye 2.4.20190522'.
[NuGet] Successfully installed 'wfuzz.fireeye 2.4.20190522'.

wfuzz.fireeye v2.4.20190522
wfuzz.fireeye package files upgrade completed. Performing other installation steps.
ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop:     ERROR: Complete output from command python setup.py egg_info:
The upgrade of wfuzz.fireeye was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\wfuzz.fireeye\Tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - wfuzz.fireeye (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\wfuzz.fireeye\Tools\chocolateyInstall.ps1'.
 See log for details.

**Comment by day1player** [comment]
Try running these commands:
```
cinst winrar
cinst Elite.fireeye
```
Wfuzz is currently bugged #75 and will be fixed in the next update

**Comment by SmarTIGer** [comment]
> Try running these commands from an administrative terminal:
> 
> ```
> cinst winrar
> cinst Elite.fireeye
> ```
> 
> Wfuzz is currently bugged #75 and will be fixed in the next update

COMMANDO 2019/07/04 周四 20:52:38.91
C:\Windows\system32>cinst winrar
Chocolatey v0.10.15
Installing the following packages:
winrar
By installing you accept licenses for the packages.
Progress: Downloading winrar 5.71... 100%

winrar v5.71 [Approved]
winrar package files install completed. Performing other installation steps.
ERROR: This package does not support 64 bit architecture.
The install of winrar was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\winrar\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - winrar (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\winrar\tools\chocolateyInstall.ps1'.
 See log for details.

COMMANDO 2019/07/04 周四 20:54:13.10
C:\Windows\system32>cinst Elite.fireeye
Chocolatey v0.10.15
Installing the following packages:
Elite.fireeye
By installing you accept licenses for the packages.
Progress: Downloading Elite.fireeye 1.0.0.1... 100%
Elite.fireeye not installed. An error occurred during installation:
 Unable to resolve dependency 'dotnetcore-runtime.install (= 2.2.5)'.
Elite.fireeye package files install completed. Performing other installation steps.
The install of Elite.fireeye was NOT successful.
Elite.fireeye not installed. An error occurred during installation:
 Unable to resolve dependency 'dotnetcore-runtime.install (= 2.2.5)'.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - Elite.fireeye (exited 1) - Elite.fireeye not installed. An error occurred during installation:
 Unable to resolve dependency 'dotnetcore-runtime.install (= 2.2.5)'.

**Comment by day1player** [comment]
Removed both packages from install.
