### ISSUE TITLE
commando seems to disable windows updates for Windows 10 insider preview

### ISSUE THREAD

**Issue by hscu** [fireeye/commando-vm#82]
Hi, 
I installed commando vm on a copy of a Windows 10 Insider preview VM (build 18898). This copy doesn't update to the current Windows 10 Insider builds any longer although the original Windows 10 Insider VM does. Other Windows updates like Windows Defender seem to work.
Any ideas?

**Comment by Paradoxis** [comment]
Unfortunately someone thought it was a great idea to knowlingly brick this feature ([it's even documented in the source](https://github.com/fireeye/commando-vm/blame/master/commandovm.win10.preconfig.fireeye/tools/Win10.psm1#L17)), reverting the registry keys and re-enabling the services should make it work again.

@fireeye please disable this 'feature' or at least make it optional, it prevents everyone from using WSL2 which means tools like nmap will not work in the current Kali subsystem

**Comment by ThomasArmstrongJr1247** [comment]
@Paradoxis thanks so much for the powershell function. It almost fixed my insider preview issue. I was wondering if you knew what to do with the issue I have now with it. In the tab for upgrading to windows insider the option is no longer available. It reads "insider previews may be installed before this PC restarts". I have attempted to remedy it already by deleting the associated registries and made sure that my settings are correct in Group Policy and the administrative center. I can provide any screenshots to help. Also how are you able to view which account has insider status?

**Comment by Paradoxis** [comment]
@ThomasArmstrongJr1247 haven't run into that issue before unfortunately, I managed to fix mine with the aforementioned powershell function. Did you link a microsoft account with your vm before trying to install the insider preview? That's somehow also required (just make a junk account as to not let malware steal your info if you decide to do reversing on the box)

**Comment by day1player** [comment]
Please use this as a workaround if you run into this issue. We will not be enabling telemetry on the default install of Commando.
