### ISSUE TITLE
Proxycap install failure.

### ISSUE THREAD

**Issue by 6869677a** [fireeye/commando-vm#83]
**Describe the bug and expected behavior**
ERROR: Checksum for 'C:\Users\<users>\AppData\Local\Temp\ProxyCap.installer.msi' did not meet '88ecc3bd356b9dad5f8754df4b9d7ec34c6d45318bfee754c686aa6d7f589558' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
The install of proxycap.fireeye was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\proxycap.fireeye\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

**To Reproduce**
1. open CMD and type cinst proxycap.fireeye
2. fails to install

**Screenshots**

**Version**
 - OS: win10 latest

**Additional context**
It was mentioned in another ticket to type cup proxycap.fireeye but because it failed initial install it will try to install for the first time and fails because of hash.

**Comment by day1player** [comment]
I have reached out to the authors of the tool. We are having an issue with the hash not matching. They have not published hashes on their website.

**Comment by day1player** [comment]
Fixed
