### ISSUE TITLE
BUG: gpedit fails to open

### ISSUE THREAD

**Issue by Raikia** [fireeye/commando-vm#85]
**Describe the bug and expected behavior**
Some recent change now causes "gpedit" to not open and just to crash.

**To Reproduce**
1. Open gpedit from anywhere
2. Crashes with an error (even if you click "Ignore", it never opens)

Also

1. Open "mmc", which works fine.
2. Add "Snap-in" for "Group Policy Editor"
3. It adds fine but just has an icon in the left pane (look at screenshots below)
4. Click icon, window crashes.

**Screenshots**
Raw crash:

![Crash](https://i.vgy.me/CpliHM.png)

MMC works fine until the snapin is loaded:

![Crash](https://i.imgur.com/ioTPBo7.png)

![Crash](https://i.imgur.com/DJVmD41.png)

^ After you click on the icon, it closes and crashes.

**Version**
 - OS: Windows 10 1903, fresh install (and made sure the install completed without errors)

**Additional context**
This issue was introduced in 1.3.  It used to work.  Possibly due to however #68 was fixed?

**Comment by day1player** [comment]
Stale.. Havent been able to reproduce
