### ISSUE TITLE
FEATURE: Replace Adobe Reader

### ISSUE THREAD

**Issue by thereisnotime** [fireeye/commando-vm#87]
**Problem**
The install script downloads and installs Adobe Acrobat Reader and an update for it. This increases the total time for install by around 400 MB and few more minutes depending on the host machine. 
```
[2019-08-02T21:56:08.1355540+01:00:::PID 4332] Download of AcroRdrDC1901020064_MUI.exe (261.05 MB) completed.
Download of AcroRdrDC1901020064_MUI.exe (261.05 MB) completed.
[2019-08-02T22:02:24.7965976+01:00:::PID 4332] Download of AcroRdrDCUpd1901220035_MUI.msp (132.78 MB) completed.
Download of AcroRdrDCUpd1901220035_MUI.msp (132.78 MB) completed.
```

**Proposal**
Replace AAR with SumatraPDF which is a lot lighter (~5 MB zipped) or some other FOSS PDF viewer (PDFXChange/FoxIt).

**Comment by day1player** [comment]
removed adobe from default install #147
