### ISSUE TITLE
BUG with Docker Desktop 

### ISSUE THREAD

**Issue by ghost** [fireeye/commando-vm#92]
**Bug on installation with Docker Desktop**
Installation of Docker Desktop fails and subsequently blocks Spiderfoot and amass from installing 

**To Reproduce**
1. Create Windows 10 VM or Hyper-v (unsupported) with Bios or Uefi
2. Install all windows Updates and activate
3. Pull and Install Script from Github

**Screenshots**

![image](https://user-images.githubusercontent.com/6025655/62783125-0ad72280-babc-11e9-8fd3-9172a50ac848.png)

**Version**
 - HostOS: Windows 10
 - VmOS: Windows 10 1803, 1903, LTSC 2019
- Hypervisor: Vmware Workstation Pro 15.1.0 build-13591040

**Wanted Solution**
Is there Something to set in the .VMX Config ? 
Please see below the current Config for Hyper-V (unsupported)

- .encoding = "windows-1252"
- config.version = "8"
- virtualHW.version = "15"
- pciBridge0.present = "TRUE"
- pciBridge4.present = "TRUE"
- pciBridge4.virtualDev = "pcieRootPort"
- pciBridge4.functions = "8"
- pciBridge5.present = "TRUE"
- pciBridge5.virtualDev = "pcieRootPort"
- pciBridge5.functions = "8"
- pciBridge6.present = "TRUE"
- pciBridge6.virtualDev = "pcieRootPort"
- pciBridge6.functions = "8"
- pciBridge7.present = "TRUE"
- pciBridge7.virtualDev = "pcieRootPort"
- pciBridge7.functions = "8"
- vmci0.present = "TRUE"
- hpet0.present = "TRUE"
- displayName = "CommandoVM"
- guestOS = "winhyperv"
- nvram = "CommandoVM.nvram"
- virtualHW.productCompatibility = "hosted"
- powerType.powerOff = "soft"
- powerType.powerOn = "soft"
- powerType.suspend = "soft"
- powerType.reset = "soft"
- tools.syncTime = "FALSE"
- sound.autoDetect = "TRUE"
- sound.virtualDev = "hdaudio"
- sound.fileName = "-1"
- sound.present = "TRUE"
- numvcpus = "8"
- cpuid.coresPerSocket = "8"
- vcpu.hotadd = "TRUE"
- memsize = "16384"
- mem.hotadd = "TRUE"
- sata0.present = "TRUE"
- nvme0.present = "TRUE"
- nvme0:0.fileName = "CommandoVM-000002.vmdk"
- nvme0:0.present = "TRUE"
- sata0:1.deviceType = "cdrom-image"
- sata0:1.fileName = "K:\VmwareWorkstation\windows.iso"
- sata0:1.present = "TRUE"
- usb.present = "TRUE"
- ehci.present = "TRUE"
- usb_xhci.present = "TRUE"
- ethernet0.connectionType = "nat"
- ethernet0.addressType = "generated"
- ethernet0.virtualDev = "e1000"
- serial0.fileType = "thinprint"
- serial0.fileName = "thinprint"
- ethernet0.present = "TRUE"
- serial0.present = "TRUE"
- extendedConfigFile = "CommandoVM.vmxf"
- vvtd.enable = "TRUE"
- floppy0.present = "FALSE"
- vhv.enable = "TRUE"
- vpmc.enable = "TRUE"
- gui.lastPoweredViewMode = "fullscreen"
- tools.upgrade.policy = "useGlobal"
- uuid.bios = "56 4d b1 21 1b dd e7 a0-74 ac d1 9a fb 79 0b e9"
- uuid.location = "56 4d b1 21 1b dd e7 a0-74 ac d1 9a fb 79 0b e9"
- nvme0:0.redo = ""
- pciBridge0.pciSlotNumber = "17"
- pciBridge4.pciSlotNumber = "21"
- pciBridge5.pciSlotNumber = "22"
- pciBridge6.pciSlotNumber = "23"
- pciBridge7.pciSlotNumber = "24"
- usb.pciSlotNumber = "32"
- ethernet0.pciSlotNumber = "33"
- sound.pciSlotNumber = "34"
- ehci.pciSlotNumber = "35"
- usb_xhci.pciSlotNumber = "160"
- vmci0.pciSlotNumber = "36"
- sata0.pciSlotNumber = "37"
- nvme0.pciSlotNumber = "192"
- vmotion.checkpointFBSize = "4194304"
- vmotion.checkpointSVGAPrimarySize = "268435456"
- ethernet0.generatedAddress = "00:0c:29:79:0b:e9"
- ethernet0.generatedAddressOffset = "0"
- vmci0.id = "-75953175"
- monitor.phys_bits_used = "43"
- cleanShutdown = "FALSE"
- softPowerOff = "FALSE"
- svga.guestBackedPrimaryAware = "TRUE"
- gui.exitOnCLIHLT = "TRUE"
- usb_xhci:4.present = "TRUE"
- usb_xhci:4.deviceType = "hid"
- usb_xhci:4.port = "4"
- usb_xhci:4.parent = "-1"
- unity.wasCapable = "TRUE"

Here is the Log of Docker Desktop

[Dockerlog.txt](https://github.com/fireeye/commando-vm/files/3486627/Dockerlog.txt)

**Comment by Johnson90512** [comment]
Have this issue on 2 different clean installs

**Comment by Sennless** [comment]
tried it yesterday also on KVM in a Proxmox VM with the KVM Processor and Host CPU pass trough.
but after further testing i would assume this an issue with Docker Desktop itself.
it is still completely broken on Windows with nested virtualization. 
Maybe i find an old Desktop PC at work to test the Install script on hardware.

**Comment by day1player** [comment]
It is possible to do this but having a Windows HOST machine there are some hoops you have to get through. @htnhan any ideas here?

**Comment by htnhan** [comment]
@Sennless Regarding `docker` issue, please follow this URL to make sure you meet all the requirement for docker to work with nested virtualization: `https://docs.docker.com/docker-for-windows/install/`. Even though you can force VirtualBox or VMWare to support nested virtualization by modifying the VM config file manually, it is very unstable, and not recommended.

**Comment by joeminicucci** [comment]
To follow up in 2020, [see Docker's updated docs](https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-desktop-in-nested-virtualization-scenarios)

> Docker Desktop can run inside a Windows 10 VM running on apps like Parallels or VMware Fusion on a Mac provided that the VM is properly configured. However, problems and intermittent failures may still occur due to the way these apps virtualize the hardware. For these reasons, Docker Desktop is not supported in nested virtualization scenarios. It might work in some cases, and not in others.

**Comment by day1player** [comment]
Our workaround for this problem will be to create new profiles for the install, with the default install not containing Docker or Docker packages. #95
