### ISSUE TITLE
Kali on commando vm issueBUG

### ISSUE THREAD

**Issue by strongestmanever** [fireeye/commando-vm#93]
**Describe the bug and expected behavior**
Hello, once I launch kali on a fresh installed commando VM I got this error:
'kali.exe' is not recognized as an internal or external command,
operable program or batch file.

**Screenshots**
![image](https://user-images.githubusercontent.com/1062481/62857263-73f6aa00-bcf7-11e9-87cf-5d0c9ecf8e62.png)

**Version**
 - OS: Win10

**Comment by day1player** [comment]
Looks like it wasn't installed properly. Try running this command:

`cinst -y kali.fireeye --timeout 7200`

**Comment by day1player** [comment]
Make sure you are in an administrative cmd prompt

**Comment by htnhan** [comment]
@strongestmanever, Can you also check to see if your windows 10 meets all the requirements for WSL?

Thanks

**Comment by strongestmanever** [comment]
Hi all,

Thank you for your response.

- Yes, I am running it as admin

- 
![image](https://user-images.githubusercontent.com/1062481/62927788-8fc18500-bdb7-11e9-9461-0dd9f7f58835.png)

- I am checking if the machine has all the WSL prequisitions

Regards

**Comment by strongestmanever** [comment]
Hello all,

I have installed and launched Ubuntu on the windows 10.
![image](https://user-images.githubusercontent.com/1062481/62940343-ad044c80-bdd3-11e9-85d8-4b559a3044b3.png)

So I guess WSL is ok.

Regards,

**Comment by day1player** [comment]
@strongestmanever Good to know WSL is working. Try running these commands:
`cinst -y wsl-kalilinux -f`
And when that is done run this command:
`cinst -y kali.fireeye -f --timeout 7200`

This will force the reinstall. Let us know if you get it running with that.

**Comment by strongestmanever** [comment]
Hi all,

I have the same result even after executing these command.

I will install kali directly from the Windows app store and see.

Thank you all.

**Comment by goremageddon** [comment]
I am having issues as well with kali-gui ctd when clicking anything

**Comment by day1player** [comment]
fixed.
