### ISSUE TITLE
Add multiple default install profiles

### ISSUE THREAD

**Issue by vpzed** [fireeye/commando-vm#95]
Since nested virtualization is not well supported and features using nested virtualization are being added, this will likely create installation trouble for many people and the issue reports that come along with that trouble. A new feature suggestion for the installation script would be an option to opt-in/opt-out of the packages that rely on (nested) virtualization.  That way folks on bare metal or who want to go the experimental route can choose to install them, and the those who want a stable virtual machine can skip them. This would be more attractive for new users than a custom install, and building adoption by new users helps the project grow.

It would also be a good idea to update the README page with more information about the pitfalls of nested virtualization.  Currently the information on nested virtualization is minimal which can make people assume it's no big deal.

**Comment by CurioCT** [comment]
Does this mean it is actually impossible to run the docker desktop in v2.0 in a virtualbox VM on windows 10 no matter what settings I try? because Hyper V and virtualbox cant properly co-exist?

**Comment by day1player** [comment]
It is not impossible, we've got it working on some machines but its not an easy fix. It's not something we can fix during install, nor can we fix it by providing instructions on how to do it because there are a lot of variables when using a Windows host machine.

**Comment by CurioCT** [comment]
can you at least tell us the settings used in virtualbox they should be relatively simple? so that we can look at troubleshooting the host settings ourselves?

**Comment by day1player** [comment]
It's a bit more involved than just making setting changes in the GUI. You need to open up some hidden config files and make changes for them. I can give you a pointer to look for something like "enable nested virtualization in vmware/virtualbox windows 10". Docker is very similar to VMware/virtualbox because it does some virtualization, so you are needing to figure out how to run virtualized Docker containers inside of a virtual machine. This is where the issues for the windows hosts arise.

**Comment by CurioCT** [comment]
Thanks that's a great start point :D

**Comment by CurioCT** [comment]
Looks like its AMD arch only at the moment on Vbox. :( 

Are there any community support forums / channels for this yet didn't see anything on google / twitter

**Comment by day1player** [comment]
We have a channel in the BloodHound Gang slack, you might be able to ask some of the people in there if they have been able to figure it out. You can also try VMware Player as it is also free.

**Comment by CurioCT** [comment]
thanks once again :D

**Comment by day1player** [comment]
fixed in #147
