### ISSUE TITLE
BUG Cannot bind argument to parameter 'Path' because it is null.

### ISSUE THREAD

**Issue by hackdefendr** [fireeye/commando-vm#97]
**Describe the bug and expected behavior**

Running 'cup all' errors with the below:

```
ERROR: Cannot bind argument to parameter 'Path' because it is null.
The upgrade of adaclscanner.fireeye was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\ADACLScanner.fireeye\Tools\chocolateyInstall.ps1'.
 See log for details.

```
**To Reproduce**
1. Open an elevated command prompt
2. Run: cup all
3. Wait a minute
4. See error above

**Screenshots**
Just the error.

**Version**
 - OS: Windows 10 (1803)

**Additional context**
Why is the PATH variable not getting set?

**Comment by fakename12345cat** [comment]
Same problem

**Comment by cedricpernet** [comment]
same problem

**Comment by hackdefendr** [comment]
That was fun to read, I managed to get the solution...so, thanks for that @cedricpernet 

### SOLUTION

1. Open Powershell as Administrator
2. Run:
> [Environment]::SetEnvironmentVariable("RAW_TOOLS_DIR", "%systemdrive%\Tools", 2)
3. Run: 
> cup all
