### ISSUE TITLE
BUG: Upgrade of metasploit fails - remote file either does not exist, is unauthorized or forbidden

### ISSUE THREAD

**Issue by forensic65x** [fireeye/commando-vm#98]
I ran the following from the admin powershell prompt:

choco upgrade metasploit-flare -f

Below is the output from that command, including the errors about the file not being found.

Upgrading the following packages:
metasploit.flare
By upgrading you accept licenses for the packages.

You have metasploit.flare v5.0.42.20190815 installed. Version 5.0.43.20190826 is available based on your source(s).
Progress: Downloading metasploit.flare 5.0.43.20190826... 100%

metasploit.flare v5.0.43.20190826 (forced)
metasploit.flare package files upgrade completed. Performing other installation steps.
Attempt to get headers for https://windows.metasploit.com/metasploit-framework-5.0.43%2B20190826152646-1rapid7-1-x64.msi failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://windows.metasploit.com/metasploit-framework-5.0.43%2B20190826152646-1rapid7-1-x64.msi'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
Downloading metasploit.flare 64 bit
  from 'https://windows.metasploit.com/metasploit-framework-5.0.43%2B20190826152646-1rapid7-1-x64.msi'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://windows.metasploit.com/metasploit-framework-5.0.43%2B20190826152646-1rapid7-1-x64.msi'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
The upgrade of metasploit.flare was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\metasploit.flare\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - metasploit.flare (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\metasploit.flare\tools\chocolateyInstall.ps1'.
 See log for details.

**Comment by DevTronX** [comment]
I am running into the same issue with a brand new install. see below:

Vm is running windows 10, in vmware workstation 15, if that helps at all. 

Chocolatey v0.10.15
Upgrading the following packages:
metasploit.flare
By upgrading you accept licenses for the packages.
metasploit.flare is not installed. Installing...
Progress: Downloading metasploit.flare 5.0.43.20190826... 100%
Progress: Downloading metasploit.flare 5.0.43.20190826... 100%

metasploit.flare v5.0.43.20190826 (forced)
metasploit.flare package files upgrade completed. Performing other installation steps.
Attempt to get headers for https://windows.metasploit.com/metasploit-framework-5.0.43%2B20190826152646-1rapid7-1-x64.msi failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://windows.metasploit.com/metasploit-framework-5.0.43%2B20190826152646-1rapid7-1-x64.msi'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
Downloading metasploit.flare 64 bit
  from 'https://windows.metasploit.com/metasploit-framework-5.0.43%2B20190826152646-1rapid7-1-x64.msi'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://windows.metasploit.com/metasploit-framework-5.0.43%2B20190826152646-1rapid7-1-x64.msi'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
The upgrade of metasploit.flare was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\metasploit.flare\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - metasploit.flare (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\metasploit.flare\tools\chocolateyInstall.ps1'.
 See log for details.

**Comment by cathedrall** [comment]
Can confirm, this is happening on a build I performed today, in addition to taskbar items not appearing as they should.

**Comment by amanjohar** [comment]
Can confirm, this is happening along with taskbar items not appearing, docker fails to start and the following packages are not installing amass proxycap spiderfoot wfuzz x64dbg.

**Comment by Donovoi** [comment]
Can also confirm taskbar items not appearing, docker fails to start and everything is awesome

**Comment by day1player** [comment]
Fixed
