### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by bhaizlett123** [fireeye/commando-vm#99]
**Describe the bug and expected behavior**

I just installed windows 10 VM

Windows 10 pro
Build 1903
OS Build - 18362.387

Fully updated

I download the command-vm, i did the fully unrestricted bypass and the i do the install.ps1

And after some time that it runs, it errors out here and just stops

Chocolatey upgraded 0/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Chocolatey v0.10.15
Installing the following packages:
powershell
By installing you accept licenses for the packages.
powershell not installed. An error occurred during installation:
 The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
powershell package files install completed. Performing other installation steps.
The install of powershell was NOT successful.
powershell not installed. An error occurred during installation:
 The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - powershell (exited 1) - powershell not installed. An error occurred during installation:
 The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
Refreshing environment variables from registry for cmd.exe. Please wait...Finished..
[+] Performing normal installation...
Chocolatey v0.10.15
Upgrading the following packages:
common.fireeye
By upgrading you accept licenses for the packages.
common.fireeye v3.0.0.3 is the latest version available based on your source(s).

Chocolatey upgraded 0/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Chocolatey v0.10.15
Nothing to change. Config already set.
Chocolatey v0.10.15
Upgrading the following packages:
commandovm.win10.preconfig.fireeye
By upgrading you accept licenses for the packages.
commandovm.win10.preconfig.fireeye v2.0 is the latest version available based on your source(s).

Chocolatey upgraded 0/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Install-BoxstarterPackage : The term 'Install-BoxstarterPackage' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.
At C:\Users\admin\Desktop\commando-vm-master\install.ps1:361 char:5
+     Install-BoxstarterPackage -PackageName commandovm.win10.installer ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Install-BoxstarterPackage:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Install-BoxStarterPackage : The term 'Install-BoxStarterPackage' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.
At C:\Users\admin\Desktop\commando-vm-master\install.ps1:362 char:5
+     Install-BoxStarterPackage -PackageName commandovm.win10.config.fi ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Install-BoxStarterPackage:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\admin\Desktop\commando-vm-master>

**Comment by day1player** [comment]
It looks like some sort of TLS/SSL issue is occurring. Are you by chance trying to install behind a proxy? You may have to install some additional SSL certs or (preferred) install on a separate network. 

Let us know if you continue having issues.
